version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /core
    schedule:
      interval: weekly
    target-branch: main
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /connectors
    schedule:
      interval: weekly
    target-branch: main
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /sdks/go
    schedule:
      interval: weekly
    target-branch: main
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /ai
    schedule:
      interval: weekly
    target-branch: main

  - package-ecosystem: npm
    directory: /console
    schedule:
      interval: weekly
    target-branch: main
