package main

// @title Irmin API
// @version 1.0.0
// @description Core API for the Irmin data management platform
// @termsOfService http://irmin.co/terms

// @contact.name Irmin Team
// @contact.url https://irmin.co
// @contact.email hello@irmin.co

// @host api.irmin.co
// @BasePath /api/v1
// @schemes https

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @description User's JWT token with Bearer prefix provided by Clerk on login

// @securityDefinitions.apikey SystemTokenAuth
// @in header
// @name Authorization
// @description System API token used for internal operations

import (
	"context"
	"flag"
	"irmin-api/cache"
	"irmin-api/db"
	"irmin-api/engine"
	"irmin-api/lib"
	"irmin-api/locales"
	"irmin-api/orchestrator"
	"irmin-api/permissions"
	"irmin-api/routes"
	"irmin-api/services"
	"irmin-api/templatefiles"
	"irmin-api/utils"
	"log"
	"log/slog"
	"strings"
	"time"

	irminsqids "github.com/IrminData/irmin-sdk-go/sqids"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/compress"
	"github.com/gofiber/fiber/v3/middleware/cors"
	"github.com/gofiber/fiber/v3/middleware/helmet"
	"github.com/gofiber/fiber/v3/middleware/idempotency"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/recover"
	"github.com/gofiber/fiber/v3/middleware/requestid"

	_ "irmin-api/docs" // This will be generated by swag

	mcpserver "irmin-api/mcp"
)

const (
	// MaxRequestBodySize is the maximum size of request body in bytes (5 GB).
	MaxRequestBodySize = 5 * 1024 * 1024 * 1024
	// CachePreflightDuration is the duration for which preflight requests are cached.
	CachePreflightDuration = 24 * time.Hour
)

// setupDefaultTags seeds default tags for all workspaces.
func setupDefaultTags(d *db.Database) error {
	// Fetch all workspaces
	workspaces, fetchWorkspacesErr := d.GetAllWorkspaces()
	if fetchWorkspacesErr != nil {
		return fetchWorkspacesErr
	}

	// Seed default tags for every workspace
	for _, workspace := range workspaces {
		seedDefaultTagsErr := lib.SeedDefaultTags(d.DB, workspace.ID)
		if seedDefaultTagsErr != nil {
			return seedDefaultTagsErr
		}
	}

	return nil
}

func setupRolesAndPolicies(d *db.Database, overridePolicies *bool) error {
	// Seed initial roles
	if seedRolesErr := lib.SeedRoles(d); seedRolesErr != nil {
		return seedRolesErr
	}

	// Fetch all workspaces
	workspaces, fetchWorkspacesErr := d.GetAllWorkspaces()
	if fetchWorkspacesErr != nil {
		return fetchWorkspacesErr
	}

	// Set default policies for every workspace
	for _, workspace := range workspaces {
		setDefaultPoliciesErr := lib.SetDefaultPolicies(d.DB, workspace.ID, *overridePolicies)
		if setDefaultPoliciesErr != nil {
			return setDefaultPoliciesErr
		}
	}

	// Set default role for every user without a role
	if assignDefaultRolesErr := lib.AssignDefaultRolesToUsersWithoutRoles(d); assignDefaultRolesErr != nil {
		return assignDefaultRolesErr
	}

	return nil
}

// setupDatabase initializes and configures the database based on command line flags.
func setupDatabase(env *utils.CoreAPIEnv) (*db.Database, error) {
	d, err := db.InitialiseDB(env)
	if err != nil {
		return nil, err
	}

	// Handle command line flags
	reset := flag.Bool("reset", false, "Reset the database")
	migrate := flag.Bool("migrate", false, "Run database migrations")
	overridePolicies := flag.Bool("override-policies", false, "Override existing policies")
	seedTags := flag.Bool("seed-tags", false, "Seed default tags for all workspaces")
	seedTemplates := flag.Bool("seed-templates", false, "Seed templates from embedded files")
	flag.Parse()

	// Empty the database if the reset flag is set
	if *reset {
		if dbResetErr := d.Reset(); dbResetErr != nil {
			return nil, dbResetErr
		}
	}

	// Run database migrations if the migrate flag is set
	if *migrate {
		// Create database tables, add indexes, or update existing once
		if dbMigrateErr := d.Migrate(); dbMigrateErr != nil {
			return nil, dbMigrateErr
		}

		// Setup roles and policies
		if setupRolesAndPoliciesErr := setupRolesAndPolicies(d, overridePolicies); setupRolesAndPoliciesErr != nil {
			return nil, setupRolesAndPoliciesErr
		}
	}

	// Seed default tags for all workspaces if the seedTags flag is set
	if *seedTags {
		if setupDefaultTagsErr := setupDefaultTags(d); setupDefaultTagsErr != nil {
			return nil, setupDefaultTagsErr
		}
	}

	// Seed templates if the seedTemplates flag is set
	if *seedTemplates {
		if seedTemplatesErr := templatefiles.SeedTemplates(d, slog.Default()); seedTemplatesErr != nil {
			return nil, seedTemplatesErr
		}
	}

	return d, nil
}

// setupFiberApp creates and configures a new Fiber application.
func setupFiberApp(env *utils.CoreAPIEnv, appCacheMiddleware fiber.Handler) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName:   "Irmin API",
		BodyLimit: MaxRequestBodySize,
		ErrorHandler: func(c fiber.Ctx, err error) error {
			return c.Status(fiber.StatusInternalServerError).SendString(err.Error())
		},
	})

	// 1. Recover: Must be first. It needs to wrap every other handler
	// to catch any panics that might occur anywhere in the chain.
	app.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))

	// 2. CORS: Must be very early. It needs to handle preflight OPTIONS
	// requests immediately, before they hit other middleware like logging,
	// caching, or authentication.
	if env.CorsEnabled {
		app.Use(setupCORS(env))
	}

	// 3. Request ID: Assigns a unique ID to the request. This should be
	// early so that the logger and any subsequent tracing can use the ID.
	app.Use(requestid.New())

	// 4. Logger: Logs information about the request. It benefits from the
	// request ID being set and can log the final status of the request
	// after all other handlers have run.
	app.Use(logger.New(logger.Config{
		Format: "${pid} ${locals:requestid} ${status} - ${method} ${path}\n",
	}))

	// 5. Helmet: Adds security-related HTTP headers. It's a good general
	// security measure to have in place before processing the request further.
	if env.HelmetEnabled {
		app.Use(helmet.New())
	}

	// 6. Cache: This is a "gatekeeper". If a valid cached response exists
	// for a GET request, it will be served immediately, and no further
	// handlers (like idempotency or your main business logic) will be executed.
	// This provides a significant performance boost.
	app.Use(appCacheMiddleware)

	// 7. Idempotency: Another "gatekeeper", primarily for POST/PATCH requests.
	// It prevents duplicate operations. It should come after caching but before
	// your main application logic.
	if env.IdempotencyEnabled {
		app.Use(idempotency.New())
	}

	// 8. Compress: This is a "response modifier". It should be last.
	// It acts on the final response body generated by your route handlers
	// just before it's sent to the client. Placing it here ensures you don't
	// waste CPU cycles compressing something that might have been served
	// from cache.
	app.Use(compress.New(compress.Config{Level: compress.LevelBestSpeed}))

	return app
}

// setupCORS configures and returns the CORS middleware.
func setupCORS(env *utils.CoreAPIEnv) fiber.Handler {
	allowedOrigins := strings.Split(env.AllowedOrigins, ",")
	for i, origin := range allowedOrigins {
		allowedOrigins[i] = strings.TrimSpace(origin)
	}
	log.Println("Allowed origins:", allowedOrigins)

	return cors.New(cors.Config{
		AllowOrigins:     allowedOrigins,
		AllowCredentials: true,
		AllowHeaders: []string{
			"Origin",
			"Content-Type",
			"Accept",
			"Authorization",
			"X-Requested-With",
			"Accept-Language",
			"Referer",
			"Cache-Control",
		},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		MaxAge:       int(CachePreflightDuration.Seconds()),
	})
}

// setupServices initializes all required services.
func setupServices(
	env *utils.CoreAPIEnv,
	database *db.Database,
	cacheStorage fiber.Storage,
) (*orchestrator.Orchestrator, *irminsqids.SQIDManager, *locales.LocaleManager, *permissions.Service, error) {
	// Initialize data engine
	dataEngine, err := engine.NewClient(context.Background(), "en", slog.Default(), env, database)
	if err != nil {
		return nil, nil, nil, nil, err
	}

	// Initialize orchestrator
	orchestrator := orchestrator.NewOrchestrator(database, slog.Default(), env, dataEngine, cacheStorage)
	if env.OrchestratorEnabled {
		go func() {
			if orchestratorStartErr := orchestrator.StartOrchestrator(context.Background()); orchestratorStartErr != nil {
				log.Printf("Orchestrator error: %v", orchestratorStartErr)
			}
		}()
	}

	// Initialize SQID manager
	sqidManager := irminsqids.NewSQIDManager(env.SqidAlphabet)

	// Initialize locale manager
	localeManager, err := locales.New()
	if err != nil {
		return nil, nil, nil, nil, err
	}

	// Initialize permission service
	permissionService := permissions.NewService(database, slog.Default())

	return orchestrator, sqidManager, localeManager, permissionService, nil
}

// startServer starts the Fiber server in a goroutine.
func startServer(app *fiber.App, env *utils.CoreAPIEnv) {
	go func() {
		if err := app.Listen(":" + env.Port); err != nil {
			log.Printf("Server error: %v", err)
		}
	}()
}

func main() {
	// Load environment variables
	env, err := utils.LoadEnv()
	if err != nil {
		log.Fatalf("failed to load environment variables: %v", err)
	}

	// Setup database
	database, err := setupDatabase(env)
	if err != nil {
		log.Fatalf("failed to setup database: %v", err)
	}

	// Initialize cache storage and middleware
	cacheStorage := cache.NewDefaultStorage()
	appCacheMiddleware := cache.NewAppCacheMiddleware(cacheStorage)

	// Setup Fiber app
	app := setupFiberApp(env, appCacheMiddleware)

	// Setup services
	orchestrator, sqidManager, localeManager, permissionService, err := setupServices(env, database, cacheStorage)
	if err != nil {
		log.Fatalf("failed to setup services: %v", err)
	}

	// Create API services
	apiServices := services.NewAPIServices(
		database,
		slog.Default(),
		env,
		orchestrator,
		sqidManager,
		localeManager,
		permissionService,
		cacheStorage,
	)

	// Register routes
	routes.RegisterAPIRoutes(
		app,
		apiServices,
	)

	// Mount MCP streamable HTTP handler inside the main app
	mcpserver.RegisterFiber(app, apiServices)

	// Start servers
	startServer(app, env)

	// Keep the main process running
	select {}
}
