package main

// @title Irmin API
// @version 1.0.0
// @description Core API for the Irmin data management platform
// @termsOfService http://irmin.co/terms

// @contact.name Irmin Team
// @contact.url https://irmin.co
// @contact.email hello@irmin.co

// @host api.irmin.co
// @BasePath /api/v1
// @schemes https

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @description User's JWT token with Bearer prefix provided by Clerk on login

// @securityDefinitions.apikey SystemTokenAuth
// @in header
// @name Authorization
// @description System API token used for internal operations

import (
	"context"
	"flag"
	"fmt"
	"irmin-api/cache"
	"irmin-api/db"
	"irmin-api/engine"
	"irmin-api/gc"
	"irmin-api/lakefs"
	"irmin-api/lib"
	"irmin-api/locales"
	"irmin-api/orchestrator"
	"irmin-api/permissions"
	"irmin-api/routes"
	"irmin-api/services"
	"irmin-api/templatefiles"
	"irmin-api/utils"
	"log"
	"log/slog"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	irminsqids "github.com/IrminData/irmin-sdk-go/sqids"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/compress"
	"github.com/gofiber/fiber/v3/middleware/cors"
	"github.com/gofiber/fiber/v3/middleware/helmet"
	"github.com/gofiber/fiber/v3/middleware/idempotency"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/recover"
	"github.com/google/uuid"

	_ "irmin-api/docs" // This will be generated by swag

	mcpserver "irmin-api/mcp"
)

const (
	// CachePreflightDuration is the duration for which preflight requests are cached.
	CachePreflightDuration = 24 * time.Hour

	// GracefulShutdownTimeout is the maximum duration to wait for in-flight requests during shutdown.
	GracefulShutdownTimeout = 30 * time.Second
)

// setupDefaultTags seeds default tags for all workspaces.
func setupDefaultTags(d *db.Database) error {
	// Fetch all workspaces
	workspaces, fetchWorkspacesErr := d.GetAllWorkspaces()
	if fetchWorkspacesErr != nil {
		return fetchWorkspacesErr
	}

	// Seed default tags for every workspace
	for _, workspace := range workspaces {
		seedDefaultTagsErr := lib.SeedDefaultTags(d.DB, workspace.ID)
		if seedDefaultTagsErr != nil {
			return seedDefaultTagsErr
		}
	}

	return nil
}

func setupRolesAndPolicies(d *db.Database, overridePolicies *bool) error {
	// Seed initial roles
	if seedRolesErr := lib.SeedRoles(d); seedRolesErr != nil {
		return seedRolesErr
	}

	// Fetch all workspaces
	workspaces, fetchWorkspacesErr := d.GetAllWorkspaces()
	if fetchWorkspacesErr != nil {
		return fetchWorkspacesErr
	}

	// Set default policies for every workspace
	for _, workspace := range workspaces {
		setDefaultPoliciesErr := lib.SetDefaultPolicies(d.DB, workspace.ID, *overridePolicies)
		if setDefaultPoliciesErr != nil {
			return setDefaultPoliciesErr
		}
	}

	// Set default role for every user without a role
	if assignDefaultRolesErr := lib.AssignDefaultRolesToUsersWithoutRoles(d); assignDefaultRolesErr != nil {
		return assignDefaultRolesErr
	}

	return nil
}

// setupDatabase initializes and configures the database based on command line flags.
// The returned bool is true when a one-shot command (e.g. -gc) was run and the process should exit.
func setupDatabase(env *utils.CoreAPIEnv) (*db.Database, bool, error) {
	d, err := db.InitialiseDB(env)
	if err != nil {
		return nil, false, err
	}

	// Handle command line flags
	reset := flag.Bool("reset", false, "Reset the database")
	skipMigrate := flag.Bool("skip-migrate", false, "Skip automatic database migrations")
	overridePolicies := flag.Bool("override-policies", false, "Override existing policies")
	seedTags := flag.Bool("seed-tags", false, "Seed default tags for all workspaces")
	seedTemplates := flag.Bool("seed-templates", false, "Seed templates from embedded files")
	gcRun := flag.Bool("gc", false, "Run garbage collection operations")
	gcDryRun := flag.Bool("gc-dry-run", false, "Run garbage collection in dry-run mode (no deletions)")
	// Keep -migrate flag for backwards compatibility (now a no-op since migrations run by default)
	_ = flag.Bool("migrate", false, "Run database migrations (deprecated: migrations now run automatically)")
	flag.Parse()

	// Empty the database if the reset flag is set
	if *reset {
		if dbResetErr := d.Reset(); dbResetErr != nil {
			return nil, false, dbResetErr
		}
	}

	// Run database migrations on startup (unless explicitly skipped)
	// This ensures the database schema is always up-to-date for Railway, Docker, etc.
	if !*skipMigrate {
		log.Println("Running database migrations...")
		// Create database tables, add indexes, or update existing ones
		if dbMigrateErr := d.Migrate(); dbMigrateErr != nil {
			return nil, false, dbMigrateErr
		}

		// Setup roles and policies
		if setupRolesAndPoliciesErr := setupRolesAndPolicies(d, overridePolicies); setupRolesAndPoliciesErr != nil {
			return nil, false, setupRolesAndPoliciesErr
		}
		log.Println("Database migrations completed")
	} else {
		log.Println("Database migrations skipped (-skip-migrate flag set)")
	}

	// Seed default tags for all workspaces if the seedTags flag is set
	if *seedTags {
		if setupDefaultTagsErr := setupDefaultTags(d); setupDefaultTagsErr != nil {
			return nil, false, setupDefaultTagsErr
		}
	}

	// Seed templates if the seedTemplates flag is set
	if *seedTemplates {
		if seedTemplatesErr := templatefiles.SeedTemplates(d, slog.Default()); seedTemplatesErr != nil {
			return nil, false, seedTemplatesErr
		}
	}

	// Run garbage collection if either GC flag is set.
	// GC is a one-shot command — the process should exit after completion.
	if *gcRun || *gcDryRun {
		if gcErr := runGarbageCollection(d, env, *gcDryRun); gcErr != nil {
			return nil, false, gcErr
		}
		return d, true, nil
	}

	return d, false, nil
}

// runGarbageCollection creates a GC collector and executes it.
func runGarbageCollection(d *db.Database, env *utils.CoreAPIEnv, dryRun bool) error {
	lakefsClient, lakefsErr := lakefs.CreateClient(context.Background(), slog.Default(), env)
	if lakefsErr != nil {
		return lakefsErr
	}
	collector := gc.NewCollector(d, lakefsClient, slog.Default(), env)
	report := collector.Run(context.Background(), dryRun)
	if report.HasErrors() {
		return fmt.Errorf("garbage collection completed with %d errors", len(report.Errors)+len(report.LakeFSErrors))
	}
	return nil
}

// setupFiberApp creates and configures a new Fiber application.
func setupFiberApp(env *utils.CoreAPIEnv, appCacheMiddleware fiber.Handler) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName:   "Irmin API",
		BodyLimit: utils.MaxRequestBodySizeBytes(env),
		ErrorHandler: func(c fiber.Ctx, err error) error {
			slog.Error("Unhandled request error", "error", err, "path", c.Path(), "method", c.Method())
			return c.Status(fiber.StatusInternalServerError).SendString("Internal Server Error")
		},
	})

	// 1. Recover: Must be first. It needs to wrap every other handler
	// to catch any panics that might occur anywhere in the chain.
	app.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))

	// 2. CORS: Must be very early. It needs to handle preflight OPTIONS
	// requests immediately, before they hit other middleware like logging,
	// caching, or authentication.
	if env.CorsEnabled {
		app.Use(setupCORS(env))
	}

	// 3. Request ID: Assigns a unique ID to the request. This should be
	// early so that the logger and any subsequent tracing can use the ID.
	app.Use(func(c fiber.Ctx) error {
		// Check for existing request ID from upstream services/load balancers
		requestID := c.Get("X-Request-ID")
		if requestID == "" {
			// Generate a unique request ID if none exists
			requestID = uuid.New().String()
		}
		// Set the request ID in locals so it can be accessed by other handlers
		c.Locals("requestid", requestID)
		// Set the X-Request-ID header in the response
		c.Set("X-Request-ID", requestID)
		return c.Next()
	})

	// 4. Logger: Logs information about the request. It benefits from the
	// request ID being set and can log the final status of the request
	// after all other handlers have run.
	app.Use(logger.New(logger.Config{
		Format: "${pid} ${locals:requestid} ${status} - ${method} ${path}\n",
	}))

	// 5. Helmet: Adds security-related HTTP headers. It's a good general
	// security measure to have in place before processing the request further.
	if env.HelmetEnabled {
		app.Use(helmet.New())
	}

	// 6. Cache: This is a "gatekeeper". If a valid cached response exists
	// for a GET request, it will be served immediately, and no further
	// handlers (like idempotency or your main business logic) will be executed.
	// This provides a significant performance boost.
	app.Use(appCacheMiddleware)

	// 7. Idempotency: Another "gatekeeper", primarily for POST/PATCH requests.
	// It prevents duplicate operations. It should come after caching but before
	// your main application logic.
	if env.IdempotencyEnabled {
		app.Use(idempotency.New())
	}

	// 8. Compress: This is a "response modifier". It should be last.
	// It acts on the final response body generated by your route handlers
	// just before it's sent to the client. Placing it here ensures you don't
	// waste CPU cycles compressing something that might have been served
	// from cache.
	app.Use(compress.New(compress.Config{Level: compress.LevelBestSpeed}))

	return app
}

// setupCORS configures and returns the CORS middleware.
func setupCORS(env *utils.CoreAPIEnv) fiber.Handler {
	allowedOrigins := strings.Split(env.AllowedOrigins, ",")
	for i, origin := range allowedOrigins {
		allowedOrigins[i] = strings.TrimSpace(origin)
	}
	log.Println("Allowed origins:", allowedOrigins)

	return cors.New(cors.Config{
		AllowOrigins:     allowedOrigins,
		AllowCredentials: true,
		AllowHeaders: []string{
			"Origin",
			"Content-Type",
			"Accept",
			"Authorization",
			"X-Requested-With",
			"Accept-Language",
			"Referer",
			"Cache-Control",
		},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		MaxAge:       int(CachePreflightDuration.Seconds()),
	})
}

// setupServices initializes all required services.
func setupServices(
	ctx context.Context,
	env *utils.CoreAPIEnv,
	database *db.Database,
	cacheStorage fiber.Storage,
) (*orchestrator.Orchestrator, *irminsqids.SQIDManager, *locales.LocaleManager, *permissions.Service, *engine.Client, error) {
	// Initialize data engine
	dataEngine, err := engine.NewClient(ctx, "en", slog.Default(), env, database)
	if err != nil {
		return nil, nil, nil, nil, nil, err
	}

	// Initialize orchestrator
	orchestrator := orchestrator.NewOrchestrator(database, slog.Default(), env, dataEngine, cacheStorage)
	if env.OrchestratorEnabled {
		go func() {
			if orchestratorStartErr := orchestrator.StartOrchestrator(ctx); orchestratorStartErr != nil {
				log.Printf("Orchestrator error: %v", orchestratorStartErr)
			}
		}()
	}

	// Initialize SQID manager
	sqidManager := irminsqids.NewSQIDManager(env.SqidAlphabet)

	// Initialize locale manager
	localeManager, err := locales.New()
	if err != nil {
		return nil, nil, nil, nil, nil, err
	}

	// Initialize permission service
	permissionService := permissions.NewService(database, slog.Default())

	return orchestrator, sqidManager, localeManager, permissionService, dataEngine, nil
}

// startServer starts the Fiber server in a goroutine.
func startServer(app *fiber.App, env *utils.CoreAPIEnv) {
	go func() {
		if err := app.Listen(":" + env.Port); err != nil {
			log.Printf("Server error: %v", err)
		}
	}()
}

func main() {
	// Load environment variables
	env, err := utils.LoadEnv()
	if err != nil {
		log.Fatalf("failed to load environment variables: %v", err)
	}

	// Setup database (and run one-shot commands like -gc if requested).
	database, exitAfterSetup, err := setupDatabase(env)
	if err != nil {
		log.Fatalf("failed to setup database: %v", err)
	}
	if exitAfterSetup {
		return
	}

	// Initialize cache storage and middleware
	cacheStorage := cache.NewDefaultStorage()
	appCacheMiddleware := cache.NewAppCacheMiddleware(cacheStorage)

	// Setup Fiber app
	app := setupFiberApp(env, appCacheMiddleware)

	// Create a cancellable context for background services
	ctx, cancel := context.WithCancel(context.Background())

	// Setup services
	orchestrator, sqidManager, localeManager, permissionService, dataEngine, setupSvcErr := setupServices(
		ctx, env, database, cacheStorage,
	)
	if setupSvcErr != nil {
		cancel()
		log.Fatalf("failed to setup services: %v", setupSvcErr)
	}

	// Create API services
	apiServices := services.NewAPIServices(
		database,
		slog.Default(),
		env,
		orchestrator,
		sqidManager,
		localeManager,
		permissionService,
		cacheStorage,
		dataEngine.LakeFSClient,
	)

	// Wire orchestrator workflow run completion callback for billing usage tracking
	if apiServices.UsageTracker != nil {
		tracker := apiServices.UsageTracker
		orchestrator.OnWorkflowRunComplete = func(workspaceID uint) {
			tracker.Track(workspaceID, db.UsageDimensionWorkflowRuns, 1)
		}
	}

	// Wire orchestrator workflow run usage limit check for billing enforcement
	if apiServices.BillingService != nil {
		bs := apiServices.BillingService
		orchestrator.CheckWorkflowRunUsage = func(workspaceID uint) (bool, error) {
			return bs.CheckUsageLimit(workspaceID, db.UsageDimensionWorkflowRuns, 1)
		}
	}

	// Start usage tracker if billing is enabled
	if apiServices.UsageTracker != nil {
		go func() {
			if usageTrackerErr := apiServices.UsageTracker.Start(ctx); usageTrackerErr != nil {
				log.Printf("Usage tracker error: %v", usageTrackerErr)
			}
		}()
	}

	// Ensure Novu workflows exist (non-blocking, logs warnings on failure)
	lib.EnsureNovuWorkflows(env, slog.Default())

	// Register routes
	routes.RegisterAPIRoutes(
		app,
		apiServices,
	)

	// Mount MCP streamable HTTP handler inside the main app
	mcpserver.RegisterFiber(app, apiServices)

	// Mount AI Application MCP handler
	mcpserver.RegisterAIAppMCP(app, apiServices)

	// Start servers
	startServer(app, env)

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("Shutting down server...")

	// Shutdown Fiber first to drain in-flight requests before cancelling the
	// engine context. Cancelling ctx before shutdown would cause requests still
	// using engine.Client (LakeFS, data operations) to fail with context-cancelled.
	if shutdownErr := app.ShutdownWithTimeout(GracefulShutdownTimeout); shutdownErr != nil {
		log.Printf("Server forced to shutdown: %v", shutdownErr)
	}

	// Cancel the context to stop orchestrator and background services
	cancel()

	// Close database connection pool
	if sqlDB, dbErr := database.DB.DB(); dbErr == nil {
		if closeErr := sqlDB.Close(); closeErr != nil {
			log.Printf("Error closing database connection: %v", closeErr)
		}
	}

	log.Println("Server gracefully stopped")
}
