package lakefs

import (
	"fmt"
	"net/http"
)

// StagingLocation represents a location for placing an object when staging it
type StagingLocation struct {
	PhysicalAddress    string `json:"physical_address"`
	PresignedURL       string `json:"presigned_url"`        // if presign=true is passed in the request, this field will contain a pre-signed URL to use when uploading
	PresignedURLExpiry int64  `json:"presigned_url_expiry"` // If present and nonzero, physical_address is a pre-signed URL and will expire at this Unix Epoch time. This will be shorter than the pre-signed URL lifetime if an authentication token is about to expire.
}

// StagingMetadata represents the metadata about a staged object
type StagingMetadata struct {
	Staging      StagingLocation   `json:"staging"`
	Checksum     string            `json:"checksum"`      // unique identifier of object content on backing store (typically ETag)
	SizeBytes    int64             `json:"size_bytes"`    // size of object content in bytes
	UserMetadata map[string]string `json:"user_metadata"` // user-defined metadata
	ContentType  string            `json:"content_type"`  // MIME type of object content
	MTime        int64             `json:"mtime"`         // modification time of object content in Unix Epoch time
	Force        bool              `json:"force"`
}

// GenerateStagingLocation generates an address to which the client can upload an object to stage it
func (c *Client) GenerateStagingLocation(repositoryID, branchID, path string, presign bool) (*StagingLocation, error) {
	var stagingLocation StagingLocation
	endpoint := fmt.Sprintf("/repositories/%s/branches/%s/staging/backing?path=%s&presign=%t", repositoryID, branchID, path, presign)
	if err := c.doRequest("GET", endpoint, nil, []int{http.StatusOK}, &stagingLocation); err != nil {
		return nil, err
	}
	return &stagingLocation, nil
}

// AssociateStaging links the physical address with the path in lakeFS, creating an uncommitted change.
// The given address can be one generated by GenerateStagingLocation, or an address outside the repository's
// storage namespace.
func (c *Client) AssociateStaging(repositoryID, branchID, path string, reqData StagingMetadata) (*ObjectMetadata, error) {
	endpoint := fmt.Sprintf("/repositories/%s/branches/%s/staging/backing?path=%s", repositoryID, branchID, path)
	var objectMetadata ObjectMetadata
	if err := c.doRequest("POST", endpoint, reqData, []int{http.StatusOK}, &objectMetadata); err != nil {
		return nil, err
	}
	return &objectMetadata, nil
}
