package main

// @title Irmin Connectors
// @version 1.0.0
// @description Collection of connectors for Irmin to interact with external services
// @termsOfService http://irmin.co/terms

// @contact.name Irmin Team
// @contact.url https://irmin.co
// @contact.email hello@irmin.co

// @host connectors.irmin.co
// @BasePath
// @schemes https

// @securityDefinitions.apikey SystemTokenAuth
// @in header
// @name Authorization
// @description System token with Bearer prefix - used for connector registration and initialization endpoints

// @securityDefinitions.apikey OperationTokenAuth
// @in header
// @name Authorization
// @description Operation token with Bearer prefix - received from operation/init and used for data operation endpoints

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"irmin-connectors/connectors"
	"irmin-connectors/connectors/common"
	"irmin-connectors/db"
	"irmin-connectors/models"
	sentryutil "irmin-connectors/sentry"
	"irmin-connectors/swagger"
	"irmin-connectors/utils"
	"log"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/cache"
	"github.com/gofiber/fiber/v3/middleware/compress"
	"github.com/gofiber/fiber/v3/middleware/cors"
	"github.com/gofiber/fiber/v3/middleware/healthcheck"
	"github.com/gofiber/fiber/v3/middleware/helmet"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/recover"
	"github.com/gofiber/fiber/v3/middleware/static"
	"github.com/google/uuid"

	_ "irmin-connectors/docs" // This will be generated by swag
)

// Constants for the application.
const (
	// StartupTimeoutSeconds is the duration for which the startup is allowed to take.
	StartupTimeoutSeconds = 30

	// MaxStartupAttempts is the maximum number of attempts to start the server.
	MaxStartupAttempts = 600

	// StartupAttemptsInterval is the interval between startup attempts.
	StartupAttemptsInterval = 50 * time.Millisecond

	// ConnectionTimeout is the timeout for TCP connection attempts.
	ConnectionTimeout = 100 * time.Millisecond

	// CacheExpirationDuration is the duration for which responses are cached.
	CacheExpirationDuration = 10 * time.Second

	// MaxRequestBodySize is the maximum body size in bytes (5 GB).
	MaxRequestBodySize = 5 * 1024 * 1024 * 1024

	// ReadBufferSize is the size of the read buffer in bytes (10 MB).
	ReadBufferSize = 10 * 1024 * 1024

	// URLHealthCheckTimeout is the timeout for URL health check requests.
	URLHealthCheckTimeout = 5 * time.Second

	// MaxURLHealthCheckAttempts is the maximum number of attempts to check if the service URL is accessible.
	MaxURLHealthCheckAttempts = 60

	// URLHealthCheckInterval is the interval between URL health check attempts.
	URLHealthCheckInterval = 1 * time.Second
)

// setupDatabase initializes and configures the database.
func setupDatabase(ctx context.Context, runMigrations bool) (*db.Database, error) {
	if runMigrations {
		log.Println("Running database migrations...")
	}

	database, err := db.InitialiseDB(ctx, runMigrations)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize database: %w", err)
	}

	if runMigrations {
		log.Println("Database migrations completed")
	}

	return database, nil
}

// setupFiberApp creates and configures a new Fiber application.
func setupFiberApp(env *utils.ConnectorsEnv) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName:        "Irmin Connectors",
		BodyLimit:      MaxRequestBodySize,
		ReadBufferSize: ReadBufferSize, // 10MB for headers to handle large CORS headers
		ErrorHandler: func(c fiber.Ctx, err error) error {
			slog.Error("Unhandled request error", "error", err, "path", c.Path(), "method", c.Method())
			sentryutil.GetHubFromFiber(c).CaptureException(err)
			return c.Status(fiber.StatusInternalServerError).SendString("Internal Server Error")
		},
	})

	// 1. Recover: Must be first. It needs to wrap every other handler
	// to catch any panics that might occur anywhere in the chain.
	app.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))

	// 2. CORS: Must be very early. It needs to handle preflight OPTIONS
	// requests immediately, before they hit other middleware like logging,
	// caching, or authentication.
	// Apply public CORS for static files and connector details pages
	app.Use(setupPublicCORS())

	// Apply restricted CORS for API routes
	if env.CorsEnabled {
		app.Use(setupRestrictedCORS(env))
	}

	// 3. Request ID: Assigns a unique ID to the request. This should be
	// early so that the logger and any subsequent tracing can use the ID.
	app.Use(func(c fiber.Ctx) error {
		// Check for existing request ID from upstream services/load balancers
		requestID := c.Get("X-Request-ID")
		if requestID == "" {
			// Generate a unique request ID if none exists
			requestID = uuid.New().String()
		}
		// Set the request ID in locals so it can be accessed by other handlers
		c.Locals("requestid", requestID)
		// Set the X-Request-ID header in the response
		c.Set("X-Request-ID", requestID)
		return c.Next()
	})

	// 3.5. Sentry: Clones the Sentry hub per request for isolated error tracking
	// and starts a transaction span for performance monitoring.
	app.Use(sentryutil.FiberMiddleware())

	// 4. Logger: Logs information about the request. It benefits from the
	// request ID being set and can log the final status of the request
	// after all other handlers have run.
	app.Use(logger.New(logger.Config{
		Format: "${pid} ${locals:requestid} ${status} - ${method} ${path}\n",
	}))

	// 5. Helmet: Adds security-related HTTP headers. It's a good general
	// security measure to have in place before processing the request further.
	// Skip helmet for public routes to allow cross-origin resource loading (images, etc.)
	if env.HelmetEnabled {
		app.Use(helmet.New(helmet.Config{
			CrossOriginResourcePolicy: "cross-origin", // Allow images to be loaded from other origins
			Next: func(c fiber.Ctx) bool {
				// Skip helmet for public static files to ensure they can be loaded cross-origin
				return strings.HasPrefix(c.Path(), "/public/")
			},
		}))
	}

	// 6. Cache: This is a "gatekeeper". If a valid cached response exists
	// for a GET request, it will be served immediately, and no further
	// handlers (like your main business logic) will be executed.
	// This provides a significant performance boost.
	app.Use(setupCache())

	// 7. Compress: This is a "response modifier". It should be last.
	// It acts on the final response body generated by your route handlers
	// just before it's sent to the client. Placing it here ensures you don't
	// waste CPU cycles compressing something that might have been served
	// from cache.
	app.Use(compress.New(compress.Config{Level: compress.LevelBestSpeed}))

	return app
}

// setupCache configures and returns the cache middleware.
func setupCache() fiber.Handler {
	return cache.New(cache.Config{
		Expiration: CacheExpirationDuration,
		Next: func(c fiber.Ctx) bool {
			return shouldBypassAppCache(c.Path())
		},
		Methods: []string{
			http.MethodGet,
			http.MethodHead,
			http.MethodOptions,
		},
		KeyGenerator: func(c fiber.Ctx) string {
			queriesMap := c.Queries()
			var keys []string
			for key := range queriesMap {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			queries := ""
			for _, key := range keys {
				value := queriesMap[key]
				if queries == "" {
					queries = key + "=" + value
				} else {
					queries += "&" + key + "=" + value
				}
			}
			return c.Path() + queries + c.Get("authorization")
		},
	})
}

func shouldBypassAppCache(path string) bool {
	return strings.HasPrefix(path, "/operation/status/") ||
		strings.HasPrefix(path, "/operation/result/")
}

// setupPublicCORS configures and returns a permissive CORS middleware for public routes.
func setupPublicCORS() fiber.Handler {
	return cors.New(cors.Config{
		AllowOrigins:     []string{"*"}, // Allow all origins for public content
		AllowCredentials: false,         // No credentials needed for public content
		AllowHeaders: []string{
			"Origin",
			"Content-Type",
			"Accept",
			"X-Requested-With",
			"Accept-Language",
			"Referer",
			"Cache-Control",
		},
		AllowMethods: []string{"GET", "OPTIONS"},
		Next: func(c fiber.Ctx) bool {
			// Only apply to public routes
			path := c.Path()
			// Apply to static files in /public/
			if strings.HasPrefix(path, "/public/") {
				return false // Apply this CORS policy
			}
			// Apply to connector details pages (e.g., /http/details, /mysql/details, etc.)
			if strings.HasSuffix(path, "/details") {
				return false // Apply this CORS policy
			}
			return true // Skip this CORS policy for other routes
		},
	})
}

// setupRestrictedCORS configures and returns the restricted CORS middleware for API routes.
func setupRestrictedCORS(env *utils.ConnectorsEnv) fiber.Handler {
	allowedOrigins := strings.Split(env.CorsOrigins, ",")
	for i, origin := range allowedOrigins {
		allowedOrigins[i] = strings.TrimSpace(origin)
	}
	log.Println("Allowed origins for API routes:", allowedOrigins)

	return cors.New(cors.Config{
		AllowOrigins:     allowedOrigins,
		AllowCredentials: true,
		AllowHeaders: []string{
			"Origin",
			"Content-Type",
			"Accept",
			"Authorization",
			"X-Requested-With",
			"Accept-Language",
			"Referer",
			"Cache-Control",
		},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		Next: func(c fiber.Ctx) bool {
			// Skip restricted CORS for public routes (they use public CORS instead)
			path := c.Path()
			// Skip restricted CORS for static files in /public/
			if strings.HasPrefix(path, "/public/") {
				return true
			}
			// Skip restricted CORS for connector details pages
			if strings.HasSuffix(path, "/details") {
				return true
			}
			return false // Apply restricted CORS to API routes
		},
	})
}

// setupConnectorsApp creates a new application instance with all dependencies.
func setupConnectorsApp(env *utils.ConnectorsEnv, database *db.Database, app *fiber.App) *models.ConnectorsApp {
	logger := slog.Default()
	listenerManager := connectors.SetupListenerManager(logger, database)

	// Construct the async operation JobManager and kick off the
	// janitor goroutine. The janitor is idempotent so launching it
	// here rather than lazily on the first StartJob gives us a
	// deterministic startup order: expired jobs from a previous pod
	// lifetime get reaped on the first tick (~1m after startup).
	jobManager := common.NewJobManager(database, logger, common.JobManagerConfig{})
	jobManager.StartJanitor()

	return &models.ConnectorsApp{
		App:             app,
		DB:              database,
		Env:             env,
		Logger:          logger,
		ListenerManager: listenerManager,
		JobManager:      jobManager,
	}
}

// initializeConnectors registers all connectors and starts the listeners for all subscriptions.
func initializeConnectors(app *models.ConnectorsApp, skipRegistrations bool) error {
	if !skipRegistrations {
		if err := connectors.RegisterAllConnectors(context.Background(), app.DB, app.Logger, app.Env.APIBaseURL, app.Env.APIToken, app.Env.URL); err != nil {
			return err
		}
	}

	registrations, err := app.DB.GetAllConnectorRegistrations()
	if err != nil {
		return err
	}

	subscriptions, err := app.DB.GetAllSubscriptions()
	if err != nil {
		return err
	}

	// Start listeners for all existing subscriptions using the listener manager
	for _, subscription := range subscriptions {
		for _, reg := range registrations {
			if reg.ID == subscription.ConnectorRegistrationID {
				if listenerErr := app.ListenerManager.StartListener(reg.ConnectorName, subscription); listenerErr != nil {
					log.Printf(
						"error starting subscription listener for subscription %d: %v",
						subscription.ID,
						listenerErr,
					)
				}
				break
			}
		}
	}
	return nil
}

// waitForServerReady waits for the server to be ready by attempting to connect to it.
// Returns true if server is ready, false if context is cancelled or max attempts reached.
func waitForServerReady(ctx context.Context, port string, maxAttempts int) bool {
	address := ":" + port

	for range maxAttempts {
		select {
		case <-ctx.Done():
			return false
		default:
		}

		dialer := &net.Dialer{
			Timeout: ConnectionTimeout,
		}
		conn, err := dialer.DialContext(ctx, "tcp", address)
		if err == nil {
			if closeErr := conn.Close(); closeErr != nil {
				log.Printf("Warning: failed to close connection: %v", closeErr)
			}
			return true
		}

		// Wait a bit before retrying
		time.Sleep(StartupAttemptsInterval)
	}

	return false
}

// waitForServiceURLAccessible waits for the service to be accessible via its external URL.
// This is necessary because in containerized environments (like Railway), the internal DNS/routing
// may take time to propagate after the local port starts accepting connections.
// Returns true if service URL is accessible, false if context is cancelled or max attempts reached.
func waitForServiceURLAccessible(ctx context.Context, serviceURL string, maxAttempts int) bool {
	// Use a custom HTTP client with shorter timeouts and TLS config for internal URLs
	client := &http.Client{
		Timeout: URLHealthCheckTimeout,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				MinVersion: tls.VersionTLS12,
			},
			DisableKeepAlives: true,
		},
	}

	// Use the liveness endpoint for health checking
	healthURL := serviceURL + healthcheck.LivenessEndpoint

	var lastErr error
	for attempt := range maxAttempts {
		select {
		case <-ctx.Done():
			return false
		default:
		}

		req, err := http.NewRequestWithContext(ctx, http.MethodGet, healthURL, nil)
		if err != nil {
			log.Printf("Error creating health check request: %v", err)
			time.Sleep(URLHealthCheckInterval)
			continue
		}

		resp, err := client.Do(req)
		if err == nil {
			if closeErr := resp.Body.Close(); closeErr != nil {
				log.Printf("Warning: failed to close response body: %v", closeErr)
			}
			if resp.StatusCode == http.StatusOK {
				log.Printf("Service URL %s is accessible after %d attempts", serviceURL, attempt+1)
				return true
			}
			lastErr = fmt.Errorf("unexpected status code: %d", resp.StatusCode)
		} else {
			lastErr = err
		}

		if attempt%10 == 0 && attempt > 0 {
			log.Printf(
				"Waiting for service URL %s to become accessible (attempt %d/%d), last error: %v",
				serviceURL,
				attempt+1,
				maxAttempts,
				lastErr,
			)
		}

		time.Sleep(URLHealthCheckInterval)
	}

	log.Printf("Service URL health check failed after %d attempts. Last error: %v", maxAttempts, lastErr)
	return false
}

// startServer starts the Fiber server in a goroutine.
func startServer(app *fiber.App, env *utils.ConnectorsEnv) chan error {
	serverErr := make(chan error, 1)

	go func() {
		log.Printf("Server starting on port %s...", env.Port)

		// Try to start the server
		appListenErr := app.Listen(":" + env.Port)

		// If Listen returns, it's either due to an error or graceful shutdown
		serverErr <- appListenErr
	}()

	return serverErr
}

// setupGracefulShutdown sets up graceful shutdown handling.
func setupGracefulShutdown() chan os.Signal {
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	return quit
}

//nolint:gocognit // This function simply orchestrates the startup of the server and the connectors
func main() {
	// Define all flags in one place
	skipRegistrations := flag.Bool("skip-registrations", false, "Skip connector registrations")
	skipMigrate := flag.Bool("skip-migrate", false, "Skip automatic database migrations")
	// Keep -migrate flag for backwards compatibility (now a no-op since migrations run by default)
	_ = flag.Bool("migrate", false, "Run database migrations (deprecated: migrations now run automatically)")
	flag.Parse()

	// Load environment variables
	env, err := utils.LoadEnv()
	if err != nil {
		log.Fatalf("failed to load environment variables: %v", err)
	}

	// Initialize Sentry error tracking
	sentryutil.Init(slog.Default(), env)

	// Setup database (migrations run by default unless explicitly skipped)
	databaseContext := context.Background()
	database, err := setupDatabase(databaseContext, !*skipMigrate)
	if err != nil {
		sentryutil.CaptureError(err)
		sentryutil.Flush(sentryutil.FlushTimeout)
		log.Fatalf("failed to setup database: %v", err)
	}

	// Setup Fiber app
	app := setupFiberApp(env)

	// Simple index route
	app.Get("/", func(c fiber.Ctx) error {
		return c.SendString("Irmin Connectors")
	})

	// Health check routes
	app.Get(healthcheck.LivenessEndpoint, healthcheck.New(healthcheck.Config{}))
	app.Get(healthcheck.ReadinessEndpoint, healthcheck.New(healthcheck.Config{}))
	app.Get(healthcheck.StartupEndpoint, healthcheck.New(healthcheck.Config{}))

	// Swagger documentation endpoints
	app.Get("/swagger/swagger.json", swagger.JSON)
	app.Get("/swagger", swagger.UI)

	// Setup static file serving
	app.Get("/public/*", static.New("./public"))

	// Setup connectors app
	connectorsApp := setupConnectorsApp(env, database, app)

	// Register the API routes
	connectors.SetupConnectorRoutes(connectorsApp)

	// Register the top-level async-job HTTP endpoints (status /
	// result / cancel). These live outside the per-connector group
	// because the SDK client addresses them by job_id alone — the
	// connector slug is a server-side audit field on the
	// OperationJob row, not part of the URL.
	common.RegisterJobHandlers(app, connectorsApp)

	// Create context for startup timeout
	startupCtx, startupCancel := context.WithTimeout(context.Background(), StartupTimeoutSeconds*time.Second)

	// Start the server
	serverErr := startServer(app, env)

	// Setup graceful shutdown
	quit := setupGracefulShutdown()

	// Wait for server to be ready or fail
	serverReady := make(chan bool, 1)
	go func() {
		// Wait for server to actually accept connections
		ready := waitForServerReady(startupCtx, env.Port, MaxStartupAttempts)
		serverReady <- ready
	}()

	// Wait for startup completion or failure
	select {
	case appListenErr := <-serverErr:
		// Server returned an error (startup failure)
		startupCancel()
		log.Fatalf("Server failed to start: %v", appListenErr)
	case ready := <-serverReady:
		if !ready {
			startupCancel()
			log.Fatalf("Server failed to become ready within startup timeout")
		}

		// Server is confirmed ready - startup phase is complete
		startupCancel()
		log.Printf("Server successfully started and ready on port %s", env.Port)

		// Wait for the service to be accessible via its external URL before registering connectors
		// This is necessary because the Irmin API will call back to this service during registration
		if env.URL != "" && !*skipRegistrations {
			log.Printf("Verifying service is accessible via URL: %s (service running on port %s)", env.URL, env.Port)

			// Check for common Railway internal URL misconfiguration
			if strings.Contains(env.URL, ".railway.internal") && strings.HasPrefix(env.URL, "https://") {
				log.Printf(
					"WARNING: Railway internal URLs should use HTTP, not HTTPS. "+
						"Consider using http://<service>.railway.internal:%s instead of %s",
					env.Port,
					env.URL,
				)
			}

			urlCheckCtx, urlCheckCancel := context.WithTimeout(context.Background(), StartupTimeoutSeconds*time.Second)
			if !waitForServiceURLAccessible(urlCheckCtx, env.URL, MaxURLHealthCheckAttempts) {
				urlCheckCancel()
				log.Printf("Warning: Service URL %s is not accessible, connector registration may fail", env.URL)
			} else {
				urlCheckCancel()
			}
		}

		// Initialize connectors after server is ready and URL is accessible
		if initConnErr := initializeConnectors(connectorsApp, *skipRegistrations); initConnErr != nil {
			log.Printf("Error initializing connectors: %v", initConnErr)
			// Don't exit here, just log the error and continue
		}

		// Now wait for shutdown signal or runtime error
		select {
		case appListenErr := <-serverErr:
			// Server encountered a runtime error or was shut down
			if appListenErr != nil {
				sentryutil.CaptureError(appListenErr)
				log.Printf("Server error: %v", appListenErr)
			}
		case <-quit:
			log.Println("Shutting down server...")

			// Stop all active listeners first
			log.Println("Stopping all subscription listeners...")
			connectorsApp.ListenerManager.StopAll()

			// Shutdown with timeout
			if appShutdownErr := app.Shutdown(); appShutdownErr != nil {
				log.Printf("Server forced to shutdown: %v", appShutdownErr)
			}

			log.Println("Server gracefully stopped")
		}

		// Flush buffered Sentry events before exiting
		sentryutil.Flush(sentryutil.FlushTimeout)
	}
}
