version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "timborovkov"
    groups:
      all:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    target-branch: "main"

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      include: "scope"
    reviewers:
      - "timborovkov"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    target-branch: "main"
