/**
 * English dictionary, key-value pairs for static strings in the application
 */
const en = {
  static: {
    wordpressHomePageSlug: 'home',
    wordpressMainMenuSlug: 'primary-menu-en',
    wordpressFooterMenuSlug: 'footer-menu-en',
  },
  website: {
    navigation: {
      goToConsole: 'Console',
      getStarted: 'Get started',
      signIn: 'Sign in',
    },
    footer: {
      description:
        'A better home for your data. Irmin is an ETL and data management platform that helps you to collect, clean, and transform your data.',
      newsletter: {
        title: 'Subscribe to our newsletter',
        subtitle:
          'Stay up to date with the latest news and updates from Irmin.',
        email: 'Email',
        subscribe: 'Subscribe',
      },
      terms: 'Terms and conditions',
      privacy: 'Privacy policy',
      allRightsReserved: 'All rights reserved.',
    },
    sections: {
      careers: {
        viewJob: 'View job',
        search: 'Search',
        allLocations: 'All locations',
        allTypes: 'All types',
      },
      contact: {
        email: 'Email',
        message: 'Message',
        messagePlaceholder: 'Write your message here...',
        send: 'Send',
      },
      newsletter: {
        email: 'Enter your email',
        subscribe: 'Subscribe',
        privacy_notice: 'We care for your data. Read our',
        privacy: 'Privacy policy',
      },
      pricing: {
        billedMonthly: 'Billed monthly',
        billedAnnually: 'Billed annually',
        month: 'mo',
        year: 'yr',
      },
      articles: {
        allArticles: 'All articles',
        search: 'Search',
      },
    },
  },
  theme: {
    toggleTheme: 'Toggle theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
  },
  misc: {
    selectLanguage: 'Select language',
    loading: 'Loading...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    error: 'Error',
    ohNo: 'Oh no!',
    pageNotFound: 'Page not found',
    articleNotFound: 'Article not found',
    somethingWentWrong: 'Something went wrong',
    weEncounteredError: 'We encountered an error',
    tryAgainOrContactSupport: 'Please try again or contact support',
    goBackHome: 'Go back to the home page',
    goBackConsole: 'Go back to Irmin Console',
    back: 'Back',
    remove: 'Remove',
    tryAgain: 'Try again',
    success: 'Success',
    info: 'Info',
    noOptionsMessage: 'No options',
    yes: 'Yes',
    no: 'No',
    fieldRequired: 'This field is required',
    fieldInvalid: 'This field is invalid',
    refresh: 'Refresh',
    dangerZone: 'Danger zone',
    confirmDeletion: 'Confirm deletion',
    resetForm: 'Clear form',
    pleaseFixErrors: 'Please fix the errors above',
    select: 'Select',
    selected: 'Selected',
    lastModified: 'Last modified',
    size: 'Size',
    close: 'Close',
    timestamp: 'Timestamp',
    areYouSureYouWantToDelete: 'Are you sure you want to delete this item?',
    areYouSureYouWantToReassign:
      'Are you sure you want to reassign the ownership of this item?',
    download: {
      download: 'Download',
      downloading: 'Downloading',
      success: 'Your download has been successful!',
      failed: 'Your download has failed!',
    },
    name: 'Name',
    description: 'Description',
    save: 'Save',
  },
  consoleNavigation: {
    search: 'Search',
    searchPlaceholder: 'Search for data and more',
    searchNoResults: 'No results found',
    searchItemType: {
      workflows: 'Workflows',
      connections: 'Connections',
      repositories: 'Repositories',
      users: 'Users',
      workspaces: 'Workspaces',
      irmin: 'Irmin',
    },
    staticSearchItems: {
      irminWebsite: 'Irmin Website',
      contactUs: 'Contact Us',
      guides: 'Irmin Guides',
      documentation: 'Irmin Documentation',
      termsAndPrivacy: 'Terms of Use & Privacy Policy',
      createWorkspace: 'Create new workspace',
      logs: 'Workspace Logs',
      workspaceDocumentation: 'Workspace Documentation',
      myProfile: 'My Profile',
      manageWorkspaces: 'Manage Workspaces',
      editor: 'Editor',
      workspaceSettings: 'Workspace settings',
      workflows: 'All Workflows',
      actions: 'Actions workflows',
      imports: 'Import workflows',
      exports: 'Export workflows',
      createWorkflow: 'Create new workflow',
      connections: 'Connections',
      createConnection: 'Create new connection',
      repositories: 'Repositories',
      createRepository: 'Create new repository',
      description: {
        irminWebsite: 'Go to the Irmin website',
        contactUs: 'Contact our team',
        guides: 'Read the Irmin guides',
        documentation: 'Read the Irmin documentation',
        termsAndPrivacy: 'Read the terms and privacy policy',
        createWorkspace: 'Create a new workspace on Irmin',
        logs: 'View logs of your current workspace',
        workspaceDocumentation: 'View workspace documentation',
        myProfile: 'View and edit your profile',
        manageWorkspaces: 'Manage your workspaces',
        editor: 'Write and run scripts',
        workspaceSettings: 'Edit workspace settings',
        workflows: 'View and manage workflows',
        actions: 'View and manage action workflows',
        imports: 'View and manage import workflows',
        exports: 'View and manage export workflows',
        createWorkflow: 'Create a new workflow of any type',
        connections: 'View and manage connections',
        createConnection: 'Create a new connection to use in your workflows',
        repositories: 'View and manage repositories',
        createRepository: 'Create a new repository to store your data',
      },
    },
    irminConsole: 'Irmin Console',
    workspace: 'Workspace',
    settings: 'Settings',
    usefulLinks: 'Useful links',
    links: {
      home: 'Workspace',
      repositories: 'Repositories',
      editor: 'Editor',
      queries: 'Queries',
      connections: 'Connections',
      workflows: 'Workflows',
      actions: 'Actions',
      imports: 'Imports',
      exports: 'Exports',
      pipelines: 'Pipelines',
      logs: 'Logs',
      documentation: 'Documentation',
      workspaceSettings: 'Workspace',
      workspaces: 'Workspaces',
      goToWebsite: 'Go to website',
      myProfile: 'My Profile',
      signOut: 'Sign out',
      guides: 'Guides',
      contactSupport: 'Contact our team',
      developerDocs: 'Developer Docs',
      irminWebsite: 'Irmin Website',
      privacyPolicy: 'Privacy Policy',
      termsOfUse: 'Terms of Use',
      termsAndPrivacy: 'Terms & Privacy',
    },
  },
  consoleHome: {
    welcomeToWorkspace: 'Get started on Irmin with these quick actions:',
    createNewConnection: 'Create new connection',
    createNewConnectionDescription:
      'Connect a new data source or export destination for your workspace',
    runScriptOnData: 'Run script on data',
    runScriptOnDataDescription:
      'Write and run scripts on your data to automate tasks or find insights',
    setupWorkflow: 'Setup a workflow',
    setupWorkflowDescription:
      'Automate data tasks with workflows. Data ingestion, transformation, and export',
    browseRepositories: 'Data and repositories',
    browseRepositoriesDescription:
      'Browse, query, and manage your data, in a Git-like environment',
  },
  workspaceSwitcher: {
    manageWorkspaces: 'Manage Workspaces',
    selectWorkspace: 'Select a workspace',
    createNewWorkspace: 'Create new workspace',
    selectExisting: 'Select existing workspace',
    switchedTo: 'Switched to',
    failedToSwitch: 'Failed to switch workspace',
    workspace: 'Workspace',
    leaveWorkspace: 'Leave workspace',
    leaveWorkspaceConfirm: 'Are you sure you want to leave this workspace?',
  },
  repository: {
    repository: 'Repository',
    allRepositories: 'All repositories',
    rowsReturnedIn: 'rows returned in',
    sqlQuery: 'SQL Query',
    runQuery: 'Run query',
    immutableDescription: 'This repository is immutable and cannot be edited.',
    createNewRepository: 'Create new repository',
    workflow: 'Workflow',
    viewWorkflow: 'View workflow',
    immutableWarning: 'Immutable repository or branch',
    immutableWarningDescription:
      'Current repository or selected branch are immutable and cannot be edited.',
    branches: {
      currentBranch: 'Current',
      branch: 'Branch',
      createBranch: 'Create branch',
      primary: 'Primary',
      newBranchName: 'New branch name',
      fromBranch: 'From branch',
      confirmDeleteBranch: 'Are you sure you want to delete this branch?',
    },
    tags: {
      tag: 'Tag',
      tagDescription: 'A tag is an immutable pointer to a single commit.',
      createTag: 'Create tag',
      newTagName: 'New tag name',
      fromCommit: 'From commit',
      confirmDeleteTag: 'Are you sure you want to delete this tag?',
      currentlyViewing: 'Currently viewing',
    },
    commit: {
      commitHash: 'Commit hash',
      copyHash: 'Copy hash',
      commitHashCopied: 'Commit hash copied to clipboard',
      uncommitedChanges: 'Uncommited changes',
      showingUncommitedChangesFor: 'Showing uncommited changes for',
      commitChanges: 'Commit changes',
      revertChanges: 'Revert changes',
      confirmRevertChanges:
        'Are you sure you want to revert all uncommitted changes?',
      noUncommitedChanges: 'There are no uncommited changes',
      noUncommitedChangesDescription:
        'To compare changes, you need to have uncommited changes in the current branch',
      commitNewChangesTo: 'Commit new changes to',
      commitMessage: 'Commit message',
      commitMessagePlaceholder: 'Describe your changes',
    },
    compare: {
      switchDirection: 'Switch direction',
      baseBranch: 'Base branch',
      compareBranch: 'Compare to branch',
      merge: 'Merge',
      into: 'into',
      comparing: 'Comparing',
      and: 'and',
      bytes: 'bytes',
      modified: 'modified',
      moved: 'moved',
      conflict: 'conflict',
      hideChanges: 'Hide changes',
      fetchChanges: 'Fetch changes',
      thereIsNothingToCompare: 'There is nothing to compare or merge',
      thereIsNothingToCompareSubtitle:
        'You need to use two different sources to get a valid comparison.',
      unsupportedContentType: 'Unsupported content type',
      download: 'Download',
      baseContent: 'Base content',
      comparedContent: 'Compared content',
      mergeStrategy: 'Merge strategy',
      mergeCommitDescription: 'Merge commit description',
      defaultStrategy: 'Default',
      destWinsStrategy: 'Destination wins',
      sourceWinsStrategy: 'Source wins',
      mergeExplanation:
        'In case of a merge conflict, this option will force the merge process to automatically favor changes from the base (“Destination wins”) or from the comparison (“Source wins"). In case no selection is made, the merge process will fail in case of a conflict.',
    },
    objects: {
      uploadObject: 'Upload object',
      noObjects: 'No objects found',
      deleteConfirm: 'Are you sure you want to delete this object?',
      lastModification: 'Last modification',
      path: 'Path',
      currentPath: 'Current path',
      currentName: 'Current name',
      type: 'Type',
      contentType: 'Content-Type',
      description: 'Description',
      size: 'Size',
      lastModified: 'Last modified',
      view: 'View',
      viewSchema: 'View schema',
      download: 'Download',
      filterObjects: 'Filter objects',
      createGroup: 'Create folder',
      uploadAndReplace: 'Upload and replace',
      moveOrRename: 'Move or rename',
      targetRepository: 'Target repository',
      targetBranch: 'Target branch',
      objectName: 'Object name',
      fileToUpload: 'File to upload',
      pathInRepository: 'Path in the repository',
      noFilesSelected: 'Select files to upload before submitting',
    },
    settings: {
      generalSettings: 'General settings',
      owner: 'Owner',
      saveChanges: 'Save changes',
      deletionNote:
        'Deleting this repository will remove all data associated with it. This action is irreversible.',
      deleteRepository: 'Delete repository',
      areYouSureYouWantToDelete:
        'Are you sure you want to delete this repository?',
    },
    tabs: {
      structure: 'Structure',
      dataViewer: 'Data',
      tags: 'Tags',
      commits: 'Commits',
      branches: 'Branches',
      compare: 'Compare',
      documentation: 'Documentation',
      settings: 'Settings',
    },
    schema: {
      schema: 'Schema',
      noSchema: 'No schema available',
      table: 'Table',
      column: 'Column',
      type: 'Type',
      timestamp: 'Timestamp',
      constraints: 'Constraints',
      folder: 'Folder',
      file: 'File',
      size: 'Size',
      created_at: 'Created at',
      modified_at: 'Modified at',
    },
  },
  connections: {
    allConnections: 'All connections',
    connection: 'Connection',
    tabs: {
      overview: 'Overview',
      documentation: 'Documentation',
      settings: 'Settings',
    },
    settings: {
      title: 'Connection settings',
      connector: 'Connector',
      saveChanges: 'Save changes',
      owner: 'Owner',
      deletionNote:
        'Deleting this connection will remove all data associated with it. This action is irreversible.',
      delete: 'Delete connection',
      areYouSureYouWantToDelete:
        'Are you sure you want to delete this connection?',
    },
    create: {
      selectConnector: 'Select a connector',
      establishConnection: 'Establish connection',
      configureSettings: 'Configure settings',
      configureConnection: 'Configure connection',
      createNewConnection: 'Create new connection',
      pleaseSelectConnector: 'Please select a connector to continue.',
      confirmConnectorSelection: 'Confirm connector selection and continue',
      selectedConnector: 'Selected connector',
      learnMore: 'Learn more',
      categoryAll: 'All',
      select: 'Select',
      connector: 'Connector',
      connectionName: 'Connection name',
      connectionNamePlaceholder: 'eg. My Google Analytics connection',
      connectionDescription: 'Connection description',
      connectionDescriptionPlaceholder:
        'Enter a description for the connection, so you can remember what it is used for',
      addCustomConnector: 'Add custom connector',
      continueAndTest: 'Continue & test connection',
      createConnection: 'Create connection',
      continue: 'Continue',
      goBack: 'Go back',
      success: 'Connection successful',
      failed: 'Connection failed',
      configuration_valid: 'Connection configuration valid',
      configuration_invalid: 'Connection configuration invalid',
      contactSupport: 'Contact support',
      requiredFieldsMissing: 'Error! Required fields are missing',
    },
    connector: {
      version: 'Version',
      structureVersion: 'Irmin Structure Version',
      author: 'Author',
      authorEmail: 'Author email',
      categories: 'Categories',
      capabilities: 'Capabilities',
      locales: 'Locales',
      readMore: 'Read more',
    },
  },
  workflow: {
    allWorkflows: 'All Workflows',
    importWorkflows: 'Import workflows',
    actionWorkflows: 'Action workflows',
    exportWorkflows: 'Export workflows',
    pipelineWorkflows: 'Pipeline workflows',
    triggerRun: 'Trigger workflow run',
    triggeringRun: 'Triggering run',
    workflow: 'Workflow',
    import: 'Import',
    action: 'Action',
    export: 'Export',
    run: 'run',
    startedAt: 'Started at',
    finishedAt: 'Finished at',
    scheduled: 'Scheduled',
    notScheduled: 'Not scheduled',
    owner: 'Owner',
    openInEditor: 'Open in editor',
    executableScriptFile: 'Executable script file',
    scriptResultDestinationRepository: 'Result to repository',
    scriptResultDestinationBranch: 'Result to branch',
    scriptResultDestinationPath: 'Result to path',
    importSourceConnection: 'Import from connection',
    importDestinationRepository: 'Import to repository',
    importDestinationBranch: 'Import to branch',
    importDestinationPath: 'Import to path',
    exportDestinationConnection: 'Export to connection',
    exportSourceRepository: 'Export from repository',
    exportSourceBranch: 'Export from branch',
    exportSourcePath: 'Export from path',
    exportRecursive: 'Recursive export',
    livePipeline: 'Live pipeline',
    tabs: {
      overview: 'Overview',
      documentation: 'Documentation',
      data: 'Data',
      logs: 'Logs',
      schedule: 'Schedule',
      settings: 'Settings',
    },
    settings: {
      saveChanges: 'Save changes',
      deletionNote:
        'Deleting this workflow will remove all data associated with it. This action is irreversible.',
      delete: 'Delete workflow',
      areYouSureYouWantToDelete:
        'Are you sure you want to delete this workflow?',
      resumeWorkflow: 'Resume',
      pauseWorkflow: 'Pause',
    },
    create: {
      createNewWorkflow: 'Create new workflow',
      createNewActionWorkflow: 'Create new action workflow',
      createNewImportWorkflow: 'Create new import workflow',
      createNewExportWorkflow: 'Create new export workflow',
      createNewPipelineWorkflow: 'Create new pipeline workflow',
      configureImport: 'Configure import',
      configureAction: 'Configure action',
      configureExport: 'Configure export',
      configurePipeline: 'Configure pipeline',
      configureWorkflow: 'Configure workflow',
      confirmAndCreate: 'Confirm and create',
      confirmAndContinue: 'Confirm and continue',
      goBack: 'Go back',
    },
    pipeline: {
      pipeline: 'Pipeline',
      livePipeline: 'Live pipeline',
      addNewStage: 'Add new stage',
      addStage: 'Add stage',
      stage: 'Stage',
      descriptionPlaceholder: 'Describe what this pipeline stage does',
      write: 'Write',
      read: 'Read',
      executablePath: 'Executable path',
      executablePathDescription:
        'Path to the action script e.g. /path/to/script.py',
      connectionWritePath: 'Write Path',
      connectionWritePathDescription:
        'Path to write within the connection e.g. /path/to/write',
      connectionReadPath: 'Read Path',
      connectionReadPathDescription:
        'Path to read within the connection e.g. /path/to/read',
      moveUp: 'Move up',
      moveDown: 'Move down',
      removeStage: 'Remove stage',
      savePipelineStages: 'Save pipeline stages',
      noStages: 'No stages',
    },
    schedule: {
      workflowSchedule: 'Workflow schedule',
      frequency: 'Frequency',
      interval: 'Interval',
      weekdays: 'Weekdays',
      trigger: 'Trigger',
      triggers: 'Triggers',
      timeTrigger: 'Time based trigger',
      repositoryEventTrigger: 'Repository event trigger',
      workflowRunEventTrigger: 'Workflow run event trigger',
      addTrigger: 'Add trigger',
      maxRetries: 'Max Retries',
      maxRuntime: 'Max Runtime (seconds)',
      minInterval: 'Min Interval (seconds)',
      triggerType: 'Trigger Type',
      recurrenceRule: 'Recurrence Rule',
      event: 'Event',
      saveSchedule: 'Save Schedule',
    },
  },
  editor: {
    writeYourSQL: 'Write your SQL query here...',
    writeYourJS: 'Write your JavaScript script here...',
    writeYourGo: 'Write your Go script here...',
    writeYourMarkdown: 'Write your Markdown here...',
    newScriptTitle: 'Create a new script',
    newScriptSubtitle:
      'Start writing your script in your preferred language and save it as a workflow',
  },
  query: {
    results: 'Results',
    errors: 'Errors',
    logs: 'Logs',
    noErrors: 'No errors',
    queryResults: 'Query results',
    createQuery: 'Create query',
    save: 'Save',
    saveAsWorkflow: 'Save as workflow',
    run: 'Run',
    rowsReturnedIn: 'rows returned in',
    exportTable: 'export table (.csv)',
    noResults: 'No results',
    search: 'Search in results',
    newQuery: 'New query',
    selectedQuery: 'Selected query',
  },
  list: {
    status: 'Status',
    runs: 'Runs',
    connector: 'Connector',
    actions: 'Actions',
    view: 'View',
    logs: 'Logs',
    delete: 'Delete',
    edit: 'Edit',
    owner: 'Owner',
    author: 'Author',
    lastUpdated: 'Last updated',
    createdAt: 'Created at',
    immutable: 'Immutable',
    source: 'Source',
    destination: 'Destination',
    searchPlaceholder: 'Type to search...',
    noItemsFound: 'No items found',
  },
  fileNavigator: {
    original: 'Original',
    saveFile: 'Save file',
    createFile: 'Create file',
    createFolder: 'Create folder',
    updateFile: 'Update file',
    updateFolder: 'Update folder',
    open: 'Open',
    delete: 'Delete',
    rename: 'Rename',
    move: 'Move',
    root: 'Root',
    rootDirectory: 'Root directory',
    newNameOfTheFile: 'New name of the file',
    newNameOfTheFolder: 'New name of the folder',
    newPathOfTheFile: 'New path of the file',
    newPathOfTheFolder: 'New path of the folder',
    newFileName: 'New file name',
    newFolderName: 'New folder name',
    newFilePath: 'New file path',
    newFolderPath: 'New folder path',
    deleteConfirmation: 'Are you sure you want to delete',
    deleteFolderWarning: 'All files and folders inside will be deleted',
    errors: {
      invalidType: 'Invalid item type (file or folder)',
      noExtension: 'No extension provided',
      invalidExtension: 'Invalid file extension (js, py, sql)',
      emptyName: 'Name is empty',
      longName: 'Name is too long',
      invalidName: 'Invalid name',
      invalidPath: 'Invalid path',
      pathExists: 'Path already exists',
      parentPathNotExist: 'Parent path does not exist',
    },
  },
  documentation: {
    documentation: 'Documentation',
    switchToPlainText: 'Plain text',
    switchToVisualEditor: 'Visual editor',
    startTypingDocumentation:
      'Start typing your documentation and notes here...',
    schema: 'Schema',
    downloadPDF: 'Download PDF',
    timestamp: 'Timestamp',
    workspace: 'Workspace',
    createdBy: 'Created by',
    sections: {
      repositories: 'Repositories',
      connections: 'Connections',
      importWorkflows: 'Import workflows',
      actionWorkflows: 'Action workflows',
      exportWorkflows: 'Export workflows',
    },
  },
  users: {
    removeUserConfirmation: 'Are you sure you want to remove this user?',
    transferOwnershipConfirmation:
      'Are you sure you want to transfer ownership?',
    usersAndPermissions: 'Users & Permissions',
    invites: 'Invites to the workspace',
    inviteUser: 'Invite a User',
    changeProfilePicture: 'Change profile picture',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    company: 'Company',
    role: 'Role',
    owner: 'Owner',
    noRole: 'No role',
    updateProfile: 'Update profile',
    transferOwnership: 'Transfer ownership',
    removeFromWorkspace: 'Remove from workspace',
    resendInvite: 'Resend invite',
    cancelInvite: 'Cancel invite',
    invite: 'Invite',
    cancel: 'Cancel',
  },
  invite: {
    loginToAccept: 'Login to Accept Invitation',
    setPassword: 'Set a Password',
    enterNewPassword: 'Enter a new password',
    confirmPassword: 'Confirm Password',
    reenterPassword: 'Re-enter your password',
    declineInvitation: 'Decline invitation',
    acceptAndCreateAccount: 'Accept & Create Account',
    acceptInvitation: 'Accept Invitation',
    workspaceInvitation: 'Workspace Invitation',
    workspaceInvitationDescription: 'You have been invited to join a workspace',
    invitedBy: 'Invited by',
    workspace: 'Workspace',
    yourEmail: 'Your email',
    yourPhone: 'Your phone',
    yourCompany: 'Your company',
  },
  workspace: {
    general: 'General',
    users: 'Users',
    invites: 'Invites',
    billing: 'Billing',
    confirmDeletion: 'Confirm Deletion',
    deletionWarning:
      'Are you sure you want to delete this workspace? This action cannot be undone and will remove all data associated with this workspace.',
    cancel: 'Cancel',
    delete: 'Delete',
    generalSettings: 'General Settings',
    workspaceName: 'Workspace Name',
    workspaceDescription: 'Workspace Description',
    saveChanges: 'Save Changes',
    deletionNote:
      'Deleting your workspace will remove all data associated with it. This action is irreversible.',
    deleteWorkspace: 'Delete Workspace',
    billingSettings: 'Billing Settings',
    billingNote:
      'You can currently only manage billing by contacting our team.',
    contactUs: 'Contact Us',
  },
  logs: {
    workspaceLogs: 'Workspace logs',
    workflowLogs: 'Workflow logs',
    repositoryLogs: 'Repository logs',
    connectionLogs: 'Connection logs',
    workflowRunLogs: 'Workflow run logs',
    noLogsFound: 'No logs found',
    system: 'System',
  },
};
export default en;
