/**
 * English dictionary, key-value pairs for static strings in the application
 */
const en = {
  common: {
    selectLanguage: 'Select language',
    loading: 'Loading...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    error: 'Error',
    ohNo: 'Oh no!',
    pageNotFound: 'Page not found',
    somethingWentWrong: 'Something went wrong',
    weEncounteredError: 'We encountered an error',
    tryAgainOrContactSupport: 'Please try again or contact support',
    goBackHome: 'Go back to the home page',
    goBackConsole: 'Go back to Irmin Console',
    back: 'Back',
    remove: 'Remove',
    tryAgain: 'Try again',
    success: 'Success',
    info: 'Info',
    noOptionsMessage: 'No options',
    yes: 'Yes',
    no: 'No',
    fieldRequired: 'This field is required',
    fieldInvalid: 'This field is invalid',
    refresh: 'Refresh',
    dangerZone: 'Danger zone',
    resetForm: 'Clear form',
    pleaseFixErrors: 'Please fix the errors above',
    lastModified: 'Last modified',
    size: 'Size',
    close: 'Close',
    timestamp: 'Timestamp',
    areYouSureYouWantToDelete: 'Are you sure you want to delete this item?',
    areYouSureYouWantToTransferOwnership:
      'Are you sure you want to transfer the ownership of this item?',
    name: 'Name',
    description: 'Description',
    save: 'Save',
    search: 'Search',
    noResults: 'No results',
    contactUs: 'Contact Us',
    readMore: 'Read more',
    overview: 'Overview',
    email: 'Email',
    message: 'Message',
    messagePlaceholder: 'Write your message here...',
    pleaseWait: 'Please wait...',
    actions: {
      send: 'Send',
      subscribe: 'Subscribe',
      download: 'Download',
    },
    terms: {
      termsAndConditions: 'Terms and conditions',
      privacyPolicy: 'Privacy policy',
    },
  },
  theme: {
    toggle: 'Toggle theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
  },
  consoleNavigation: {
    searchPlaceholder: 'Search for data and more',
    staticSearchItems: {
      guides: 'Irmin Guides',
      documentation: 'Irmin Documentation',
      termsAndPrivacy: 'Terms of Use & Privacy Policy',
      createWorkspace: 'Create new workspace',
      logs: 'Workspace Logs',
      workspaceDocumentation: 'Workspace Documentation',
      myProfile: 'My Profile',
      manageWorkspaces: 'Manage Workspaces',
      editor: 'Editor',
      workspaceSettings: 'Workspace settings',
      createWorkflow: 'Create new workflow',
      createConnection: 'Create new connection',
      createRepository: 'Create new repository',
      description: {
        irminWebsite: 'Go to the Irmin website',
        contactUs: 'Contact our team',
        guides: 'Read the Irmin guides',
        documentation: 'Read the Irmin documentation',
        termsAndPrivacy: 'Read the terms and privacy policy',
        createWorkspace: 'Create a new workspace on Irmin',
        logs: 'View logs of your current workspace',
        workspaceDocumentation: 'View workspace documentation',
        myProfile: 'View and edit your profile',
        manageWorkspaces: 'Manage your workspaces',
        editor: 'Write and run scripts',
        workspaceSettings: 'Edit workspace settings',
        workflows: 'View and manage workflows',
        actions: 'View and manage action workflows',
        imports: 'View and manage import workflows',
        exports: 'View and manage export workflows',
        pipelines: 'View and manage pipeline workflows',
        createWorkflow: 'Create a new workflow of any type',
        connections: 'View and manage connections',
        createConnection: 'Create a new connection to use in your workflows',
        repositories: 'View and manage repositories',
        createRepository: 'Create a new repository to store your data',
      },
    },
    irmin: 'Irmin',
    irminConsole: 'Irmin Console',
    irminWebsite: 'Irmin Website',
    workspace: 'Workspace',
    settings: 'Settings',
    usefulLinks: 'Useful links',
    editor: 'Editor',
    queries: 'Queries',
    logs: 'Logs',
    workspaceSettings: 'Workspace',
    workspaces: 'Workspaces',
    goToWebsite: 'Go to website',
    myProfile: 'My Profile',
    signOut: 'Sign out',
    guides: 'Guides',
    contactSupport: 'Contact our team',
    developerDocs: 'Developer Docs',
    termsAndPrivacy: 'Terms & Privacy',
  },
  consoleHome: {
    welcomeToWorkspace: 'Get started on Irmin with these quick actions:',
    createNewConnection: 'Create new connection',
    createNewConnectionDescription:
      'Connect a new data source or export destination for your workspace',
    runScriptOnData: 'Run script on data',
    runScriptOnDataDescription:
      'Write and run scripts on your data to automate tasks or find insights',
    setupWorkflow: 'Setup a workflow',
    setupWorkflowDescription:
      'Automate data tasks with workflows. Data ingestion, transformation, and export',
    browseRepositories: 'Data and repositories',
    browseRepositoriesDescription:
      'Browse, query, and manage your data, in a Git-like environment',
  },
  workspaceSwitcher: {
    manageWorkspaces: 'Manage Workspaces',
    selectWorkspace: 'Select a workspace',
    createNewWorkspace: 'Create new workspace',
    workspace: 'Workspace',
    leaveWorkspace: 'Leave workspace',
    leaveWorkspaceConfirm: 'Are you sure you want to leave this workspace?',
  },
  repository: {
    repository: 'Repository',
    repositories: 'Repositories',
    sqlQuery: 'SQL Query',
    runQuery: 'Run query',
    createNewRepository: 'Create new repository',
    immutableWarning: 'Immutable repository or branch',
    immutableWarningDescription:
      'Current repository or selected branch are immutable and cannot be edited.',
    branches: {
      branches: 'Branches',
      currentBranch: 'Current',
      branch: 'Branch',
      createBranch: 'Create branch',
      primary: 'Primary',
      primaryBranch: 'Primary branch',
      newBranchName: 'New branch name',
      fromBranch: 'From branch',
      confirmDeleteBranch: 'Are you sure you want to delete this branch?',
    },
    tags: {
      tag: 'Tag',
      tags: 'Tags',
      tagDescription: 'A tag is an immutable pointer to a single commit.',
      createTag: 'Create tag',
      newTagName: 'New tag name',
      fromCommit: 'From commit',
      confirmDeleteTag: 'Are you sure you want to delete this tag?',
      currentlyViewing: 'Currently viewing',
    },
    commit: {
      commits: 'Commits',
      commitHash: 'Commit hash',
      copyHash: 'Copy hash',
      commitHashCopied: 'Commit hash copied to clipboard',
      uncommittedChanges: 'Uncommitted changes',
      showingUncommittedChangesFor: 'Showing uncommitted changes for',
      commitChanges: 'Commit changes',
      revertChanges: 'Revert changes',
      confirmRevertChanges:
        'Are you sure you want to revert all uncommitted changes?',
      noUncommittedChanges: 'There are no uncommitted changes',
      noUncommittedChangesDescription:
        'To compare changes, you need to have uncommitted changes in the current branch',
      commitNewChangesTo: 'Commit new changes to',
      commitMessage: 'Commit message',
      commitMessagePlaceholder: 'Describe your changes',
    },
    compare: {
      compare: 'Compare',
      switchDirection: 'Switch direction',
      baseBranch: 'Base branch',
      compareBranch: 'Compare to branch',
      merge: 'Merge',
      into: 'into',
      comparing: 'Comparing',
      and: 'and',
      bytes: 'bytes',
      modified: 'modified',
      moved: 'moved',
      conflict: 'conflict',
      hideChanges: 'Hide changes',
      fetchChanges: 'Fetch changes',
      thereIsNothingToCompare: 'There is nothing to compare or merge',
      thereIsNothingToCompareSubtitle:
        'You need to use two different sources to get a valid comparison.',
      baseContent: 'Base content',
      comparedContent: 'Compared content',
      mergeStrategy: 'Merge strategy',
      squashCommits: 'Squash commits',
      mergeCommitDescription: 'Merge commit description',
      defaultStrategy: 'Default',
      destWinsStrategy: 'Destination wins',
      sourceWinsStrategy: 'Source wins',
      mergeExplanation:
        'In case of a merge conflict, this option will force the merge process to automatically favour changes from the base (“Destination wins”) or from the comparison (“Source wins”). In case no selection is made, the merge process will fail in case of a conflict.',
    },
    objects: {
      objects: 'Objects',
      noObjects: 'No objects found',
      noObjectsMessage:
        'Start by uploading files or create a workflow to populate this repository.',
      uploadObject: 'Upload object',
      path: 'Path',
      currentPath: 'Current path',
      currentName: 'Current name',
      type: 'Type',
      contentType: 'Content-Type',
      view: 'View',
      unsupportedContentType: 'Unsupported content type',
      contentUnavailable: 'Object content unavailable',
      viewSchema: 'View schema',
      filterObjects: 'Filter objects',
      createFolder: 'Create folder',
      uploadAndReplace: 'Upload and replace',
      moveOrRename: 'Move or rename',
      targetRepository: 'Target repository',
      targetBranch: 'Target branch',
      objectName: 'Object name',
      fileToUpload: 'File to upload',
      pathInRepository: 'Path in the repository',
      noFilesSelected: 'Select files to upload before submitting',
    },
    settings: {
      deletionNote:
        'Deleting this repository will remove all data associated with it. This action is irreversible.',
      deleteRepository: 'Delete repository',
    },
    schema: {
      schema: 'Schema',
      noSchema: 'No schema available',
    },
  },
  connections: {
    connection: 'Connection',
    connections: 'Connections',
    settings: {
      title: 'Connection settings',
      saveChanges: 'Save changes',
      deletionNote:
        'Deleting this connection will remove all data associated with it. This action is irreversible.',
      delete: 'Delete connection',
      areYouSureYouWantToDelete:
        'Are you sure you want to delete this connection?',
    },
    create: {
      selectConnector: 'Select a connector',
      establishConnection: 'Establish connection',
      configureSettings: 'Configure settings',
      configureConnection: 'Configure connection',
      createNewConnection: 'Create new connection',
      pleaseSelectConnector: 'Please select a connector to continue.',
      confirmConnectorSelection: 'Confirm connector selection and continue',
      selectedConnector: 'Selected connector',
      categoryAll: 'All',
      connectionName: 'Connection name',
      connectionNamePlaceholder: 'eg. My Google Analytics connection',
      connectionDescription: 'Connection description',
      connectionDescriptionPlaceholder:
        'Enter a description for the connection, so you can remember what it is used for',
      addCustomConnector: 'Add custom connector',
      continueAndTest: 'Continue & test connection',
      createConnection: 'Create connection',
      continue: 'Continue',
      goBack: 'Go back',
      success: 'Connection successful',
      failed: 'Connection failed',
      configuration_valid: 'Connection configuration valid',
      configuration_invalid: 'Connection configuration invalid',
      contactSupport: 'Contact support',
      requiredFieldsMissing: 'Required fields are missing',
    },
  },
  connectors: {
    connector: 'Connector',
    connectors: 'Connectors',
    version: 'Version',
    author: 'Author',
    authorEmail: 'Author email',
    categories: 'Categories',
    capabilities: 'Capabilities',
    locales: 'Locales',
  },
  workflow: {
    workflows: 'Workflows',
    importWorkflows: 'Import workflows',
    actionWorkflows: 'Action workflows',
    exportWorkflows: 'Export workflows',
    pipelineWorkflows: 'Pipeline workflows',
    actions: 'Actions',
    imports: 'Imports',
    exports: 'Exports',
    pipelines: 'Pipelines',
    triggerRun: 'Trigger workflow run',
    triggeringRun: 'Triggering run',
    workflow: 'Workflow',
    import: 'Import',
    action: 'Action',
    export: 'Export',
    run: 'run',
    startedAt: 'Started at',
    finishedAt: 'Finished at',
    scheduled: 'Scheduled',
    notScheduled: 'Not scheduled',
    openInEditor: 'Open in editor',
    executableScriptFile: 'Executable script file',
    scriptResultDestinationRepository: 'Result to repository',
    scriptResultDestinationBranch: 'Result to branch',
    scriptResultDestinationPath: 'Result to path',
    importSourceConnection: 'Import from connection',
    importDestinationRepository: 'Import to repository',
    importDestinationBranch: 'Import to branch',
    importDestinationPath: 'Import to path',
    exportDestinationConnection: 'Export to connection',
    exportSourceRepository: 'Export from repository',
    exportSourceBranch: 'Export from branch',
    exportSourcePath: 'Export from path',
    livePipeline: 'Live pipeline',
    triggeredBy: 'Triggered by',
    duration: 'Duration',
    tabs: {
      data: 'Data',
      logs: 'Logs',
      schedule: 'Schedule',
    },
    settings: {
      saveChanges: 'Save changes',
      deletionNote:
        'Deleting this workflow will remove all data associated with it. This action is irreversible.',
      delete: 'Delete workflow',
      areYouSureYouWantToDelete:
        'Are you sure you want to delete this workflow?',
      resumeWorkflow: 'Resume',
      pauseWorkflow: 'Pause',
    },
    create: {
      createNewWorkflow: 'Create new workflow',
      createNewActionWorkflow: 'Create new action workflow',
      createNewImportWorkflow: 'Create new import workflow',
      createNewExportWorkflow: 'Create new export workflow',
      createNewPipelineWorkflow: 'Create new pipeline workflow',
      configureImport: 'Configure import',
      configureAction: 'Configure action',
      configureExport: 'Configure export',
      configurePipeline: 'Configure pipeline',
      configureWorkflow: 'Configure workflow',
      confirmAndCreate: 'Confirm and create',
      confirmAndContinue: 'Confirm and continue',
      goBack: 'Go back',
    },
    pipeline: {
      pipeline: 'Pipeline',
      livePipeline: 'Live pipeline',
      addNewStage: 'Add new stage',
      addStage: 'Add stage',
      stage: 'Stage',
      descriptionPlaceholder: 'Describe what this pipeline stage does',
      write: 'Write',
      read: 'Read',
      executablePath: 'Executable path',
      executablePathDescription:
        'Path to the action script e.g. /path/to/script.py',
      connectionWritePath: 'Write Path',
      connectionWritePathDescription:
        'Path to write within the connection e.g. /path/to/write',
      connectionReadPath: 'Read Path',
      connectionReadPathDescription:
        'Path to read within the connection e.g. /path/to/read',
      moveUp: 'Move up',
      moveDown: 'Move down',
      savePipelineStages: 'Save pipeline stages',
      noStages: 'No stages',
    },
    schedule: {
      workflowSchedule: 'Workflow schedule',
      frequency: 'Frequency',
      interval: 'Interval',
      weekdays: 'Weekdays',
      trigger: 'Trigger',
      triggers: 'Triggers',
      timeTrigger: 'Time based trigger',
      repositoryEventTrigger: 'Repository event trigger',
      workflowRunEventTrigger: 'Workflow run event trigger',
      addTrigger: 'Add trigger',
      maxRetries: 'Max Retries',
      maxRuntime: 'Max Runtime (seconds)',
      minInterval: 'Min Interval (seconds)',
      triggerType: 'Trigger Type',
      recurrenceRule: 'Recurrence Rule',
      event: 'Event',
      saveSchedule: 'Save Schedule',
    },
  },
  editor: {
    writeYourJS: 'Write your JavaScript script here...',
    writeYourGo: 'Write your Go script here...',
    writeYourSQL: 'Write your SQL query here...',
    writeYourPython: 'Write your Python script here...',
    writeYourText: 'Write your text here...',
    writeYourMarkdown: 'Write your Markdown here...',
    writeYourJSON: 'Write your JSON here...',
    newScriptTitle: 'Create a new script',
    newScriptSubtitle:
      'Start writing your script in your preferred language and save it as a workflow',
    scriptExecutionStarted: 'Script execution started',
    scriptNeedsToBeSaved:
      'Script needs to be saved before running. Save the script in the editor and run it again.',
  },
  query: {
    queryExecutionStarted: 'Query execution started',
    results: 'Results',
    errors: 'Errors',
    logs: 'Logs',
    noErrors: 'No errors',
    queryResults: 'Query results',
    createQuery: 'Create query',
    saveAsWorkflow: 'Save as workflow',
    run: 'Run',
    rowsReturnedIn: 'rows returned in',
    exportTable: 'export table (.csv)',
    search: 'Search in results',
    newQuery: 'New query',
    selectedQuery: 'Selected query',
  },
  list: {
    status: 'Status',
    runs: 'Runs',
    actions: 'Actions',
    view: 'View',
    logs: 'Logs',
    delete: 'Delete',
    edit: 'Edit',
    owner: 'Owner',
    author: 'Author',
    lastUpdated: 'Last updated',
    createdAt: 'Created at',
    immutable: 'Immutable',
    source: 'Source',
    destination: 'Destination',
    searchPlaceholder: 'Type to search...',
    noItemsFound: 'No items found',
  },
  fileNavigator: {
    original: 'Original',
    saveFile: 'Save file',
    createFile: 'Create file',
    createFolder: 'Create folder',
    updateFile: 'Update file',
    updateFolder: 'Update folder',
    copyFolder: 'Copy folder',
    copyFile: 'Copy file',
    open: 'Open',
    rename: 'Rename',
    move: 'Move',
    root: 'Root',
    rootDirectory: 'Root directory',
    newNameOfTheFile: 'New name of the file',
    newNameOfTheFolder: 'New name of the folder',
    newPathOfTheFile: 'New path of the file',
    newPathOfTheFolder: 'New path of the folder',
    newFileName: 'New file name',
    newFolderName: 'New folder name',
    newFilePath: 'New file path',
    newFolderPath: 'New folder path',
    deleteConfirmation: 'Are you sure you want to delete',
    deleteFolderWarning: 'All files and folders inside will be deleted',
    errors: {
      invalidType: 'Invalid item type (file or folder)',
      noExtension: 'No extension provided',
      invalidExtension: 'Invalid file extension (js, py, sql)',
      emptyName: 'Name is empty',
      longName: 'Name is too long',
      invalidName: 'Invalid name',
      invalidPath: 'Invalid path',
      pathExists: 'Path already exists',
      parentPathNotExist: 'Parent path does not exist',
    },
  },
  documentation: {
    documentation: 'Documentation',
    startTypingDocumentation:
      'Start typing your documentation and notes here...',
    schema: 'Schema',
    workspace: 'Workspace',
    createdBy: 'Created by',
  },
  users: {
    removeUserConfirmation: 'Are you sure you want to remove this user?',
    transferOwnershipConfirmation:
      'Are you sure you want to transfer ownership?',
    usersAndPermissions: 'Users & Permissions',
    invites: 'Invites to the workspace',
    inviteUser: 'Invite a User',
    changeProfilePicture: 'Change profile picture',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    company: 'Company',
    role: 'Role',
    noRole: 'No role',
    updateProfile: 'Update profile',
    transferOwnership: 'Transfer ownership',
    removeFromWorkspace: 'Remove from workspace',
    resendInvite: 'Resend invite',
    cancelInvite: 'Cancel invite',
    invite: 'Invite',
  },
  invite: {
    acceptInvitation: 'Accept Invitation',
    declineInvitation: 'Decline invitation',
    workspaceInvitation: 'Workspace Invitation',
    workspaceInvitationDescription: 'You have been invited to join a workspace',
    invitedBy: 'Invited by',
    workspace: 'Workspace',
    role: 'Role',
  },
  workspace: {
    general: 'General',
    users: 'Users',
    invites: 'Invites',
    billing: 'Billing',
    deletionWarning:
      'Are you sure you want to delete this workspace? This action cannot be undone and will remove all data associated with this workspace.',
    generalSettings: 'General Settings',
    workspaceName: 'Workspace Name',
    workspaceDescription: 'Workspace Description',
    saveChanges: 'Save Changes',
    deletionNote:
      'Deleting your workspace will remove all data associated with it. This action is irreversible.',
    deleteWorkspace: 'Delete Workspace',
    billingSettings: 'Billing Settings',
    billingNote:
      'You can currently only manage billing by contacting our team.',
  },
  logs: {
    workspaceLogs: 'Workspace logs',
    workflowLogs: 'Workflow logs',
    repositoryLogs: 'Repository logs',
    connectionLogs: 'Connection logs',
    workflowRunLogs: 'Workflow run logs',
    noLogsFound: 'No logs found',
    system: 'System',
  },
  tokens: {
    apiTokens: 'API tokens',
    noTokens: 'You have no API tokens',
    createAPIToken: 'Create API token',
    validFor: 'Valid for (in seconds)',
    expiresAt: 'Expires at',
    revokeToken: 'Revoke token',
    yourAPIToken: 'Your API Token',
    storeTokenDescription:
      'This token will only be shown once. Please copy it and store it securely.',
    tokenRevealed: 'Token Revealed',
    revealToken: 'Reveal token',
    copied: 'Copied!',
    copyToken: 'Copy token',
  },
};

export default en;
