/**
 * Finnish dictionary, key-value pairs for static strings in the application
 */
const fi = {
  common: {
    selectLanguage: 'Valitse kieli',
    loading: 'Ladataan...',
    cancel: 'Peruuta',
    confirm: 'Vahvista',
    error: 'Virhe',
    ohNo: 'Voi ei!',
    pageNotFound: 'Sivua ei löytynyt',
    somethingWentWrong: 'Jotain meni pieleen',
    weEncounteredError: 'Kohtasimme virheen',
    tryAgainOrContactSupport: 'Yritä uudelleen tai ota yhteyttä tukeen',
    goBackHome: 'Mene takaisin kotisivulle',
    goBackConsole: 'Palaa Irmin-konsoliin',
    back: 'Takaisin',
    remove: 'Poista',
    tryAgain: 'Yritä uudelleen',
    success: 'Onnistui',
    info: 'Info',
    noOptionsMessage: 'Ei vaihtoehtoja',
    yes: 'Kyllä',
    no: 'Ei',
    fieldRequired: 'Kenttä on pakollinen',
    fieldInvalid: 'Kenttä on virheellinen',
    refresh: 'Päivitä',
    dangerZone: 'Vaaravyöhyke',
    resetForm: 'Tyhjennä lomake',
    pleaseFixErrors: 'Korjaa virheet yllä',
    lastModified: 'Viimeksi muokattu',
    size: 'Koko',
    close: 'Sulje',
    timestamp: 'Aikaleima',
    areYouSureYouWantToDelete:
      'Oletko varma, että haluat poistaa tämän kohteen?',
    areYouSureYouWantToTransferOwnership:
      'Oletko varma, että haluat vaihtaa tämän kohteen omistajan?',
    name: 'Nimi',
    description: 'Kuvaus',
    save: 'Tallenna',
    search: 'Hae',
    noResults: 'Ei tuloksia',
    contactUs: 'Ota yhteyttä',
    readMore: 'Lue lisää',
    overview: 'Yleiskatsaus',
    email: 'Sähköposti',
    message: 'Viesti',
    messagePlaceholder: 'Kirjoita viestisi tähän...',
    pleaseWait: 'Odota hetki...',
    downloadSuccess: 'Lataus onnistui',
    actions: {
      send: 'Lähetä',
      subscribe: 'Tilaa',
      download: 'Lataa',
    },
    terms: {
      termsAndConditions: 'Käyttöehdot',
      privacyPolicy: 'Tietosuojakäytäntö',
    },
  },
  theme: {
    toggle: 'Vaihda teemaa',
    light: 'Vaalea',
    dark: 'Tumma',
    system: 'Järjestelmä',
  },
  consoleNavigation: {
    searchPlaceholder: 'Etsi tietoja ja muuta',
    staticSearchItems: {
      guides: 'Irmin Oppaat',
      documentation: 'Irmin Dokumentaatio',
      termsAndPrivacy: 'Käyttöehdot & Tietosuojakäytäntö',
      createWorkspace: 'Luo uusi työtila',
      logs: 'Työtilan Lokit',
      workspaceDocumentation: 'Työtilan Dokumentaatio',
      myProfile: 'Oma Profiili',
      manageWorkspaces: 'Hallitse Työtiloja',
      editor: 'Muokkaustyökalu',
      workspaceSettings: 'Työtilan asetukset',
      createWorkflow: 'Luo uusi prosessi',
      createConnection: 'Luo uusi yhteys',
      createRepository: 'Luo uusi data-arkisto',
      description: {
        irminWebsite: 'Siirry Irmin verkkosivustolle',
        contactUs: 'Ota yhteyttä tiimiimme',
        guides: 'Lue Irmin oppaat',
        documentation: 'Lue Irmin dokumentaatio',
        termsAndPrivacy: 'Lue käyttöehdot ja tietosuojakäytäntö',
        createWorkspace: 'Luo uusi Irmin työtila ja aloita työskentely',
        logs: 'Näytä nykyisen työtilan lokit',
        workspaceDocumentation: 'Näytä työtilan dokumentaatio',
        myProfile: 'Näytä ja muokkaa profiiliasi',
        manageWorkspaces: 'Hallitse työtilojasi',
        editor: 'Kirjoita ja suorita skriptejä',
        workspaceSettings: 'Muokkaa työtilan asetuksia',
        workflows: 'Näytä ja hallitse prosesseja',
        actions: 'Näytä ja hallitse toimintoja',
        imports: 'Näytä ja hallitse tuonteja',
        exports: 'Näytä ja hallitse vientejä',
        pipelines: 'Näytä ja hallitse dataputkia',
        createWorkflow: 'Luo uusi minkä tahansa tyyppinen prosessi',
        connections: 'Näytä ja hallitse yhteyksiä',
        createConnection: 'Luo uusi yhteys käytettäväksi prosesseissa',
        repositories: 'Näytä ja hallitse data-arkistoja',
        createRepository: 'Luo uusi data-arkisto tietojen tallentamista varten',
      },
    },
    irmin: 'Irmin',
    irminConsole: 'Irmin-konsoli',
    irminWebsite: 'Irmin-verkkosivu',
    workspace: 'Työtila',
    settings: 'Asetukset',
    usefulLinks: 'Hyödylliset linkit',
    editor: 'Editori',
    queries: 'Kyselyt',
    logs: 'Lokit',
    workspaceSettings: 'Työtila',
    workspaces: 'Työtilat',
    goToWebsite: 'Siirry verkkosivustolle',
    myProfile: 'Profiilini',
    signOut: 'Kirjaudu ulos',
    guides: 'Oppaat',
    contactSupport: 'Ota yhteyttä tukeen',
    developerDocs: 'Dokumentaatio kehittäjille',
    termsAndPrivacy: 'Käyttöehdot ja tietosuoja',
  },
  consoleHome: {
    welcomeToWorkspace: 'Aloita työskentely valitsemalla näistä toiminnoista:',
    createNewConnection: 'Luo uusi yhteys',
    createNewConnectionDescription:
      'Yhdistä työtilallesi uusi tietolähde tai vientikohde ja aloita datan siirtäminen',
    runScriptOnData: 'Suorita skripti',
    runScriptOnDataDescription:
      'Kirjoita ja suorita skripti automatisoidaksesi tehtäviä tai saadaksesi oivalluksia',
    setupWorkflow: 'Luo prosessi',
    setupWorkflowDescription:
      'Automatisoi tietotehtäviä prosessien avulla: tiedon keräys, muuntaminen ja vienti',
    browseRepositories: 'Data ja data-arkistot',
    browseRepositoriesDescription:
      'Selaa, käsittele ja hallinnoi tietojasi Git-tyyppisessä ympäristössä',
  },
  workspaceSwitcher: {
    manageWorkspaces: 'Hallinnoi työtiloja',
    selectWorkspace: 'Valitse työtila',
    createNewWorkspace: 'Luo uusi työtila',
    workspace: 'Työtila',
    leaveWorkspace: 'Poistu työtilasta',
    leaveWorkspaceConfirm:
      'Oletko varma, että haluat poistua tästä työtilasta?',
  },
  repository: {
    repository: 'Data-arkisto',
    repositories: 'Data-arkistot',
    sqlQuery: 'SQL-kysely',
    runQuery: 'Aja kysely',
    createNewRepository: 'Luo uusi data-arkisto',
    immutableWarning: 'Muuttumaton data-arkisto tai haara',
    immutableWarningDescription:
      'Tämä data-arkisto tai valittu haara on muuttumaton, eikä sitä voi muokata.',
    branches: {
      branches: 'Haarat',
      currentBranch: 'Nykyinen',
      branch: 'Haara',
      createBranch: 'Luo haara',
      primary: 'Päähaara',
      primaryBranch: 'Päähaara',
      newBranchName: 'Uuden haaran nimi',
      fromBranch: 'Haarasta',
      confirmDeleteBranch: 'Oletko varma, että haluat poistaa tämän haaran?',
    },
    tags: {
      tag: 'Tagi',
      tags: 'Tagit',
      tagDescription: 'Tagi on immuuttinen viittaus tiettyyn commit-tilaan.',
      createTag: 'Luo tagi',
      newTagName: 'Uuden tagin nimi',
      fromCommit: 'Commitista',
      confirmDeleteTag: 'Oletko varma, että haluat poistaa tämän tagin?',
      currentlyViewing: 'Nykyinen näkymä',
    },
    commit: {
      commits: 'Commitit',
      commitHash: 'Commit hash',
      copyHash: 'Kopioi hash',
      commitHashCopied: 'Commit hash kopioitu leikepöydälle',
      uncommittedChanges: 'Tallentamattomat muutokset',
      showingUncommittedChangesFor:
        'Näytetään tallentamattomat muutokset haaralle',
      commitChanges: 'Tallenna muutokset',
      revertChanges: 'Peru muutokset',
      confirmRevertChanges:
        'Oletko varma, että haluat peruuttaa kaikki tallentamattomat muutokset?',
      noUncommittedChanges: 'Ei tallentamattomia muutoksia',
      noUncommittedChangesDescription:
        'Jotta voit verrata muutoksia, sinun on tehtävä tallentamattomia muutoksia nykyiseen haaraan',
      commitNewChangesTo: 'Tallenna uudet muutokset haaralle',
      commitMessage: 'Commit-viesti',
      commitMessagePlaceholder: 'Kuvaile muutokset',
    },
    compare: {
      compare: 'Vertaa',
      switchDirection: 'Vaihda suuntaa',
      baseBranch: 'Pohjahaara',
      compareBranch: 'Vertailuhaara',
      merge: 'Sulauta',
      into: 'haaraan',
      comparing: 'Verrataan',
      and: 'ja',
      bytes: 'tavua',
      modified: 'muokattu',
      moved: 'siirretty',
      conflict: 'konflikti',
      hideChanges: 'Piilota muutokset',
      fetchChanges: 'Hae muutokset',
      thereIsNothingToCompare: 'Ei mitään vertailtavaa tai yhdistettävää',
      thereIsNothingToCompareSubtitle:
        'Tarvitset kaksi eri lähdettä saadaksesi pätevän vertailun.',
      baseContent: 'Pohjasisältö',
      comparedContent: 'Vertailusisältö',
      mergeStrategy: 'Sulautusstrategia',
      squashCommits: 'Yhdistä commitit',
      mergeCommitDescription: 'Sulautuscommitin kuvaus',
      defaultStrategy: 'Oletus',
      destWinsStrategy: 'Kohde voittaa',
      sourceWinsStrategy: 'Lähde voittaa',
      mergeExplanation:
        'Jos sulauttamisessa esiintyy konflikti, tämä asetus suosii automaattisesti pohjan ("Kohde voittaa") tai vertailun ("Lähde voittaa") muutoksia. Ellei mitään valintaa tehdä, sulautus epäonnistuu konfliktitilanteessa.',
    },
    objects: {
      objects: 'Objektit',
      noObjects: 'Ei objekteja',
      noObjectsMessage:
        'Aloita lataamalla tiedostoja tai luomalla tuontiprosessin',
      uploadObject: 'Lataa objekti',
      path: 'Polku',
      currentPath: 'Nykyinen polku',
      currentName: 'Nykyinen nimi',
      type: 'Tyyppi',
      contentType: 'Sisältötyyppi',
      view: 'Näytä',
      unsupportedContentType: 'Sisältötyyppiä ei tueta',
      contentUnavailable: 'Objektin sisältö ei ole saatavilla',
      viewSchema: 'Näytä rakenne',
      filterObjects: 'Suodata objekteja',
      uploadAndReplace: 'Lataa ja korvaa',
      moveOrRename: 'Siirrä tai nimeä uudelleen',
      targetRepository: 'Kohde data-arkisto',
      targetBranch: 'Kohde haara',
      objectName: 'Objektin nimi',
      fileToUpload: 'Ladattava tiedosto',
      pathInRepository: 'Polku data-arkistossa',
      noFilesSelected: 'Valitse tiedostot ennen lataamista',
      binary: 'Binary',
      group: 'Group',
      structured: 'Structured',
      children: 'Lapset',
      hideChildren: 'Hide children',
      showChildren: 'Show children',
      unknownType: 'Unknown type',
      hideSchema: 'Hide schema',
      showSchema: 'Show schema',
    },
    settings: {
      deletionNote:
        'Data-arkiston poistaminen poistaa kaiken siihen liittyvän datan. Tätä toimintoa ei voi peruuttaa.',
      deleteRepository: 'Poista data-arkisto',
    },
    schema: {
      schema: 'Rakenne',
      noSchema: 'Ei rakennetta saatavilla',
    },
  },
  connections: {
    connection: 'Yhteys',
    connections: 'Yhteydet',
    settings: {
      title: 'Yhteyden asetukset',
      saveChanges: 'Tallenna muutokset',
      deletionNote:
        'Poistamalla tämän yhteyden poistetaan kaikki siihen liittyvä data. Tätä toimintoa ei voi peruuttaa.',
      delete: 'Poista yhteys',
      areYouSureYouWantToDelete:
        'Oletko varma, että haluat poistaa tämän yhteyden?',
    },
    create: {
      selectConnector: 'Valitse yhdistin',
      establishConnection: 'Perusta yhteys',
      configureSettings: 'Määritä asetukset',
      configureConnection: 'Määritä yhteys',
      createNewConnection: 'Luo uusi yhteys',
      pleaseSelectConnector: 'Valitse yhdistin jatkaaksesi',
      confirmConnectorSelection: 'Vahvista yhdistimen valinta ja jatka',
      selectedConnector: 'Valittu yhdistin',
      categoryAll: 'Kaikki',
      connectionName: 'Yhteyden nimi',
      connectionNamePlaceholder: 'esim. Minun Google Analytics -yhteys',
      connectionDescription: 'Yhteyden kuvaus',
      connectionDescriptionPlaceholder:
        'Kirjoita kuvaus yhteydelle, jotta muut tietävät, mihin sitä käytetään',
      addCustomConnector: 'Lisää oma yhdistin',
      continueAndTest: 'Jatka ja testaa yhteys',
      createConnection: 'Luo yhteys',
      continue: 'Jatka',
      goBack: 'Mene takaisin',
      success: 'Yhteys onnistui',
      failed: 'Yhteys epäonnistui',
      configuration_valid: 'Yhteyden konfiguraatio on validi',
      configuration_invalid: 'Yhteyden konfiguraatio on virheellinen',
      contactSupport: 'Ota yhteyttä tukeen',
      requiredFieldsMissing: 'Pakollisia kenttiä puuttuu',
    },
  },
  connectors: {
    connector: 'Yhdistin',
    connectors: 'Yhdistimet',
    version: 'Versio',
    author: 'Tekijä',
    authorEmail: 'Tekijän sähköposti',
    categories: 'Kategoriat',
    capabilities: 'Toiminallisuudet',
    locales: 'Kielet',
  },
  workflow: {
    workflows: 'Prosessit',
    importWorkflows: 'Tuontiprosessit',
    actionWorkflows: 'Toimintoprosessit',
    exportWorkflows: 'Vientiprosessit',
    pipelineWorkflows: 'Dataputkiprosessit',
    actions: 'Toiminnot',
    imports: 'Tuonnit',
    exports: 'Viennit',
    pipelines: 'Dataputket',
    triggerRun: 'Käynnistä ajo',
    triggeringRun: 'Käynnistetään ajoa',
    workflow: 'Prosessi',
    import: 'Tuonti',
    action: 'Toiminto',
    export: 'Vienti',
    run: 'Ajo',
    noStatus: 'Ei statusta',
    startedAt: 'Aloitettu',
    finishedAt: 'Valmis',
    scheduled: 'Aikataulutettu',
    notScheduled: 'Ei aikataulutettu',
    openInEditor: 'Avaa editorissa',
    executableScriptFile: 'Suoritettava skriptitiedosto',
    scriptResultDestinationRepository: 'Tuloksen data-arkisto',
    scriptResultDestinationBranch: 'Tuloksen haara',
    scriptResultDestinationPath: 'Tuloksen polku',
    importSourceConnection: 'Tuonnin lähdeyhteys',
    importSourceConnectionPath: 'Tuonnin lähdeyhteyden polku',
    importDestinationRepository: 'Tuonnin kohdedata-arkisto',
    importDestinationBranch: 'Tuonnin kohdehaara',
    importDestinationPath: 'Tuonnin kohdepolku',
    exportDestinationConnection: 'Viennin kohdeyhteys',
    exportDestinationConnectionPath: 'Viennin kohdeyhteyden polku',
    exportSourceRepository: 'Vientilähteen data-arkisto',
    exportSourceBranch: 'Vientilähteen haara',
    exportSourcePath: 'Vientilähteen polku',
    livePipeline: 'Live-dataputki',
    triggeredBy: 'Laukaisija',
    duration: 'Kesto',
    tabs: {
      data: 'Data',
      logs: 'Lokit',
      schedule: 'Aikataulu',
    },
    settings: {
      saveChanges: 'Tallenna muutokset',
      deletionNote:
        'Poistamalla tämän prosessin poistetaan kaikki siihen liittyvä data. Tätä toimintoa ei voi peruuttaa.',
      delete: 'Poista prosessi',
      areYouSureYouWantToDelete:
        'Oletko varma, että haluat poistaa tämän prosessin?',
      resumeWorkflow: 'Jatka',
      pauseWorkflow: 'Pysäytä',
    },
    create: {
      createNewWorkflow: 'Luo uusi prosessi',
      createNewActionWorkflow: 'Luo uusi toimintoprosessi',
      createNewImportWorkflow: 'Luo uusi tuontiprosessi',
      createNewExportWorkflow: 'Luo uusi vientiprosessi',
      createNewPipelineWorkflow: 'Luo uusi dataputkiprosessi',
      configureImport: 'Määritä tuonti',
      configureAction: 'Määritä toiminto',
      configureExport: 'Määritä vienti',
      configurePipeline: 'Määritä dataputki',
      configureWorkflow: 'Määritä prosessi',
      confirmAndCreate: 'Vahvista ja luo',
      confirmAndContinue: 'Vahvista ja jatka',
      goBack: 'Mene takaisin',
    },
    pipeline: {
      pipeline: 'Dataputki',
      livePipeline: 'Live-dataputki',
      addNewStage: 'Lisää uusi vaihe',
      addStage: 'Lisää vaihe',
      stage: 'Vaihe',
      descriptionPlaceholder: 'Kuvaile, mitä tämä dataputken vaihe tekee',
      write: 'Kirjoita',
      read: 'Lue',
      executablePath: 'Suoritettava polku',
      executablePathDescription:
        'Polku suoritettavaan skriptiin (esim. /path/to/script.py)',
      connectionWritePath: 'Kirjoittamisen polku',
      connectionWritePathDescription:
        'Polku, johon data kirjoitetaan (esim. /path/to/write)',
      connectionReadPath: 'Lukupolku',
      connectionReadPathDescription:
        'Polku, josta data luetaan (esim. /path/to/read)',
      moveUp: 'Siirrä ylös',
      moveDown: 'Siirrä alas',
      savePipelineStages: 'Tallenna vaiheet',
      noStages: 'Ei vaiheita',
    },
    schedule: {
      workflowSchedule: 'Prosessin aikataulu',
      frequency: 'Usein toistuva?',
      interval: 'Väli',
      weekdays: 'Viikonpäivät',
      trigger: 'Laukaisin',
      triggers: 'Laukaisimet',
      timeTrigger: 'Aikapohjainen laukaisin',
      repositoryEventTrigger: 'Data-arkiston tapahtumalaukaisin',
      workflowRunEventTrigger: 'Prosessin ajotapahtuma-laukaisin',
      addTrigger: 'Lisää laukaisin',
      maxRetries: 'Enimmäisyritykset',
      maxRuntime: 'Maksimiaika (sekunteina)',
      minInterval: 'Minimiaika (sekunteina)',
      triggerType: 'Laukaisimen tyyppi',
      recurrenceRule: 'Toistumissääntö',
      event: 'Tapahtuma',
      saveSchedule: 'Tallenna aikataulu',
    },
  },
  editor: {
    writeYourJS: 'Kirjoita JavaScriptisi tähän...',
    writeYourGo: 'Kirjoita Go-skriptisi tähän...',
    writeYourSQL: 'Kirjoita SQL-kyselysi tähän...',
    writeYourPython: 'Kirjoita Python-koodisi tähän...',
    writeYourText: 'Kirjoita teksti tähän...',
    writeYourMarkdown: 'Kirjoita Markdown-tekstisi tähän...',
    writeYourJSON: 'Kirjoita JSON-objektisi tähän...',
    newScriptTitle: 'Luo uusi skripti',
    newScriptSubtitle:
      'Kirjoita skripti haluamallasi kielellä ja tallenna se prosessina',
    scriptExecutionStarted: 'Skriptin suoritus aloitettu',
    scriptNeedsToBeSaved:
      'Skripti on tallennettava ennen suorittamista. Tallenna skripti editoriin ja suorita se uudelleen.',
  },
  query: {
    queryExecutionStarted: 'Kyselyn suoritus aloitettu',
    results: 'Tulokset',
    errors: 'Virheet',
    logs: 'Lokit',
    noErrors: 'Ei virheitä',
    queryResults: 'Kyselyn tulokset',
    createQuery: 'Luo kysely',
    saveAsWorkflow: 'Tallenna prosessina',
    run: 'Suorita',
    rowsReturnedIn: 'riviä palautettu ajassa',
    exportTable: 'vie taulukko (.csv)',
    search: 'Hae tuloksista',
    newQuery: 'Uusi kysely',
    selectedQuery: 'Valittu kysely',
  },
  list: {
    status: 'Tila',
    runs: 'Ajot',
    actions: 'Toiminnot',
    view: 'Katso',
    logs: 'Lokit',
    delete: 'Poista',
    edit: 'Muokkaa',
    owner: 'Omistaja',
    author: 'Luoja',
    lastUpdated: 'Päivitetty',
    createdAt: 'Luotu',
    immutable: 'Muuttumaton',
    source: 'Lähde',
    destination: 'Kohde',
    searchPlaceholder: 'Kirjoita hakusana...',
    noItemsFound: 'Ei kohteita',
  },
  fileNavigator: {
    original: 'Alkuperäinen',
    saveFile: 'Tallenna tiedosto',
    createFile: 'Luo tiedosto',
    createFolder: 'Luo kansio',
    updateFile: 'Päivitä tiedosto',
    updateFolder: 'Päivitä kansio',
    copyFolder: 'Kopioi kansio',
    copyFile: 'Kopioi tiedosto',
    open: 'Avaa',
    rename: 'Nimeä uudelleen',
    move: 'Siirrä',
    root: 'Juuri',
    rootDirectory: 'Juurihakemisto',
    newNameOfTheFile: 'Tiedoston uusi nimi',
    newNameOfTheFolder: 'Kansion uusi nimi',
    newPathOfTheFile: 'Tiedoston uusi polku',
    newPathOfTheFolder: 'Kansion uusi polku',
    newFileName: 'Uuden tiedoston nimi',
    newFolderName: 'Uuden kansion nimi',
    newFilePath: 'Uuden tiedoston polku',
    newFolderPath: 'Uuden kansion polku',
    deleteConfirmation: 'Oletko varma, että haluat poistaa',
    deleteFolderWarning:
      'Kaikki tämän kansion tiedostot ja alikansiot poistetaan',
    errors: {
      invalidType: 'Virheellinen tyyppi (tiedosto tai kansio)',
      noExtension: 'Tiedoston pääte puuttuu tai on virheellinen',
      invalidExtension: 'Virheellinen tiedostopääte (js, py, sql)',
      emptyName: 'Nimi ei voi olla tyhjä',
      longName: 'Nimi on liian pitkä',
      invalidName: 'Virheellinen nimi',
      invalidPath: 'Virheellinen polku',
      pathExists: 'Polku on jo olemassa',
      parentPathNotExist: 'Yläkansiota ei ole olemassa',
    },
  },
  documentation: {
    documentation: 'Dokumentaatio',
    startTypingDocumentation:
      'Aloita dokumentaation ja muistiinpanojen kirjoittaminen tähän...',
    schema: 'Rakenne',
    workspace: 'Työtila',
    createdBy: 'Luonut',
  },
  users: {
    removeUserConfirmation:
      'Oletko varma, että haluat poistaa tämän käyttäjän?',
    transferOwnershipConfirmation:
      'Oletko varma, että haluat siirtää omistajuuden?',
    usersAndPermissions: 'Käyttäjät ja oikeudet',
    invites: 'Kutsut työtilaan',
    inviteUser: 'Kutsu käyttäjä',
    changeProfilePicture: 'Vaihda profiilikuva',
    firstName: 'Etunimi',
    lastName: 'Sukunimi',
    email: 'Sähköposti',
    phone: 'Puhelinnumero',
    company: 'Yritys',
    role: 'Rooli',
    noRole: 'Ei roolia',
    updateProfile: 'Päivitä profiili',
    transferOwnership: 'Siirrä omistajuus',
    removeFromWorkspace: 'Poista työtilasta',
    resendInvite: 'Lähetä kutsu uudelleen',
    cancelInvite: 'Peruuta kutsu',
    invite: 'Kutsu',
  },
  invite: {
    acceptInvitation: 'Hyväksy kutsu',
    declineInvitation: 'Hylkää kutsu',
    workspaceInvitation: 'Kutsu työtilaan',
    workspaceInvitationDescription: 'Sinut on kutsuttu liittymään työtilaan',
    invitedBy: 'Kutsuja',
    workspace: 'Työtila',
    role: 'Rooli',
  },
  workspace: {
    general: 'Yleiset',
    users: 'Käyttäjät',
    invites: 'Kutsut',
    billing: 'Laskutus',
    deletionWarning:
      'Oletko varma, että haluat poistaa tämän työtilan? Tätä toimintoa ei voi peruuttaa ja se poistaa kaiken tähän työtilaan liittyvän datan.',
    generalSettings: 'Yleiset asetukset',
    workspaceName: 'Työtilan nimi',
    workspaceDescription: 'Työtilan kuvaus',
    saveChanges: 'Tallenna muutokset',
    deletionNote:
      'Työtilan poistaminen poistaa kaiken siihen liittyvän datan. Tätä toimintoa ei voi peruuttaa.',
    deleteWorkspace: 'Poista työtila',
    billingSettings: 'Laskutuksen asetukset',
    billingNote:
      'Voit tällä hetkellä hallita laskutusta vain ottamalla yhteyttä tiimiimme.',
  },
  logs: {
    workspaceLogs: 'Työtilan lokit',
    workflowLogs: 'Prosessin lokit',
    noLogsFound: 'Ei lokeja löytynyt',
    system: 'Järjestelmä',
  },
  tokens: {
    apiTokens: 'API avaimet',
    noTokens: 'Sinulla ei ole vielä luotuja API avaimia',
    createAPIToken: 'Luo API avain',
    validFor: 'Voimassa (sekunneissa)',
    expiresAt: 'Vanhenee',
    revokeToken: 'Poista avain',
    yourAPIToken: 'Sinun API avain',
    storeTokenDescription:
      'Tämä avain näytetään vain kerran. Ole hyvä ja kopio se, sekä säilytä turvallisesti.',
    tokenRevealed: 'Avain näytetty',
    revealToken: 'Näytä avain',
    copied: 'Kopioitu!',
    copyToken: 'Kopioi avain',
  },
};

export default fi;
