/**
 * Finnish dictionary, key-value pairs for static strings in the application
 */
const fi = {
  // === CORE APPLICATION ===
  common: {
    // Basic actions
    loading: 'Ladataan...',
    cancel: 'Peruuta',
    confirm: 'Vahvista',
    save: 'Tallenna',
    delete: 'Poista',
    edit: 'Muokkaa',
    view: 'Näytä',
    create: 'Luo',
    update: 'Päivitä',
    add: 'Lisää',
    remove: 'Poista',
    upload: 'Lataa',
    download: 'Lataa',
    back: 'Takaisin',
    next: 'Seuraava',
    previous: 'Edellinen',
    close: 'Sulje',
    open: 'Avaa',
    refresh: 'Päivitä',
    tryAgain: 'Yritä uudelleen',

    // Search and navigation
    search: 'Hae',
    filters: 'Suodattimet',
    noResults: 'Ei tuloksia',
    loadMore: 'Lataa lisää',
    selectAll: 'Valitse kaikki',

    // Status and feedback
    success: 'Onnistui',
    error: 'Virhe',
    info: 'Info',
    yes: 'Kyllä',
    no: 'Ei',

    // Content
    name: 'Nimi',
    description: 'Kuvaus',
    email: 'Sähköposti',
    message: 'Viesti',
    overview: 'Yleiskatsaus',
    actions: 'Toiminnot',
    logs: 'Lokit',
    timestamp: 'Aikaleima',
    lastModified: 'Viimeksi muokattu',
    size: 'Koko',
    color: 'Väri',

    // Forms
    fieldRequired: 'Kenttä on pakollinen',
    fieldInvalid: 'Kenttä on virheellinen',
    resetForm: 'Tyhjennä lomake',
    pleaseFixErrors: 'Korjaa virheet yllä',
    messagePlaceholder: 'Kirjoita viestisi tähän...',

    // Messages and alerts
    insufficientPermissions: 'Liian vähän oikeuksia',
    ohNo: 'Voi ei!',
    pageNotFound: 'Sivua ei löytynyt',
    somethingWentWrong: 'Jotain meni pieleen',
    weEncounteredError: 'Kohtasimme virheen',
    tryAgainOrContactSupport: 'Yritä uudelleen tai ota yhteyttä tukeen',
    goBackHome: 'Mene takaisin kotisivulle',
    goBackConsole: 'Palaa Irmin-konsoliin',
    noOptionsMessage: 'Ei vaihtoehtoja',
    downloadSuccess: 'Lataus onnistui',
    dangerZone: 'Vaaravyöhyke',

    // Confirmations
    areYouSureYouWantToDelete:
      'Oletko varma, että haluat poistaa tämän kohteen?',
    areYouSureYouWantToTransferOwnership:
      'Oletko varma, että haluat vaihtaa tämän kohteen omistajan?',

    // Contact and support
    contactUs: 'Ota yhteyttä',
    readMore: 'Lue lisää',

    // Language and localization
    selectLanguage: 'Valitse kieli',
  },

  // === USER INTERFACE ===
  theme: {
    toggle: 'Vaihda teemaa',
    light: 'Vaalea',
    dark: 'Tumma',
    system: 'Järjestelmä',
  },

  search: {
    advancedSearch: 'Edistynyt haku',
    searchDescription:
      'Hae data-arkistoista, prosesseista, yhteyksistä ja muusta',
    searchPlaceholder: 'Hae mitä tahansa...',
    contentTypes: 'Sisältötyypit',
    fromDate: 'Alkaen',
    toDate: 'Päättyen',
    resultsPerPage: 'Tuloksia per sivu',
    noResultsFound: 'Ei tuloksia',
    tryAdjustingFilters: 'Kokeile muuttaa hakutermejä tai suodattimia',
    startSearching: 'Aloita hakeminen',
    startSearchingDescription:
      'Syötä hakutermi yllä löytääksesi data-arkistoja, prosesseja, yhteyksiä ja muuta',
    searchingText: 'Haetaan...',
    resultsFoundFor: 'tulosta löytyi haulle',
    resultFoundFor: 'tulos löytyi haulle',
  },

  // === NAVIGATION ===
  consoleNavigation: {
    searchPlaceholder: 'Etsi tietoja ja muuta',
    irmin: 'Irmin',
    irminConsole: 'Irmin-konsoli',
    irminWebsite: 'Irmin-verkkosivu',
    workspace: 'Työtila',
    workspaces: 'Työtilat',
    settings: 'Asetukset',
    usefulLinks: 'Hyödylliset linkit',
    editor: 'Editori',
    queries: 'Kyselyt',
    workspaceSettings: 'Työtila',
    goToWebsite: 'Siirry verkkosivustolle',
    myProfile: 'Profiilini',
    signOut: 'Kirjaudu ulos',
    guides: 'Oppaat',
    contactSupport: 'Ota yhteyttä tukeen',
    developerDocs: 'Dokumentaatio kehittäjille',
    termsAndPrivacy: 'Käyttöehdot ja tietosuoja',

    staticSearchItems: {
      guides: 'Irmin Oppaat',
      documentation: 'Irmin Dokumentaatio',
      termsAndPrivacy: 'Käyttöehdot & Tietosuojakäytäntö',
      createWorkspace: 'Luo uusi työtila',
      workspaceDocumentation: 'Työtilan Dokumentaatio',
      myProfile: 'Oma Profiili',
      manageWorkspaces: 'Hallitse Työtiloja',
      editor: 'Muokkaustyökalu',
      workspaceSettings: 'Työtilan asetukset',
      createWorkflow: 'Luo uusi prosessi',
      createConnection: 'Luo uusi yhteys',
      createRepository: 'Luo uusi data-arkisto',

      description: {
        irminWebsite: 'Siirry Irmin verkkosivustolle',
        contactUs: 'Ota yhteyttä tiimiimme',
        guides: 'Lue Irmin oppaat',
        documentation: 'Lue Irmin dokumentaatio',
        termsAndPrivacy: 'Lue käyttöehdot ja tietosuojakäytäntö',
        createWorkspace: 'Luo uusi Irmin työtila ja aloita työskentely',
        logs: 'Näytä nykyisen työtilan lokit',
        workspaceDocumentation: 'Näytä työtilan dokumentaatio',
        myProfile: 'Näytä ja muokkaa profiiliasi',
        manageWorkspaces: 'Hallitse työtilojasi',
        editor: 'Kirjoita ja suorita skriptejä',
        workspaceSettings: 'Muokkaa työtilan asetuksia',
        workflows: 'Näytä ja hallitse prosesseja',
        actions: 'Näytä ja hallitse toimintoja',
        imports: 'Näytä ja hallitse tuonteja',
        exports: 'Näytä ja hallitse vientejä',
        pipelines: 'Näytä ja hallitse dataputkia',
        createWorkflow: 'Luo uusi minkä tahansa tyyppinen prosessi',
        connections: 'Näytä ja hallitse yhteyksiä',
        createConnection: 'Luo uusi yhteys käytettäväksi prosesseissa',
        repositories: 'Näytä ja hallitse data-arkistoja',
        createRepository: 'Luo uusi data-arkisto tietojen tallentamista varten',
      },
    },
  },
  // === WORKSPACE ===
  workspace: {
    general: 'Yleiset',
    users: 'Käyttäjät',
    policies: 'Oikeudet',
    invites: 'Kutsut',
    tags: 'Tunnisteet',
    billing: 'Laskutus',
    deletionWarning:
      'Oletko varma, että haluat poistaa tämän työtilan? Tätä toimintoa ei voi peruuttaa ja se poistaa kaiken tähän työtilaan liittyvän datan.',
    generalSettings: 'Yleiset asetukset',
    workspaceName: 'Työtilan nimi',
    workspaceDescription: 'Työtilan kuvaus',
    saveChanges: 'Tallenna muutokset',
    deletionNote:
      'Työtilan poistaminen poistaa kaiken siihen liittyvän datan. Tätä toimintoa ei voi peruuttaa.',
    deleteWorkspace: 'Poista työtila',
    billingSettings: 'Laskutuksen asetukset',
    billingNote:
      'Voit tällä hetkellä hallita laskutusta vain ottamalla yhteyttä tiimiimme.',
    taggedItems: 'Tunnistetut kohteet',
    addTags: 'Lisää tunnisteet',
    failedToLoadTags: 'Tunnisteiden lataaminen epäonnistui',
    failedToLoadWorkspaces: 'Työtilojen lataaminen epäonnistui',
  },

  workspaceSwitcher: {
    manageWorkspaces: 'Hallinnoi työtiloja',
    selectWorkspace: 'Valitse työtila',
    createNewWorkspace: 'Luo uusi työtila',
    createFirstWorkspace: 'Luo ensimmäinen työtilasi',
    createFirstWorkspaceDescription:
      'Työtilat auttavat organisoimaan datasi, työnkulkusi ja tiimityöskentelyn. Aloita luomalla ensimmäinen työtilasi.',
    workspace: 'Työtila',
    leaveWorkspace: 'Poistu työtilasta',
    leaveWorkspaceConfirm:
      'Oletko varma, että haluat poistua tästä työtilasta?',
  },

  consoleHome: {
    welcomeToWorkspace: 'Aloita työskentely valitsemalla näistä toiminnoista:',
    createNewConnection: 'Luo uusi yhteys',
    createNewConnectionDescription:
      'Yhdistä työtilallesi uusi tietolähde tai vientikohde ja aloita datan siirtäminen',
    runScriptOnData: 'Suorita skripti',
    runScriptOnDataDescription:
      'Kirjoita ja suorita skripti automatisoidaksesi tehtäviä tai saadaksesi oivalluksia',
    setupWorkflow: 'Luo prosessi',
    setupWorkflowDescription:
      'Automatisoi tietotehtäviä prosessien avulla: tiedon keräys, muuntaminen ja vienti',
    browseRepositories: 'Data ja data-arkistot',
    browseRepositoriesDescription:
      'Selaa, käsittele ja hallinnoi tietojasi Git-tyyppisessä ympäristössä',
  },

  // === DATA MANAGEMENT ===
  repository: {
    repository: 'Data-arkisto',
    repositories: 'Data-arkistot',
    sqlQuery: 'SQL-kysely',
    runQuery: 'Aja kysely',
    createNewRepository: 'Luo uusi data-arkisto',
    immutableWarning: 'Muuttumaton data-arkisto tai haara',
    immutableWarningDescription:
      'Tämä data-arkisto tai valittu haara on muuttumaton, eikä sitä voi muokata.',
    branches: {
      branches: 'Haarat',
      currentBranch: 'Nykyinen',
      branch: 'Haara',
      ref: 'Ref',
      createBranch: 'Luo haara',
      primary: 'Päähaara',
      primaryBranch: 'Päähaara',
      newBranchName: 'Uuden haaran nimi',
      fromBranch: 'Haarasta',
      confirmDeleteBranch: 'Oletko varma, että haluat poistaa tämän haaran?',
    },
    tags: {
      tag: 'Tagi',
      tags: 'Tagit',
      tagDescription: 'Tagi on immuuttinen viittaus tiettyyn commit-tilaan.',
      createTag: 'Luo tagi',
      newTagName: 'Uuden tagin nimi',
      fromCommit: 'Commitista',
      confirmDeleteTag: 'Oletko varma, että haluat poistaa tämän tagin?',
      currentlyViewing: 'Nykyinen näkymä',
    },
    commit: {
      commits: 'Commitit',
      commitHash: 'Commit hash',
      copyHash: 'Kopioi hash',
      commitHashCopied: 'Commit hash kopioitu leikepöydälle',
      uncommittedChanges: 'Tallentamattomat muutokset',
      showingUncommittedChangesFor:
        'Näytetään tallentamattomat muutokset haaralle',
      commitChanges: 'Tallenna muutokset',
      revertChanges: 'Peru muutokset',
      confirmRevertChanges:
        'Oletko varma, että haluat peruuttaa kaikki tallentamattomat muutokset?',
      noUncommittedChanges: 'Ei tallentamattomia muutoksia',
      noUncommittedChangesDescription:
        'Jotta voit verrata muutoksia, sinun on tehtävä tallentamattomia muutoksia nykyiseen haaraan',
      commitNewChangesTo: 'Tallenna uudet muutokset haaralle',
      commitMessage: 'Commit-viesti',
      commitMessagePlaceholder: 'Kuvaile muutokset',
    },
    compare: {
      compare: 'Vertaa',
      switchDirection: 'Vaihda suuntaa',
      baseBranch: 'Pohjahaara',
      compareBranch: 'Vertailuhaara',
      merge: 'Sulauta',
      into: 'haaraan',
      comparing: 'Verrataan',
      and: 'ja',
      bytes: 'tavua',
      modified: 'muokattu',
      moved: 'siirretty',
      conflict: 'konflikti',
      hideChanges: 'Piilota muutokset',
      fetchChanges: 'Hae muutokset',
      thereIsNothingToCompare: 'Ei mitään vertailtavaa tai yhdistettävää',
      thereIsNothingToCompareSubtitle:
        'Tarvitset kaksi eri lähdettä saadaksesi pätevän vertailun.',
      baseContent: 'Pohjasisältö',
      comparedContent: 'Vertailusisältö',
      mergeStrategy: 'Sulautusstrategia',
      squashCommits: 'Yhdistä commitit',
      mergeCommitDescription: 'Sulautuscommitin kuvaus',
      defaultStrategy: 'Oletus',
      destWinsStrategy: 'Kohde voittaa',
      sourceWinsStrategy: 'Lähde voittaa',
      mergeExplanation:
        'Jos sulauttamisessa esiintyy konflikti, tämä asetus suosii automaattisesti pohjan ("Kohde voittaa") tai vertailun ("Lähde voittaa") muutoksia. Ellei mitään valintaa tehdä, sulautus epäonnistuu konfliktitilanteessa.',
    },
    objects: {
      object: 'Objekti',
      objects: 'Objektit',
      noObjects: 'Ei objekteja',
      noObjectsMessage:
        'Aloita lataamalla tiedostoja tai luomalla tuontiprosessin',
      uploadObject: 'Lataa objekti',
      path: 'Polku',
      currentPath: 'Nykyinen polku',
      currentName: 'Nykyinen nimi',
      type: 'Tyyppi',
      contentType: 'Sisältötyyppi',
      view: 'Näytä',
      unsupportedContentType: 'Sisältötyyppiä ei tueta',
      contentUnavailable: 'Objektin sisältö ei ole saatavilla',
      viewSchema: 'Näytä rakenne',
      filterObjects: 'Suodata objekteja',
      uploadAndReplace: 'Lataa ja korvaa',
      moveOrRename: 'Siirrä tai nimeä uudelleen',
      changeHistory: 'Muutoshistoria',
      targetRepository: 'Kohde data-arkisto',
      targetBranch: 'Kohde haara',
      objectName: 'Objektin nimi',
      fileToUpload: 'Ladattava tiedosto',
      pathInRepository: 'Polku data-arkistossa',
      noFilesSelected: 'Valitse tiedostot ennen lataamista',
      binary: 'Binääri',
      group: 'Ryhmä',
      structured: 'Strukturoitu',
      children: 'Lapset',
      hideChildren: 'Piilota lapset',
      showChildren: 'Näytä lapset',
      unknownType: 'Tuntematon tyyppi',
      hideSchema: 'Piilota rakenne',
      showSchema: 'Näytä rakenne',
      enterPath: 'Syötä data-arkiston polku (esim. polku/tiedostoon.json)',
      newObjectWillBeCreated: 'Uusi objekti luodaan',
    },
    settings: {
      deletionNote:
        'Data-arkiston poistaminen poistaa kaiken siihen liittyvän datan. Tätä toimintoa ei voi peruuttaa.',
      deleteRepository: 'Poista data-arkisto',
    },
    schema: {
      schema: 'Rakenne',
      noSchema: 'Ei rakennetta saatavilla',
    },
  },
  connections: {
    connection: 'Yhteys',
    connections: 'Yhteydet',
    settings: {
      title: 'Yhteyden asetukset',
      saveChanges: 'Tallenna muutokset',
      deletionNote:
        'Poistamalla tämän yhteyden poistetaan kaikki siihen liittyvä data. Tätä toimintoa ei voi peruuttaa.',
      delete: 'Poista yhteys',
      areYouSureYouWantToDelete:
        'Oletko varma, että haluat poistaa tämän yhteyden?',
    },
    create: {
      selectConnector: 'Valitse yhdistin',
      establishConnection: 'Perusta yhteys',
      configureSettings: 'Määritä asetukset',
      configureConnection: 'Määritä yhteys',
      createNewConnection: 'Luo uusi yhteys',
      pleaseSelectConnector: 'Valitse yhdistin jatkaaksesi',
      confirmConnectorSelection: 'Vahvista yhdistimen valinta ja jatka',
      selectedConnector: 'Valittu yhdistin',
      categoryAll: 'Kaikki',
      connectionName: 'Yhteyden nimi',
      connectionNamePlaceholder: 'esim. Minun Google Analytics -yhteys',
      connectionDescription: 'Yhteyden kuvaus',
      connectionDescriptionPlaceholder:
        'Kirjoita kuvaus yhteydelle, jotta muut tietävät, mihin sitä käytetään',
      addCustomConnector: 'Lisää oma yhdistin',
      continueAndTest: 'Jatka ja testaa yhteys',
      createConnection: 'Luo yhteys',
      continue: 'Jatka',
      goBack: 'Mene takaisin',
      success: 'Yhteys onnistui',
      failed: 'Yhteys epäonnistui',
      configuration_valid: 'Yhteyden konfiguraatio on validi',
      configuration_invalid: 'Yhteyden konfiguraatio on virheellinen',
      contactSupport: 'Ota yhteyttä tukeen',
      requiredFieldsMissing: 'Pakollisia kenttiä puuttuu',
    },
  },

  connectors: {
    connector: 'Yhdistin',
    connectors: 'Yhdistimet',
    version: 'Versio',
    author: 'Tekijä',
    authorEmail: 'Tekijän sähköposti',
    categories: 'Kategoriat',
    capabilities: 'Toiminallisuudet',
    locales: 'Kielet',
  },

  // === WORKFLOWS ===
  workflow: {
    workflows: 'Prosessit',
    importWorkflows: 'Tuontiprosessit',
    actionWorkflows: 'Toimintoprosessit',
    exportWorkflows: 'Vientiprosessit',
    pipelineWorkflows: 'Dataputkiprosessit',
    actions: 'Toiminnot',
    imports: 'Tuonnit',
    exports: 'Viennit',
    pipelines: 'Dataputket',
    triggerRun: 'Käynnistä ajo',
    triggeringRun: 'Käynnistetään ajoa',
    workflow: 'Prosessi',
    import: 'Tuonti',
    action: 'Toiminto',
    export: 'Vienti',
    run: 'Ajo',
    noStatus: 'Ei statusta',
    startedAt: 'Aloitettu',
    finishedAt: 'Valmis',
    scheduled: 'Aikataulutettu',
    notScheduled: 'Ei aikataulutettu',
    openInEditor: 'Avaa editorissa',
    executableScriptFile: 'Suoritettava skriptitiedosto',
    scriptInputData: 'Syötteet',
    scriptInputFiles: {
      title: 'Skriptin syötetiedostot',
      inputFile: 'Syötetiedosto',
      addInputFile: 'Lisää syötetiedosto',
      path: 'Polku',
      save: 'Tallenna syötetiedostot',
    },
    scriptResultDestinationRepository: 'Tuloksen data-arkisto',
    scriptResultDestinationBranch: 'Tuloksen haara',
    scriptResultDestinationPath: 'Tuloksen polku',
    importSourceConnection: 'Tuonnin lähdeyhteys',
    importSourceConnectionPath: 'Tuonnin lähdeyhteyden polku',
    importDestinationRepository: 'Tuonnin kohdedata-arkisto',
    importDestinationBranch: 'Tuonnin kohdehaara',
    importDestinationPath: 'Tuonnin kohdepolku',
    exportDestinationConnection: 'Viennin kohdeyhteys',
    exportDestinationConnectionPath: 'Viennin kohdeyhteyden polku',
    exportSourceRepository: 'Vientilähteen data-arkisto',
    exportSourceBranch: 'Vientilähteen haara',
    exportSourcePath: 'Vientilähteen polku',
    livePipeline: 'Live-dataputki',
    triggeredBy: 'Laukaisija',
    duration: 'Kesto',
    // New translations for MultiplePathsSelector
    addPath: 'Lisää polku',
    removePath: 'Poista polku',
    multiplePaths: 'Useita polkuja',
    tabs: {
      data: 'Data',
      schedule: 'Aikataulu',
    },
    settings: {
      saveChanges: 'Tallenna muutokset',
      deletionNote:
        'Poistamalla tämän prosessin poistetaan kaikki siihen liittyvä data. Tätä toimintoa ei voi peruuttaa.',
      delete: 'Poista prosessi',
      areYouSureYouWantToDelete:
        'Oletko varma, että haluat poistaa tämän prosessin?',
      resumeWorkflow: 'Jatka',
      pauseWorkflow: 'Pysäytä',
    },
    create: {
      createNewWorkflow: 'Luo uusi prosessi',
      createNewActionWorkflow: 'Luo uusi toimintoprosessi',
      createNewImportWorkflow: 'Luo uusi tuontiprosessi',
      createNewExportWorkflow: 'Luo uusi vientiprosessi',
      createNewPipelineWorkflow: 'Luo uusi dataputkiprosessi',
      configureFieldMappings: 'Määritä kenttien kartoitus',
      configureImport: 'Määritä tuonti',
      configureAction: 'Määritä toiminto',
      configureExport: 'Määritä vienti',
      configurePipeline: 'Määritä dataputki',
      configureWorkflow: 'Määritä prosessi',
      confirmAndCreate: 'Vahvista ja luo',
      confirmAndContinue: 'Vahvista ja jatka',
      goBack: 'Mene takaisin',
    },
    pipeline: {
      pipeline: 'Dataputki',
      livePipeline: 'Live-dataputki',
      addNewStage: 'Lisää uusi vaihe',
      addStage: 'Lisää vaihe',
      stage: 'Vaihe',
      descriptionPlaceholder: 'Kuvaile, mitä tämä dataputken vaihe tekee',
      write: 'Kirjoita',
      read: 'Lue',
      executablePath: 'Suoritettava polku',
      executablePathDescription:
        'Polku suoritettavaan skriptiin (esim. /path/to/script.py)',
      connectionWritePath: 'Kirjoittamisen polku',
      connectionWritePathDescription:
        'Polku, johon data kirjoitetaan (esim. /path/to/write)',
      connectionReadPath: 'Lukupolku',
      connectionReadPathDescription:
        'Polku, josta data luetaan (esim. /path/to/read)',
      moveUp: 'Siirrä ylös',
      moveDown: 'Siirrä alas',
      savePipelineStages: 'Tallenna vaiheet',
      noStages: 'Ei vaiheita',
    },
    schedule: {
      workflowSchedule: 'Prosessin aikataulu',
      frequency: 'Usein toistuva?',
      interval: 'Väli',
      weekdays: 'Viikonpäivät',
      trigger: 'Laukaisin',
      triggers: 'Laukaisimet',
      timeTrigger: 'Aikapohjainen laukaisin',
      repositoryEventTrigger: 'Data-arkiston tapahtumalaukaisin',
      workflowRunEventTrigger: 'Prosessin ajotapahtuma-laukaisin',
      addTrigger: 'Lisää laukaisin',
      maxRetries: 'Enimmäisyritykset',
      maxRuntime: 'Maksimiaika (sekunteina)',
      minInterval: 'Minimiaika (sekunteina)',
      triggerType: 'Laukaisimen tyyppi',
      timeFormat: 'Aikamuoto',
      recurrenceRule: 'Toistumissääntö',
      cronExpression: 'Cron-lauseke',
      event: 'Tapahtuma',
      saveSchedule: 'Tallenna aikataulu',
      presets: 'Pohjat',
      custom: 'Mukautettu',
      cron: {
        selectPreset: 'Valitse aikataulupohja',
        generatedCron: 'Luotu Cron-lauseke',
        nextExecutionTimes: 'Seuraavat suoritusajat',
        invalidCron: 'Virheellinen cron-lauseke. Tarkista syntaksi.',
        minutes: 'Minuutit',
        hours: 'Tunnit',
        dayOfMonth: 'Kuukauden päivä',
        month: 'Kuukausi',
        dayOfWeek: 'Viikonpäivä',
        everyMinute: 'Joka minuutti (*)',
        everyHour: 'Joka tunti (*)',
        everyDay: 'Joka päivä (*)',
        everyMonth: 'Joka kuukausi (*)',
        everyWeekday: 'Joka päivä (*)',
        specificMinute: 'Tietty minuutti',
        specificHour: 'Tietty tunti',
        specificDay: 'Tietty päivä',
        specificMonth: 'Tietty kuukausi',
        specificWeekday: 'Tietty viikonpäivä',
        cronSyntax: 'Cron-syntaksi',
        cronSyntaxDescription: 'Cron-lauseke koostuu 5 kentästä:',
        cronSyntaxNote: '* = mikä tahansa arvo, 0 = sunnuntai viikonpäivälle',
        copyToClipboard: 'Kopioi leikepöydälle',
        copied: 'Kopioitu!',
        copyCron: 'Kopioi cron-lauseke',
        cronSyntaxHelp: 'Cron-syntaksin ohje',
      },
      rrule: {
        selectPreset: 'Valitse esiasetettu aikataulu',
        generatedRRule: 'Luotu RRule',
        nextExecutionTimes: 'Seuraavat ajat',
        invalidRRule: 'Virheellinen RRule. Tarkista asetukset.',
        frequency: 'Toistuvuus',
        interval: 'Väli',
        weekdays: 'Viikonpäivät',
        startDate: 'Aloituspäivä',
        none: 'Ei mitään',
        everyDay: 'Joka päivä',
        selected: 'valittu',
        rruleSyntax: 'Toistumissäännön syntaksi',
        rruleSyntaxDescription:
          'Toistumissääntö (RRule) on standardoitu muoto toistuvien tapahtumien määrittelyyn. Yleisimmät vaihtoehdot:',
        rruleSyntaxOptions: {
          freq: 'FREQ: Toistuvuus (SECONDLY, MINUTELY, HOURLY, DAILY, WEEKLY, MONTHLY, YEARLY)',
          interval: 'INTERVAL: Toistuvuuden väli',
          byday: 'BYDAY: Viikonpäivät (MO, TU, WE, TH, FR, SA, SU)',
          byhour: 'BYHOUR: Päivän tunnit (0-23)',
          byminute: 'BYMINUTE: Tunnin minuutit (0-59)',
        },
        copyToClipboard: 'Kopioi leikepöydälle',
        copied: 'Kopioitu!',
        copyRRule: 'Kopioi toistumissääntö',
        rruleSyntaxHelp: 'Toistumissäännön syntaksin ohje',
      },
    },
  },

  // === DEVELOPMENT TOOLS ===
  editor: {
    writeYourJS: 'Kirjoita JavaScriptisi tähän...',
    writeYourGo: 'Kirjoita Go-skriptisi tähän...',
    writeYourSQL: 'Kirjoita SQL-kyselysi tähän...',
    writeYourPython: 'Kirjoita Python-koodisi tähän...',
    writeYourText: 'Kirjoita teksti tähän...',
    writeYourMarkdown: 'Kirjoita Markdown-tekstisi tähän...',
    writeYourJSON: 'Kirjoita JSON-objektisi tähän...',
    newScriptTitle: 'Luo uusi skripti',
    newScriptSubtitle:
      'Kirjoita skripti haluamallasi kielellä ja tallenna se prosessina',
    scriptExecutionStarted: 'Skriptin suoritus aloitettu',
    scriptNeedsToBeSaved:
      'Skripti on tallennettava ennen suorittamista. Tallenna skripti editoriin ja suorita se uudelleen.',
  },

  query: {
    queryExecutionStarted: 'Kyselyn suoritus aloitettu',
    results: 'Tulokset',
    errors: 'Virheet',
    noErrors: 'Ei virheitä',
    queryResults: 'Kyselyn tulokset',
    createQuery: 'Luo kysely',
    saveAsWorkflow: 'Tallenna prosessina',
    run: 'Suorita',
    rowsReturnedIn: 'riviä palautettu ajassa',
    exportTable: 'vie taulukko (.csv)',
    search: 'Hae tuloksista',
    newQuery: 'Uusi kysely',
    selectedQuery: 'Valittu kysely',
  },

  fileNavigator: {
    original: 'Alkuperäinen',
    saveFile: 'Tallenna tiedosto',
    createFile: 'Luo tiedosto',
    createFolder: 'Luo kansio',
    updateFile: 'Päivitä tiedosto',
    updateFolder: 'Päivitä kansio',
    copyFolder: 'Kopioi kansio',
    copyFile: 'Kopioi tiedosto',
    open: 'Avaa',
    rename: 'Nimeä uudelleen',
    move: 'Siirrä',
    root: 'Juuri',
    rootDirectory: 'Juurihakemisto',
    newNameOfTheFile: 'Tiedoston uusi nimi',
    newNameOfTheFolder: 'Kansion uusi nimi',
    newPathOfTheFile: 'Tiedoston uusi polku',
    newPathOfTheFolder: 'Kansion uusi polku',
    newFileName: 'Uuden tiedoston nimi',
    newFolderName: 'Uuden kansion nimi',
    newFilePath: 'Uuden tiedoston polku',
    newFolderPath: 'Uuden kansion polku',
    deleteConfirmation: 'Oletko varma, että haluat poistaa',
    deleteFolderWarning:
      'Kaikki tämän kansion tiedostot ja alikansiot poistetaan',

    errors: {
      invalidType: 'Virheellinen tyyppi (tiedosto tai kansio)',
      noExtension: 'Tiedoston pääte puuttuu tai on virheellinen',
      invalidExtension: 'Virheellinen tiedostopääte (js, py, sql)',
      emptyName: 'Nimi ei voi olla tyhjä',
      longName: 'Nimi on liian pitkä',
      invalidName: 'Virheellinen nimi',
      invalidPath: 'Virheellinen polku',
      pathExists: 'Polku on jo olemassa',
      parentPathNotExist: 'Yläkansiota ei ole olemassa',
    },
  },

  // === USER MANAGEMENT ===
  users: {
    removeUserConfirmation:
      'Oletko varma, että haluat poistaa tämän käyttäjän?',
    transferOwnershipConfirmation:
      'Oletko varma, että haluat siirtää omistajuuden?',
    usersAndPermissions: 'Käyttäjät ja oikeudet',
    invites: 'Kutsut työtilaan',
    inviteUser: 'Kutsu käyttäjä',
    changeProfilePicture: 'Vaihda profiilikuva',
    firstName: 'Etunimi',
    lastName: 'Sukunimi',
    email: 'Sähköposti',
    phone: 'Puhelinnumero',
    company: 'Yritys',
    role: 'Rooli',
    noRole: 'Ei roolia',
    updateProfile: 'Päivitä profiili',
    transferOwnership: 'Siirrä omistajuus',
    removeFromWorkspace: 'Poista työtilasta',
    resendInvite: 'Lähetä kutsu uudelleen',
    cancelInvite: 'Peruuta kutsu',
    invite: 'Kutsu',
  },

  invite: {
    acceptInvitation: 'Hyväksy kutsu',
    declineInvitation: 'Hylkää kutsu',
    workspaceInvitation: 'Kutsu työtilaan',
    workspaceInvitationDescription: 'Sinut on kutsuttu liittymään työtilaan',
    invitedBy: 'Kutsuja',
    workspace: 'Työtila',
    role: 'Rooli',
  },

  tokens: {
    apiTokens: 'API avaimet',
    noTokens: 'Sinulla ei ole vielä luotuja API avaimia',
    createAPIToken: 'Luo API avain',
    validFor: 'Voimassa (sekunneissa)',
    expiresAt: 'Vanhenee',
    revokeToken: 'Poista avain',
    yourAPIToken: 'Sinun API avain',
    storeTokenDescription:
      'Tämä avain näytetään vain kerran. Ole hyvä ja kopio se, sekä säilytä turvallisesti.',
    tokenRevealed: 'Avain näytetty',
    revealToken: 'Näytä avain',
    copied: 'Kopioitu!',
    copyToken: 'Kopioi avain',
  },

  policy: {
    title: 'Käyttöoikeudet',
    description: 'Hallitse käyttöoikeuksia ja käyttöoikeuksia',
    addPolicy: 'Lisää käyttöoikeus',
    createPolicy: 'Luo uusi käyttöoikeus',
    createPolicyDescription: 'Määritä uusi käyttöoikeus työtilallesi',
    editPolicy: 'Muokkaa käyttöoikeutta',
    editPolicyDescription: 'Muokkaa käyttöoikeuden asetuksia',
    deletePolicy: 'Poista käyttöoikeus',
    deletePolicyDescription:
      'Haluatko varmasti poistaa tämän käyttöoikeuden? Tätä toimintoa ei voi peruuttaa.',
    effect: 'Vaikutus',
    action: 'Toiminto',
    resource: 'Resurssi',
    principal: 'Kohde',
    resourceId: 'Resurssin tunniste (valinnainen)',
    resourceIdPlaceholder: 'Jätä tyhjäksi kaikille resursseille',
    loading: 'Ladataan käyttöoikeuksia...',
    error: 'Virhe käyttöoikeuksien lataamisessa',
    noPolicies: 'Ei käyttöoikeuksia',
    creating: 'Luodaan...',
    updating: 'Päivitetään...',
    deleting: 'Poistetaan...',
    effectAllow: 'Salli',
    effectDeny: 'Estä',
    actionRead: 'Lue',
    actionCreate: 'Luo',
    actionUpdate: 'Päivitä',
    actionDelete: 'Poista',
    principalWorkspaceUser: 'Käyttäjä',
    principalRole: 'Rooli',
    principalEveryone: 'Kaikki',
    allResources: 'Kaikki',

    tooltips: {
      effect: 'Onko käyttöoikeus eksplisiittisesti estävä vai salliva',
      action:
        'Mikä toiminto on sallittu tai estetty (luonti, lukeminen, päivitys, poisto)',
      resource: 'Resurssin tyyppi, jolle toiminto koskee',
      principal:
        'Kenelle käyttöoikeus koskee (tietty käyttäjä, rooli tai kaikki)',
      resourceId:
        'Valinnainen tietyn resurssin tunniste. Jätä tyhjäksi koskemaan kaikkia tämän tyyppisiä resursseja',
    },
  },

  // === LOGGING & MONITORING ===
  logs: {
    workspaceLogs: 'Työtilan audit lokit',
    connectionLogs: 'Yhteyden audit lokit',
    repositoryLogs: 'Data-arkiston audit lokit',
    userAuditLogs: 'Käyttäjän audit lokit',
    workflowLogs: 'Prosessin audit lokit',
    noLogsFound: 'Ei lokeja löytynyt',
    system: 'Järjestelmä',
    foundLogEvents: 'Lokitapahtumia löytyi',
    storedQueryLogs: 'Kyselyn audit lokit',
    policyLogs: 'Käyttöoikeuden audit lokit',
    repositoryObjectLogs: 'Data-arkiston objektin audit lokit',
  },

  // === DOCUMENTATION ===
  documentation: {
    documentation: 'Dokumentaatio',
    startTypingDocumentation:
      'Aloita dokumentaation ja muistiinpanojen kirjoittaminen tähän...',
    schema: 'Rakenne',
    workspace: 'Työtila',
    createdBy: 'Luonut',
  },

  // === LIST COMPONENTS ===
  list: {
    status: 'Tila',
    runs: 'Ajot',
    actions: 'Toiminnot',
    view: 'Katso',
    delete: 'Poista',
    edit: 'Muokkaa',
    owner: 'Omistaja',
    author: 'Luoja',
    lastUpdated: 'Päivitetty',
    createdAt: 'Luotu',
    immutable: 'Muuttumaton',
    source: 'Lähde',
    destination: 'Kohde',
    searchPlaceholder: 'Kirjoita hakusana...',
    noItemsFound: 'Ei kohteita',
    emptyState: {
      repositories: {
        title: 'Ei vielä repositorioita',
        description:
          'Repositoriot tallentavat datasi Git-tyylisessä rakenteessa. Luo ensimmäinen repositorio aloittaaksesi.',
      },
      workflows: {
        title: 'Ei vielä työnkulkuja',
        description:
          'Työnkulut automatisoivat data-tehtäviäsi. Luo tuonti-, vienti-, toiminto- tai putki-työnkulkuja aloittaaksesi.',
      },
      connections: {
        title: 'Ei vielä yhteyksiä',
        description:
          'Yhteydet mahdollistavat tuonnin ja viennin ulkoisista tietolähteistä. Luo ensimmäinen yhteys aloittaaksesi.',
      },
      users: {
        title: 'Ei vielä käyttäjiä',
        description: 'Kutsu tiimin jäseniä yhteistyöhön tässä työtilassa.',
      },
      invites: {
        title: 'Ei odottavia kutsuja',
        description:
          'Kun kutsut ihmisiä tähän työtilaan, he näkyvät täällä kunnes hyväksyvät tai hylkäävät kutsun.',
      },
      queries: {
        title: 'Ei tallennettuja kyselyjä',
        description:
          'Aloita kirjoittamalla SQL-kysely editorissa ja tallenna se tulevaa käyttöä varten.',
      },
      tokens: {
        title: 'Ei API-tunnuksia',
        description:
          'API-tunnukset mahdollistavat ohjelmoitavan autentikoinnin Irmin API:n kanssa. Luo ensimmäinen tunnus aloittaaksesi.',
      },
      commits: {
        title: 'Ei vielä committeja',
        description:
          'Aloita tekemällä muutoksia repositorioosi nähdäksesi commitit täällä.',
      },
      tags: {
        title: 'Ei vielä tageja',
        description:
          'Tagit ovat muuttumattomia osoittimia tiettyihin committeihin. Luo tageja merkitäksesi tärkeitä versioita.',
      },
      branches: {
        title: 'Ei vielä haaroja',
        description:
          'Haarat mahdollistavat datasi eri versioiden käsittelyn samanaikaisesti.',
      },
      objects: {
        title: 'Ei vielä objekteja',
        description:
          'Aloita lataamalla tiedostoja tai luo työnkulku täyttääksesi tämän repositorion.',
      },
      generic: {
        title: 'Kohteita ei löytynyt',
        description:
          'Yritä muuttaa hakuehtojasi tai suodattimiasi löytääksesi etsimäsi.',
      },
    },
  },

  // === UTILITIES ===
  schemaFieldMapper: {
    title: 'Kenttien yhdistäminen',
    description:
      'Klikkaa lähdekenttää, sitten kohdekenttää luodaksesi yhdistämisen',
    descriptionWithSelection:
      'Klikkaa kohdekenttää yhdistääksesi "{fieldName}" lähteestä {source}',
    sourceSchema: 'Lähderakenne',
    destinationSchema: 'Kohderakenne',
    fieldMappings: 'Kenttien yhdistämiset',
    noMappingsYet: 'Ei vielä yhdistämisiä',
    autoMapIdenticalFields: 'Yhdistä samat kentät automaattisesti',
    clearAllMappings: 'Tyhjennä kaikki yhdistämiset',
    fields: 'kenttää',
    mapped: 'yhdistetty',
    required: 'pakollinen',
    fileSize: '{size}KB',
    autoMappedSuccess: 'Yhdistetty {count} samaa kenttää automaattisesti!',
    noIdenticalFieldsFound: 'Ei samankaltaisia kenttiä yhdistettäväksi.',
    sourceEmpty: 'Lähde on tyhjä - ei kenttiä yhdistettäväksi',
    destinationEmpty: 'Kohde on tyhjä - mitään ei tarvitse korvata',
  },
};

export default fi;
