name: Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
permissions:
  contents: write
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Prettier
        run: pnpm format:fix
      - name: ESLint
        run: pnpm lint
      - name: Build
        run: |
          pnpm build | tee build-log.txt
      - name: Check Build Status
        run: |
          if grep -q "error" build-log.txt; then
            echo "Build failed. Please fix the build errors and try again."
            exit 1
          fi
      - name: PR Comment (Success)
        if: success()
        run: |
          echo "Build succeeded. PR is allowed to be created."
          # You can use GitHub API to post a comment on the PR here if you want.
      - name: PR Comment (Failure)
        if: failure()
        run: |
          echo "Build failed. Please fix the build errors and try again."
          # You can use GitHub API to post a comment on the PR here if you want.
