import { CollectionRow } from '@/types/internal/Collection';

/**
 * Example data for a collection of rows.
 */
export const exampleCollectionData: CollectionRow[] = [
  {
    name: 'John Doe',
    age: 25,
    city: 'New York',
    country: 'USA',
    email: 'johndoe@example.com',
    jobTitle: 'Software Engineer',
    company: 'TechCorp',
    isActive: true,
  },
  {
    name: 'Jane Doe',
    age: 26,
    city: 'Toronto',
    country: 'Canada',
    email: 'janedoe@example.com',
    jobTitle: 'Product Manager',
    company: 'Innovatech',
    isActive: false,
  },
  {
    name: 'John Smith',
    age: 30,
    city: 'London',
    country: 'UK',
    email: 'johnsmith@example.com',
    jobTitle: 'Data Analyst',
    company: 'DataSolve',
    isActive: true,
  },
  {
    name: 'Jane Smith',
    age: 22,
    city: 'Paris',
    country: 'France',
    email: 'janesmith@example.com',
    jobTitle: 'Graphic Designer',
    company: 'DesignHub',
    isActive: false,
  },
  {
    name: 'John Johnson',
    age: 28,
    city: 'Berlin',
    country: 'Germany',
    email: 'johnjohnson@example.com',
    jobTitle: 'DevOps Engineer',
    company: 'CloudBase',
    isActive: true,
  },
  {
    name: 'Jane Johnson',
    age: 29,
    city: 'Tokyo',
    country: 'Japan',
    email: 'janejohnson@example.com',
    jobTitle: 'UX Researcher',
    company: 'UserFirst',
    isActive: false,
  },
  {
    name: 'John Williams',
    age: 27,
    city: 'Sydney',
    country: 'Australia',
    email: 'johnwilliams@example.com',
    jobTitle: 'Accountant',
    company: 'FinancePro',
    isActive: true,
  },
  {
    name: 'Jane Williams',
    age: 24,
    city: 'Cape Town',
    country: 'South Africa',
    email: 'janewilliams@example.com',
    jobTitle: 'Marketing Specialist',
    company: 'BrandMakers',
    isActive: false,
  },
  {
    name: 'John Brown',
    age: 23,
    city: 'Rio de Janeiro',
    country: 'Brazil',
    email: 'johnbrown@example.com',
    jobTitle: 'Sales Manager',
    company: 'SalesForce',
    isActive: true,
  },
  {
    name: 'Jane Brown',
    age: 31,
    city: 'Moscow',
    country: 'Russia',
    email: 'janebrown@example.com',
    jobTitle: 'HR Coordinator',
    company: 'PeopleOps',
    isActive: false,
  },
  {
    name: 'John Davis',
    age: 33,
    city: 'Beijing',
    country: 'China',
    email: 'johndavis@example.com',
    jobTitle: 'Business Analyst',
    company: 'BizInsights',
    isActive: true,
  },
  {
    name: 'Jane Davis',
    age: 32,
    city: 'New Delhi',
    country: 'India',
    email: 'janedavis@example.com',
    jobTitle: 'Consultant',
    company: 'AdvisoryCo',
    isActive: false,
  },
  {
    name: 'John Miller',
    age: 34,
    city: 'Seoul',
    country: 'South Korea',
    email: 'johnmiller@example.com',
    jobTitle: 'Project Manager',
    company: 'PM Solutions',
    isActive: true,
  },
  {
    name: 'Jane Miller',
    age: 35,
    city: 'Cairo',
    country: 'Egypt',
    email: 'janemiller@example.com',
    jobTitle: 'Architect',
    company: 'UrbanBuild',
    isActive: false,
  },
  {
    name: 'John Wilson',
    age: 36,
    city: 'Cape Town',
    country: 'South Africa',
    email: 'johnwilson@example.com',
    jobTitle: 'Research Scientist',
    company: 'LabWorks',
    isActive: true,
  },
  {
    name: 'Jane Wilson',
    age: 37,
    city: 'Lagos',
    country: 'Nigeria',
    email: 'janewilson@example.com',
    jobTitle: 'Financial Analyst',
    company: 'FinAdvisors',
    isActive: false,
  },
  {
    name: 'John Moore',
    age: 38,
    city: 'Mexico City',
    country: 'Mexico',
    email: 'johnmoore@example.com',
    jobTitle: 'Operations Manager',
    company: 'GlobalOps',
    isActive: true,
  },
  {
    name: 'Jane Moore',
    age: 39,
    city: 'Buenos Aires',
    country: 'Argentina',
    email: 'janemoore@example.com',
    jobTitle: 'Content Strategist',
    company: 'MediaHouse',
    isActive: false,
  },
  {
    name: 'John Taylor',
    age: 40,
    city: 'Santiago',
    country: 'Chile',
    email: 'johntaylor@example.com',
    jobTitle: 'Engineer',
    company: 'BuildTech',
    isActive: true,
  },
  {
    name: 'Jane Taylor',
    age: 41,
    city: 'Helsinki',
    country: 'Finland',
    email: 'janetaylor@example.com',
    jobTitle: 'Legal Advisor',
    company: 'LawFirm',
    isActive: false,
  },
];
