import { db, messages } from '@/database';
import { and, desc, eq, sql } from 'drizzle-orm';

import { systemPromptBuilder } from '@/services/systemPromptBuilder';

import type { User } from '@/irmin-api/types/user';
import type { Workspace } from '@/irmin-api/types/workspace';

interface SystemPromptContext {
  user?: User;
  workspace?: Workspace;
  conversationId?: string;
  agentId?: string;
  customContext?: Record<string, unknown>;
  maxUserInputChars?: number;
  maxSystemPromptChars?: number;
}

class SystemMessageCacheService {
  /**
   * Get or create a system message for a conversation
   * System messages are created once per conversation and stored as regular
   * messages.
   * Uses PostgreSQL advisory locks to prevent race conditions across all
   * instances.
   */
  async getOrCreateSystemMessage(
    conversationId: string,
    basePrompt: string | null,
    context: SystemPromptContext
  ): Promise<string | null> {
    // Validate conversationId to prevent cache collisions
    if (!conversationId || conversationId.trim() === '') {
      throw new Error(
        'ConversationId cannot be empty or null for system message cache'
      );
    }

    // Use a transaction with advisory lock to ensure atomicity across all
    // instances
    return await db.transaction(async (tx) => {
      // Acquire PostgreSQL advisory lock for this conversation via a stable
      // 64-bit hash generated by Postgres itself.
      // This serializes access across all application instances.
      await tx.execute(
        sql`SELECT pg_advisory_xact_lock(hashtextextended(${conversationId}, 0))`
      );

      // Check if conversation already has a system message
      const existingSystemMessage = await tx
        .select()
        .from(messages)
        .where(
          and(
            eq(messages.conversationId, conversationId),
            eq(messages.role, 'system')
          )
        )
        .orderBy(desc(messages.createdAt))
        .limit(1);

      if (existingSystemMessage.length > 0) {
        // Return existing system message content
        return existingSystemMessage[0].content;
      }

      // Create new system message (only happens once per conversation)
      // System prompt builder already handles length limits and context
      // sanitization
      const systemPrompt = systemPromptBuilder.buildSystemPrompt(
        basePrompt,
        context
      );

      // Store as a system message in the conversation
      const systemMessage = {
        id: `system-${conversationId}-${Date.now()}`,
        conversationId,
        role: 'system' as const,
        content: systemPrompt, // Already processed by systemPromptBuilder
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      await tx.insert(messages).values(systemMessage);

      return systemPrompt;
    });
  }

  /**
   * Check if a conversation already has a system message
   */
  async hasSystemMessage(conversationId: string): Promise<boolean> {
    // Validate conversationId to prevent cache collisions
    if (!conversationId || conversationId.trim() === '') {
      throw new Error(
        'ConversationId cannot be empty or null for system message cache'
      );
    }
    const systemMessage = await db
      .select({ id: messages.id })
      .from(messages)
      .where(
        and(
          eq(messages.conversationId, conversationId),
          eq(messages.role, 'system')
        )
      )
      .limit(1);

    return systemMessage.length > 0;
  }

  /**
   * Get existing system message content
   */
  async getSystemMessage(conversationId: string): Promise<string | null> {
    // Validate conversationId to prevent cache collisions
    if (!conversationId || conversationId.trim() === '') {
      throw new Error(
        'ConversationId cannot be empty or null for system message cache'
      );
    }
    const systemMessage = await db
      .select({ content: messages.content })
      .from(messages)
      .where(
        and(
          eq(messages.conversationId, conversationId),
          eq(messages.role, 'system')
        )
      )
      .orderBy(desc(messages.createdAt))
      .limit(1);

    return systemMessage.length > 0 ? systemMessage[0].content : null;
  }
}

// Export singleton instance
export const systemMessageCacheService = new SystemMessageCacheService();
