import { conversations, db } from '@/database';
import { eq } from 'drizzle-orm';

import { analyticsService } from './analytics';
import { completionService } from './completion';

interface TitleGenerationOptions {
  message: string;
  authToken: string;
  user: { id: string };
  workspace: { slug: string };
  conversationId?: string;
}

interface TitleGenerationResult {
  title: string;
  generated: boolean; // true if generated by AI, false if fallback
}

class TitleGenerationService {
  private readonly titleGenerationPrompt = `You are a title generator utility.

Instructions
- Input: a user prompt, the first message in the conversation.
- Output: a short, descriptive conversation title.
- Constraints:
  - Max 50 characters.
  - No quotes, punctuation at ends, or extra text.
  - Title case or concise noun phrase is fine.
  - Return only the title.`;

  constructor() {
    // No need for any initialization
  }

  /**
   * Generates a title for a conversation using direct LLM completion
   */
  async generateTitle(
    options: TitleGenerationOptions
  ): Promise<TitleGenerationResult> {
    const { message, authToken } = options;

    // Create fallback title
    const fallbackTitle = this.createFallbackTitle(message);

    try {
      // Create a simple prompt for title generation
      const titlePrompt = `${this.titleGenerationPrompt}

User message: ${message}

Title:`;

      const response = await completionService.createResponse({
        messages: [],
        provider: 'groq',
        model: 'llama-3.1-8b-instant',
        temperature: 0.7,
        maxTokens: 50,
        systemPrompt: titlePrompt,
        authToken,
      });

      let generatedTitle = response.content.trim();

      // Clean up the generated title
      generatedTitle = this.cleanTitle(generatedTitle);

      // Validate the generated title
      if (this.isValidTitle(generatedTitle)) {
        return {
          title: generatedTitle,
          generated: true,
        };
      } else {
        console.warn(
          'Generated title is invalid, using fallback:',
          generatedTitle
        );
        return {
          title: fallbackTitle,
          generated: false,
        };
      }
    } catch (error) {
      console.error('Failed to generate title:', error);

      // Log analytics for title generation failure
      if (options.conversationId) {
        await analyticsService.logError(
          'title_generation_failed',
          error instanceof Error ? error.message : 'Unknown error',
          options.conversationId
        );
      }

      return {
        title: fallbackTitle,
        generated: false,
      };
    }
  }

  /**
   * Updates a conversation title if it's still using a fallback/default title
   */
  async updateConversationTitleIfNeeded(
    conversationId: string,
    options: Omit<TitleGenerationOptions, 'conversationId'>
  ): Promise<boolean> {
    try {
      // Get the current conversation
      const conversation = await db
        .select()
        .from(conversations)
        .where(eq(conversations.id, conversationId))
        .limit(1);

      if (!conversation.length) {
        return false;
      }

      const currentTitle = conversation[0].title;

      // Check if the title looks like a fallback/default title
      if (!this.shouldUpdateTitle(currentTitle)) {
        return false;
      }

      // Generate new title
      const result = await this.generateTitle({
        ...options,
        conversationId,
      });

      // Only update if we got a generated title (not fallback)
      if (result.generated) {
        await db
          .update(conversations)
          .set({
            title: result.title,
            updatedAt: new Date(),
          })
          .where(eq(conversations.id, conversationId));

        // Log analytics for successful title update
        await analyticsService.logCustomEvent({
          eventType: 'conversation_updated',
          conversationId,
          eventData: {
            titleUpdated: true,
            oldTitle: currentTitle,
            newTitle: result.title,
            automated: true,
          },
        });

        return true;
      }

      return false;
    } catch (error) {
      console.error('Failed to update conversation title:', error);
      return false;
    }
  }

  /**
   * Creates a fallback title from the message
   */
  private createFallbackTitle(message: string): string {
    const maxLength = 50;
    const cleaned = message.trim();

    if (cleaned.length <= maxLength) {
      return cleaned;
    }

    return cleaned.substring(0, maxLength - 3) + '...';
  }

  /**
   * Cleans and normalizes a generated title
   */
  private cleanTitle(title: string): string {
    // Remove quotes and extra whitespace
    let cleaned = title
      .trim()
      .replace(/^["'`]+|["'`]+$/g, '') // Remove quotes at start/end
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim();

    // Limit length
    const maxLength = 50;
    if (cleaned.length > maxLength) {
      cleaned = cleaned.substring(0, maxLength - 3) + '...';
    }

    return cleaned;
  }

  /**
   * Validates if a generated title is acceptable
   */
  private isValidTitle(title: string): boolean {
    if (!title || title.length === 0) {
      return false;
    }

    // Check for obvious AI artifacts or refusals
    const lowerTitle = title.toLowerCase();
    const invalidPatterns = [
      'i cannot',
      "i can't",
      'sorry',
      'unable to',
      'as an ai',
      'as a language model',
      'no title',
      'untitled',
    ];

    return !invalidPatterns.some((pattern) => lowerTitle.includes(pattern));
  }

  /**
   * Determines if a conversation title should be updated
   */
  private shouldUpdateTitle(currentTitle: string): boolean {
    if (!currentTitle) {
      return true;
    }

    // Check for common fallback patterns
    const fallbackPatterns = [
      /^new conversation/i,
      /^\w+\.\.\.$/, // Short text ending with ...
      /^query generation:/i,
      /^script generation:/i,
      /^untitled/i,
    ];

    return fallbackPatterns.some((pattern) => pattern.test(currentTitle));
  }
}

export const titleGenerationService = new TitleGenerationService();
