import { conversations, db } from '@/database';
import { eq } from 'drizzle-orm';

import { getContentAsString } from '@/utils/getContentAsString';

import { analyticsService } from './analytics';
import { llmService } from './llm';

interface TitleGenerationOptions {
  message: string;
  user: { id: string };
  workspace: { slug: string };
  conversationId?: string;
  aiResponse?: string; // Optional AI response content to help generate better titles
}

interface TitleGenerationResult {
  title: string;
  generated: boolean; // true if generated by AI, false if fallback
}

class TitleGenerationService {
  private readonly titleGenerationSystemPrompt = `You are a conversation title generator for Irmin, a data warehouse platform.

Your task is to create a concise, descriptive title for a conversation based on the user's message and optionally the AI's response.

Context about Irmin:
- Irmin is a data warehouse platform with repositories, workflows, connections, and stored queries
- Irmin repositories are NOT Git repositories - they are data versioning containers (like Git but for data)
- Connections are data source integrations (PostgreSQL, MySQL, S3, etc.)
- Workflows are data pipeline orchestrations

Rules:
- Create a title that summarizes the main topic or intent
- Maximum 50 characters
- Use title case or concise noun phrases
- Do NOT repeat the user's exact words
- Do NOT include quotes, punctuation at the end, or extra text
- Do NOT say "Title Generator" or similar meta-text
- Focus on the core subject matter
- If AI response is provided, use it to better understand the conversation context
- When user mentions "repositories", refer to data repositories, not Git

Examples:
- User: "How do I connect to my PostgreSQL database?"
- Title: "PostgreSQL Connection Setup"

- User: "What repositories do I have?"
- Title: "List Data Repositories"

- User: "Can you help me write a Python script to process CSV files?"
- AI Response: "I'll help you create a Python script using pandas to read and process CSV files..."
- Title: "Python CSV Processing Script"

- User: "How do I create a new workflow?"
- Title: "Workflow Creation Help"

Return only the title, nothing else.`;
  private readonly TITLE_GENERATION_TIMEOUT_MS = 15000;

  constructor() {
    // No need for any initialization
  }

  /**
   * Generates a title for a conversation using direct LLM completion
   */
  async generateTitle(
    options: TitleGenerationOptions
  ): Promise<TitleGenerationResult> {
    // Create fallback title
    const fallbackTitle = this.createFallbackTitle();

    try {
      // Build the prompt for title generation
      let titlePrompt = `User message: "${options.message}"`;

      if (options.aiResponse) {
        // Truncate AI response if too long to avoid token limits
        const truncatedResponse =
          options.aiResponse.length > 500
            ? options.aiResponse.substring(0, 500) + '...'
            : options.aiResponse;
        titlePrompt += `\n\nAI response: "${truncatedResponse}"`;
      }

      const llm = llmService.createLLM({
        provider: 'groq',
        model: 'llama-3.1-8b-instant',
        maxTokens: 500,
        streaming: false,
      });

      const logPrefix = options.conversationId
        ? `[TitleGeneration][conversation=${options.conversationId}]`
        : '[TitleGeneration][conversation=new]';

      console.log(`${logPrefix} Generating title...`);

      const response = await Promise.race([
        llm.invoke([
          {
            role: 'system',
            content: this.titleGenerationSystemPrompt,
          },
          {
            role: 'user',
            content: titlePrompt,
          },
        ]),
        new Promise<never>((_resolve, reject) =>
          setTimeout(
            () => reject(new Error('Hypothetical generation timeout')),
            this.TITLE_GENERATION_TIMEOUT_MS
          )
        ),
      ]);

      let generatedTitle = getContentAsString(response.content).trim();

      // Clean up the generated title
      generatedTitle = this.cleanTitle(generatedTitle);

      // Validate the generated title
      if (this.isValidTitle(generatedTitle)) {
        console.log(
          `${logPrefix} ✅ Generated title: "${generatedTitle.replace(/\n/g, ' ')}"`
        );
        return {
          title: generatedTitle,
          generated: true,
        };
      } else {
        console.warn(
          `${logPrefix} ⚠️ LLM returned invalid title: "${generatedTitle.replace(/\n/g, ' ')}"`
        );
        return {
          title: fallbackTitle,
          generated: false,
        };
      }
    } catch (error) {
      const logPrefix = options.conversationId
        ? `[TitleGeneration][conversation=${options.conversationId}]`
        : '[TitleGeneration][conversation=new]';
      console.error(`${logPrefix} ❌ Title generation failed:`, error);
      // Log analytics for title generation failure
      if (options.conversationId) {
        analyticsService.logEvent({
          eventType: 'title_generation_failed',
          conversationId: options.conversationId,
          eventData: {
            error: error instanceof Error ? error.message : 'Unknown error',
          },
        });
      }

      return {
        title: fallbackTitle,
        generated: false,
      };
    }
  }

  /**
   * Updates a conversation title if it's still using a fallback/default title
   */
  async updateConversationTitleIfNeeded(
    conversationId: string,
    options: Omit<TitleGenerationOptions, 'conversationId'>
  ): Promise<boolean> {
    try {
      // Get the current conversation
      const conversation = await db
        .select()
        .from(conversations)
        .where(eq(conversations.id, conversationId))
        .limit(1);

      if (!conversation.length) {
        console.log(
          `[TitleGeneration] ❌ Conversation ${conversationId} not found`
        );
        return false;
      }

      const currentTitle = conversation[0].title;
      console.log(`[TitleGeneration] Current title: "${currentTitle}"`);

      // Check if the title looks like a fallback/default title
      if (!this.shouldUpdateTitle(currentTitle)) {
        console.log(
          `[TitleGeneration] ✅ Title "${currentTitle}" doesn't need updating`
        );
        return false;
      }

      console.log(
        `[TitleGeneration] 🔄 Title "${currentTitle}" needs updating, generating new title...`
      );

      // Generate new title
      const result = await this.generateTitle({
        ...options,
        conversationId,
      });

      // Only update if we got a generated title (not fallback)
      if (result.generated) {
        console.log(
          `[TitleGeneration] ✅ Updating conversation ${conversationId} title from "${currentTitle}" to "${result.title}"`
        );

        await db
          .update(conversations)
          .set({
            title: result.title,
            updatedAt: new Date(),
          })
          .where(eq(conversations.id, conversationId));

        // Log analytics for successful title update
        analyticsService.logEvent({
          eventType: 'conversation_updated',
          conversationId,
          eventData: {
            titleUpdated: true,
            oldTitle: currentTitle,
            newTitle: result.title,
            automated: true,
          },
        });

        return true;
      } else {
        console.log(
          `[TitleGeneration] ❌ Title generation failed, keeping current title: "${currentTitle}"`
        );
      }

      return false;
    } catch (error) {
      console.error(
        `[TitleGeneration] ❌ Failed to update conversation title for ${conversationId}:`,
        error
      );
      return false;
    }
  }

  /**
   * Creates a fallback title
   */
  createFallbackTitle(): string {
    const timestamp = new Date().toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
    return `untitled - ${timestamp}`;
  }

  /**
   * Updates a conversation title using the user's message and optionally the AI's response
   * This should be called after the AI has responded to get a better title
   */
  async updateTitle(
    conversationId: string,
    userMessage: string,
    options: Omit<
      TitleGenerationOptions,
      'message' | 'conversationId' | 'aiResponse'
    >,
    aiResponse?: string
  ): Promise<boolean> {
    try {
      const hasAIResponse = Boolean(aiResponse);
      console.log(
        `[TitleGeneration][conversation=${conversationId}] Updating title (hasAIResponse=${hasAIResponse})`
      );

      const result = await this.generateTitle({
        message: userMessage,
        aiResponse,
        conversationId,
        ...options,
      });

      if (result.generated) {
        // Update the conversation title
        await db
          .update(conversations)
          .set({
            title: result.title,
            updatedAt: new Date(),
          })
          .where(eq(conversations.id, conversationId));

        // Log analytics for successful title update
        analyticsService.logEvent({
          eventType: 'conversation_updated',
          conversationId,
          eventData: {
            titleUpdated: true,
            newTitle: result.title,
            withAIResponse: aiResponse ? true : false,
          },
        });

        console.log(
          `[TitleGeneration][conversation=${conversationId}] ✅ Title updated to "${result.title}"`
        );

        return true;
      } else {
        console.warn(
          `[TitleGeneration][conversation=${conversationId}] ⚠️ Title generation returned fallback`
        );
        return false;
      }
    } catch (error) {
      console.error(
        `[TitleGeneration] ❌ Failed to update title without AI response for conversation ${conversationId}:`,
        error
      );
      return false;
    }
  }

  /**
   * Cleans and normalizes a generated title
   */
  private cleanTitle(title: string): string {
    // Remove quotes and extra whitespace
    let cleaned = title
      .trim()
      .replace(/^["'`]+|["'`]+$/g, '') // Remove quotes at start/end
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim();

    // Limit length
    const maxLength = 50;
    if (cleaned.length > maxLength) {
      cleaned = cleaned.substring(0, maxLength - 3) + '...';
    }

    return cleaned;
  }

  /**
   * Validates if a generated title is acceptable
   */
  private isValidTitle(title: string): boolean {
    if (!title || title.length === 0) {
      return false;
    }

    // Check for obvious AI artifacts or refusals
    const lowerTitle = title.toLowerCase();
    const invalidPatterns = [
      'i cannot',
      "i can't",
      'sorry',
      'unable to',
      'as an ai',
      'as a language model',
      'no title',
    ];

    return !invalidPatterns.some((pattern) => lowerTitle.includes(pattern));
  }

  /**
   * Determines if a conversation title should be updated
   */
  private shouldUpdateTitle(currentTitle: string): boolean {
    if (!currentTitle) {
      return true;
    }

    const lowerTitle = currentTitle.toLowerCase();

    // Check if title starts with common fallback patterns
    const fallbackPrefixes = [
      'untitled',
      'new conversation',
      'query generation:',
      'script generation:',
    ];

    const isFallback = fallbackPrefixes.some((prefix) =>
      lowerTitle.startsWith(prefix)
    );

    // Additional check: if title is very long (>50 chars) or ends with "...", it might be a truncated user message
    const isLikelyUserMessage =
      currentTitle.length > 50 || currentTitle.endsWith('...');

    const shouldUpdate = isFallback || isLikelyUserMessage;

    console.log(
      `[TitleGeneration] Title "${currentTitle}" - isFallback: ${isFallback}, isLikelyUserMessage: ${isLikelyUserMessage}, shouldUpdate: ${shouldUpdate}`
    );

    return shouldUpdate;
  }
}

export const titleGenerationService = new TitleGenerationService();
