import { conversations, db } from '@/database';
import { eq } from 'drizzle-orm';

import { analyticsService } from './analytics';
// eslint-disable-next-line import-x/no-cycle
import { completionService } from './completion';

interface TitleGenerationOptions {
  message: string;
  user: { id: string };
  workspace: { slug: string };
  conversationId?: string;
  aiResponse?: string; // Optional AI response content to help generate better titles
}

interface TitleGenerationResult {
  title: string;
  generated: boolean; // true if generated by AI, false if fallback
}

class TitleGenerationService {
  private readonly titleGenerationSystemPrompt = `You are a conversation title generator.

Your task is to create a concise, descriptive title for a conversation based on the user's message and optionally the AI's response.

Rules:
- Create a title that summarizes the main topic or intent
- Maximum 50 characters
- Use title case or concise noun phrases
- Do NOT repeat the user's exact words
- Do NOT include quotes, punctuation at the end, or extra text
- Do NOT say "Title Generator" or similar meta-text
- Focus on the core subject matter
- If AI response is provided, use it to better understand the conversation context

Examples:
- User: "How do I connect to my PostgreSQL database?"
- Title: "PostgreSQL Connection Help"

- User: "Can you help me write a Python script to process CSV files?"
- AI Response: "I'll help you create a Python script using pandas to read and process CSV files..."
- Title: "Python CSV Processing Script"

- User: "What's the best way to optimize my React app performance?"
- AI Response: "Here are several optimization techniques for React apps: code splitting, memoization, lazy loading..."
- Title: "React Performance Optimization"

Return only the title, nothing else.`;

  constructor() {
    // No need for any initialization
  }

  /**
   * Generates a title for a conversation using direct LLM completion
   */
  async generateTitle(
    options: TitleGenerationOptions
  ): Promise<TitleGenerationResult> {
    // Create fallback title
    const fallbackTitle = this.createFallbackTitle();

    try {
      // Build the prompt for title generation
      let titlePrompt = `User message: "${options.message}"`;

      if (options.aiResponse) {
        // Truncate AI response if too long to avoid token limits
        const truncatedResponse =
          options.aiResponse.length > 500
            ? options.aiResponse.substring(0, 500) + '...'
            : options.aiResponse;
        titlePrompt += `\n\nAI response: "${truncatedResponse}"`;
      }

      // Call the completion service
      const response = await completionService.createResponse({
        messages: [
          {
            id: '1',
            conversationId: options.conversationId || '',
            role: 'user',
            content: titlePrompt,
            messageType: 'text',
          },
        ],
        conversationId: options.conversationId || '',
        provider: 'groq',
        model: 'llama-3.1-8b-instant',
        temperature: 1,
        maxTokens: 50,
        systemPrompt: this.titleGenerationSystemPrompt,
        useAgentGraph: false,
      });

      let generatedTitle = response.content.trim();

      // Clean up the generated title
      generatedTitle = this.cleanTitle(generatedTitle);

      // Validate the generated title
      if (this.isValidTitle(generatedTitle)) {
        return {
          title: generatedTitle,
          generated: true,
        };
      } else {
        return {
          title: fallbackTitle,
          generated: false,
        };
      }
    } catch (error) {
      // Log analytics for title generation failure
      if (options.conversationId) {
        analyticsService.logError(
          'title_generation_failed',
          error instanceof Error ? error.message : 'Unknown error',
          options.conversationId
        );
      }

      return {
        title: fallbackTitle,
        generated: false,
      };
    }
  }

  /**
   * Updates a conversation title if it's still using a fallback/default title
   */
  async updateConversationTitleIfNeeded(
    conversationId: string,
    options: Omit<TitleGenerationOptions, 'conversationId'>
  ): Promise<boolean> {
    try {
      // Get the current conversation
      const conversation = await db
        .select()
        .from(conversations)
        .where(eq(conversations.id, conversationId))
        .limit(1);

      if (!conversation.length) {
        console.log(
          `[TitleGeneration] ❌ Conversation ${conversationId} not found`
        );
        return false;
      }

      const currentTitle = conversation[0].title;
      console.log(`[TitleGeneration] Current title: "${currentTitle}"`);

      // Check if the title looks like a fallback/default title
      if (!this.shouldUpdateTitle(currentTitle)) {
        console.log(
          `[TitleGeneration] ✅ Title "${currentTitle}" doesn't need updating`
        );
        return false;
      }

      console.log(
        `[TitleGeneration] 🔄 Title "${currentTitle}" needs updating, generating new title...`
      );

      // Generate new title
      const result = await this.generateTitle({
        ...options,
        conversationId,
      });

      // Only update if we got a generated title (not fallback)
      if (result.generated) {
        console.log(
          `[TitleGeneration] ✅ Updating conversation ${conversationId} title from "${currentTitle}" to "${result.title}"`
        );

        await db
          .update(conversations)
          .set({
            title: result.title,
            updatedAt: new Date(),
          })
          .where(eq(conversations.id, conversationId));

        // Log analytics for successful title update
        analyticsService.logCustomEvent({
          eventType: 'conversation_updated',
          conversationId,
          eventData: {
            titleUpdated: true,
            oldTitle: currentTitle,
            newTitle: result.title,
            automated: true,
          },
        });

        return true;
      } else {
        console.log(
          `[TitleGeneration] ❌ Title generation failed, keeping current title: "${currentTitle}"`
        );
      }

      return false;
    } catch (error) {
      console.error(
        `[TitleGeneration] ❌ Failed to update conversation title for ${conversationId}:`,
        error
      );
      return false;
    }
  }

  /**
   * Creates a fallback title
   */
  createFallbackTitle(): string {
    const timestamp = new Date().toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
    return `untitled - ${timestamp}`;
  }

  /**
   * Updates a conversation title with AI response context
   * This should be called after the AI has responded to get a better title
   */
  async updateTitleWithAIResponse(
    conversationId: string,
    userMessage: string,
    aiResponse: string,
    options: Omit<
      TitleGenerationOptions,
      'message' | 'conversationId' | 'aiResponse'
    >
  ): Promise<boolean> {
    console.log(
      `[TitleGeneration] Updating title for conversation ${conversationId} with AI response context`
    );

    try {
      const result = await this.generateTitle({
        message: userMessage,
        aiResponse,
        conversationId,
        ...options,
      });

      if (result.generated) {
        // Update the conversation title
        await db
          .update(conversations)
          .set({
            title: result.title,
            updatedAt: new Date(),
          })
          .where(eq(conversations.id, conversationId));

        console.log(
          `[TitleGeneration] ✅ Updated conversation ${conversationId} title to: "${result.title}"`
        );

        // Log analytics for successful title update
        analyticsService.logCustomEvent({
          eventType: 'conversation_updated',
          conversationId,
          eventData: {
            titleUpdated: true,
            newTitle: result.title,
            automated: true,
            withAIResponse: true,
          },
        });

        return true;
      } else {
        console.log(
          `[TitleGeneration] ❌ Title generation with AI response failed for conversation ${conversationId}`
        );
        return false;
      }
    } catch (error) {
      console.error(
        `[TitleGeneration] ❌ Failed to update title with AI response for conversation ${conversationId}:`,
        error
      );
      return false;
    }
  }

  /**
   * Cleans and normalizes a generated title
   */
  private cleanTitle(title: string): string {
    // Remove quotes and extra whitespace
    let cleaned = title
      .trim()
      .replace(/^["'`]+|["'`]+$/g, '') // Remove quotes at start/end
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim();

    // Limit length
    const maxLength = 50;
    if (cleaned.length > maxLength) {
      cleaned = cleaned.substring(0, maxLength - 3) + '...';
    }

    return cleaned;
  }

  /**
   * Validates if a generated title is acceptable
   */
  private isValidTitle(title: string): boolean {
    if (!title || title.length === 0) {
      return false;
    }

    // Check for obvious AI artifacts or refusals
    const lowerTitle = title.toLowerCase();
    const invalidPatterns = [
      'i cannot',
      "i can't",
      'sorry',
      'unable to',
      'as an ai',
      'as a language model',
      'no title',
    ];

    return !invalidPatterns.some((pattern) => lowerTitle.includes(pattern));
  }

  /**
   * Determines if a conversation title should be updated
   */
  private shouldUpdateTitle(currentTitle: string): boolean {
    if (!currentTitle) {
      return true;
    }

    const lowerTitle = currentTitle.toLowerCase();

    // Check if title starts with common fallback patterns
    const fallbackPrefixes = [
      'untitled',
      'new conversation',
      'query generation:',
      'script generation:',
    ];

    const isFallback = fallbackPrefixes.some((prefix) =>
      lowerTitle.startsWith(prefix)
    );

    // Additional check: if title is very long (>50 chars) or ends with "...", it might be a truncated user message
    const isLikelyUserMessage =
      currentTitle.length > 50 || currentTitle.endsWith('...');

    const shouldUpdate = isFallback || isLikelyUserMessage;

    console.log(
      `[TitleGeneration] Title "${currentTitle}" - isFallback: ${isFallback}, isLikelyUserMessage: ${isLikelyUserMessage}, shouldUpdate: ${shouldUpdate}`
    );

    return shouldUpdate;
  }
}

export const titleGenerationService = new TitleGenerationService();
