import { Collection } from '@/types/api/Collection';

/**
 * Get example Repository Collections
 *
 * Array of {@link Collection}
 */
export const collections = (): Collection[] => [
  {
    id: 0,
    name: 'sales',
    original_repository: 'excel-kpis',
    formatted_name: 'excel-kpis.sales',
    type: 'table',
  },
  {
    id: 1,
    name: 'expenses',
    original_repository: 'excel-kpis',
    formatted_name: 'excel-kpis.expenses',
    type: 'table',
  },
  {
    id: 2,
    name: 'profit_by_month',
    original_repository: 'excel-kpis',
    formatted_name: 'excel-kpis.profit_by_month',
    type: 'table',
  },
  {
    id: 3,
    name: 'sessions',
    original_repository: 'main-google-analytics',
    formatted_name: 'main-google-analytics.sessions',
    type: 'table',
  },
  {
    id: 4,
    name: 'users',
    original_repository: 'main-google-analytics',
    formatted_name: 'main-google-analytics.users',
    type: 'table',
  },
  {
    id: 5,
    name: 'pageviews',
    original_repository: 'main-google-analytics',
    formatted_name: 'main-google-analytics.pageviews',
    type: 'table',
  },
  {
    id: 6,
    name: 'events',
    original_repository: 'main-google-analytics',
    formatted_name: 'main-google-analytics.events',
    type: 'table',
  },
  {
    id: 7,
    name: 'users',
    original_repository: 'app-usage-data',
    formatted_name: 'app-usage-data.users',
    type: 'table',
  },
  {
    id: 8,
    name: 'downloads',
    original_repository: 'app-usage-data',
    formatted_name: 'app-usage-data.downloads',
    type: 'table',
  },
  {
    id: 9,
    name: 'sessions',
    original_repository: 'app-usage-data',
    formatted_name: 'app-usage-data.sessions',
    type: 'table',
  },
  {
    id: 10,
    name: 'purchase_events',
    original_repository: 'app-usage-data',
    formatted_name: 'app-usage-data.purchase_events',
    type: 'table',
  },
  {
    id: 11,
    name: 'ad_clicks',
    original_repository: 'app-usage-data',
    formatted_name: 'app-usage-data.ad_clicks',
    type: 'table',
  },
  {
    id: 12,
    name: 'ad_impressions',
    original_repository: 'app-use-data',
    formatted_name: 'app-usage-data.ad_impressions',
    type: 'table',
  },
  {
    id: 13,
    name: 'sales',
    original_repository: 'kpis-from-excel',
    formatted_name: 'kpis-from-excel.sales',
    type: 'table',
  },
  {
    id: 14,
    name: 'expenses',
    original_repository: 'kpis-from-excel',
    formatted_name: 'kpis-from-excel.expenses',
    type: 'table',
  },
  {
    id: 15,
    name: 'profit_by_month',
    original_repository: 'kpis-from-excel',
    formatted_name: 'kpis-from-excel.profit_by_month',
    type: 'table',
  },
  {
    id: 16,
    name: 'inventory',
    original_repository: 'management-data-from-excel',
    formatted_name: 'management-data-from-excel.inventory',
    type: 'table',
  },
  {
    id: 17,
    name: 'employees',
    original_repository: 'management-data-from-excel',
    formatted_name: 'management-data-from-excel.employees',
    type: 'table',
  },
  {
    id: 18,
    name: 'sales',
    original_repository: 'google-sheets-kpis',
    formatted_name: 'google-sheets-kpis.sales',
    type: 'table',
  },
  {
    id: 19,
    name: 'inventory',
    original_repository: 'google-sheets-kpis',
    formatted_name: 'google-sheets-kpis.inventory',
    type: 'table',
  },
  {
    id: 20,
    name: 'expenses',
    original_repository: 'google-sheets-kpis',
    formatted_name: 'google-sheets-kpis.expenses',
    type: 'table',
  },
  {
    id: 21,
    name: 'profit_by_month',
    original_repository: 'google-sheets-kpis',
    formatted_name: 'google-sheets-kpis.profit_by_month',
    type: 'table',
  },
  {
    id: 22,
    name: 'employees',
    original_repository: 'google-sheets-kpis',
    formatted_name: 'google-sheets-kpis.employees',
    type: 'table',
  },
  {
    id: 23,
    name: 'top-100-ad-clicking-users',
    original_repository: 'top-100-ad-clicking-users',
    formatted_name: 'top-100-ad-clicking-users.top-100-ad-clicking-users',
    type: 'table',
  },
];
