import { Commit } from '@/types/core/Commit';

export const commits: () => Commit[] = () => [
  {
    hash: 'abc123',
    message: 'Initial commit',
    description: 'Initial commit of the project',
    timestamp: '2023-10-01T12:00:00Z',
    author: 'John Doe',
    previousHash: '',
    branch: 'main',
  },
  {
    hash: 'def456',
    message: 'Added new feature',
    description: 'Added a new feature to the project',
    timestamp: '2023-10-02T14:30:00Z',
    author: 'Jane Smith',
    previousHash: 'abc123',
    branch: 'main',
  },
  {
    hash: 'ghi789',
    message: 'Fixed bug',
    description: 'Fixed a bug in the project',
    timestamp: '2023-10-03T16:45:00Z',
    author: 'Alice Johnson',
    previousHash: 'def456',
    branch: 'main',
  },
  {
    hash: 'jkl012',
    message: 'Refactored code',
    description: 'Refactored the codebase for better performance',
    timestamp: '2023-10-04T10:20:00Z',
    author: 'Bob Brown',
    previousHash: 'ghi789',
    branch: 'main',
  },
  {
    hash: 'mno345',
    message: 'Updated documentation',
    description: 'Updated project documentation',
    timestamp: '2023-10-05T09:15:00Z',
    author: 'Carol White',
    previousHash: 'jkl012',
    branch: 'main',
  },
  {
    hash: 'pqr678',
    message: 'Improved performance',
    description: 'Optimized code for better performance',
    timestamp: '2023-10-06T11:45:00Z',
    author: 'David Green',
    previousHash: 'mno345',
    branch: 'main',
  },
  {
    hash: 'stu901',
    message: 'Added unit tests',
    description: 'Added unit tests for the project',
    timestamp: '2023-10-07T13:30:00Z',
    author: 'Eve Black',
    previousHash: 'pqr678',
    branch: 'main',
  },
  {
    hash: 'vwx234',
    message: 'Fixed security issue',
    description: 'Fixed a security vulnerability in the project',
    timestamp: '2023-10-08T15:00:00Z',
    author: 'Frank Blue',
    previousHash: 'stu901',
    branch: 'main',
  },
  {
    hash: 'yz5678',
    message: 'Merged feature branch',
    description: 'Merged feature branch into main',
    timestamp: '2023-10-09T17:20:00Z',
    author: 'Grace Yellow',
    previousHash: 'vwx234',
    branch: 'main',
  },
  {
    hash: 'abc901',
    message: 'Hotfix for production bug',
    description: 'Hotfix for critical bug in production',
    timestamp: '2023-10-10T19:00:00Z',
    author: 'Hank Purple',
    previousHash: 'yz5678',
    branch: 'main',
  },
];
