import {
  Connector,
  ConnectorCapability,
  ConnectorCategory,
  ConnectorConfigurationValidationResult,
} from '@/types/core/Connector';

/**
 * Get example connectors
 *
 * Array of {@link Connector}
 */
export const connectors: () => Connector[] = () => [
  {
    id: 'connector-0',
    name: 'PostgreSQL',
    description: 'Sync data to and from PostgreSQL databases',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/postgresql',
    logo_url: '/ui-assets/brands/postgres-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US', 'fi-FI'],
    primary_category: ConnectorCategory.Database,
    categories: [ConnectorCategory.Database],
    author_email: 'support@irmin.io',
    documentation:
      'Supports syncing structured data between PostgreSQL and Irmin.',
    read_more_url: 'https://postgresql.org',
  },
  {
    id: 'connector-1',
    name: 'MySQL',
    description: 'Sync data to and from MySQL databases',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/mysql',
    logo_url: '/ui-assets/brands/mysql-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US', 'fi-FI'],
    primary_category: ConnectorCategory.Database,
    categories: [ConnectorCategory.Database],
    author_email: 'support@irmin.io',
    documentation:
      'Enables MySQL database integration with Irmin for seamless data flows.',
    read_more_url: 'https://mysql.org',
  },
  {
    id: 'connector-2',
    name: 'MongoDB',
    description: 'Sync data to and from MongoDB databases',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/mongodb',
    logo_url: '/ui-assets/brands/mongodb-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US', 'fi-FI'],
    primary_category: ConnectorCategory.Database,
    categories: [ConnectorCategory.Database],
    author_email: 'support@irmin.io',
    documentation: 'Supports integration of unstructured data with MongoDB.',
    read_more_url: 'https://mongodb.org',
  },
  {
    id: 'connector-3',
    name: 'Google Sheets',
    description: 'Sync data to and from Google Sheets',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/google-sheets',
    logo_url: '/ui-assets/brands/google-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.Storage,
    categories: [ConnectorCategory.Storage],
    author_email: 'support@irmin.io',
    documentation: 'Integrates with Google Sheets for bidirectional data sync.',
    read_more_url: 'https://sheets.google.com',
  },
  {
    id: 'connector-4',
    name: 'Google Analytics',
    description: 'Sync data from Google Analytics',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/google-analytics',
    logo_url: '/ui-assets/brands/google-analytics-logo.svg',
    capabilities: [ConnectorCapability.PullFullSync],
    locales: ['en-US'],
    primary_category: ConnectorCategory.Analytics,
    categories: [ConnectorCategory.Analytics],
    author_email: 'support@irmin.io',
    documentation: 'Fetch analytical data from Google Analytics to Irmin.',
    read_more_url: 'https://analytics.google.com',
  },
  {
    id: 'connector-5',
    name: 'Excel',
    description: 'Upload a local Excel file to Irmin',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/excel',
    logo_url: '/ui-assets/brands/microsoft-logo.svg',
    capabilities: [ConnectorCapability.PullFullSync],
    locales: ['en-US'],
    primary_category: ConnectorCategory.Storage,
    categories: [ConnectorCategory.Storage],
    author_email: 'support@irmin.io',
    documentation: 'Enables uploading Excel files for processing in Irmin.',
    read_more_url: 'https://microsoft.com/excel',
  },
  {
    id: 'connector-6',
    name: 'Pipedrive',
    description: 'Sync data to and from Pipedrive CRM',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/pipedrive',
    logo_url: '/ui-assets/brands/pipedrive-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US', 'fi-FI'],
    primary_category: ConnectorCategory.CRM,
    categories: [ConnectorCategory.CRM],
    author_email: 'support@irmin.io',
    documentation:
      'Supports syncing customer relationship data with Pipedrive.',
    read_more_url: 'https://pipedrive.com',
  },
  {
    id: 'connector-7',
    name: 'HubSpot',
    description: 'Sync data to and from HubSpot CRM',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/hubspot',
    logo_url: '/ui-assets/brands/hubspot-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.CRM,
    categories: [ConnectorCategory.CRM],
    author_email: 'support@irmin.io',
    documentation:
      'Allows data integration and synchronization with HubSpot CRM.',
    read_more_url: 'https://hubspot.com',
  },
  {
    id: 'connector-8',
    name: 'Microsoft Dynamics',
    description: 'Sync data to and from Microsoft Dynamics CRM',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/microsoft-dynamics',
    logo_url: '/ui-assets/brands/microsoft-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.CRM,
    categories: [ConnectorCategory.CRM],
    author_email: 'support@irmin.io',
    documentation: 'Facilitates CRM data integration with Microsoft Dynamics.',
    read_more_url: 'https://microsoft.com/dynamics',
  },
  {
    id: 'connector-9',
    name: 'Salesforce',
    description: 'Sync data to and from Salesforce CRM',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/salesforce',
    logo_url: '/ui-assets/brands/salesforce-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.CRM,
    categories: [ConnectorCategory.CRM],
    author_email: 'support@irmin.io',
    documentation: 'Provides seamless integration with Salesforce CRM.',
    read_more_url: 'https://salesforce.com',
  },
  {
    id: 'connector-10',
    name: 'Shopify',
    description: 'Sync data to and from Shopify',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/shopify',
    logo_url: '/ui-assets/brands/shopify-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.ECommerce,
    categories: [ConnectorCategory.ECommerce],
    author_email: 'support@irmin.io',
    documentation: 'Facilitates data synchronization with Shopify.',
    read_more_url: 'https://shopify.com',
  },
  {
    id: 'connector-11',
    name: 'Stripe',
    description: 'Sync data to and from Stripe',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/stripe',
    logo_url: '/ui-assets/brands/stripe-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.Payment,
    categories: [ConnectorCategory.Payment],
    author_email: 'support@irmin.io',
    documentation: 'Enables payment data integration with Stripe.',
    read_more_url: 'https://stripe.com',
  },
  {
    id: 'connector-12',
    name: 'Mailchimp',
    description: 'Sync data to and from Mailchimp',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/mailchimp',
    logo_url: '/ui-assets/brands/mailchimp-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.Marketing,
    categories: [ConnectorCategory.Marketing],
    author_email: 'support@irmin.io',
    documentation: 'Supports syncing marketing data with Mailchimp.',
    read_more_url: 'https://mailchimp.com',
  },
  {
    id: 'connector-13',
    name: 'SendGrid',
    description: 'Sync data to and from SendGrid',
    version: '1.0.0',
    structure_version: '1.0.0',
    author: 'Irmin Team',
    api_base_url: 'https://api.irmin-connectors/sendgrid',
    logo_url: '/ui-assets/brands/sendgrid-logo.svg',
    capabilities: [
      ConnectorCapability.PullFullSync,
      ConnectorCapability.PushFullSync,
    ],
    locales: ['en-US'],
    primary_category: ConnectorCategory.Messaging,
    categories: [ConnectorCategory.Messaging],
    author_email: 'support@irmin.io',
    documentation:
      'Facilitates data synchronization with SendGrid for email services.',
    read_more_url: 'https://sendgrid.com',
  },
];

export const connectorConfigurationValidationResult: ConnectorConfigurationValidationResult =
  {
    ok: true,
    can_connect: true,
    connection_details_valid: true,
    connection_settings_valid: true,
  };
