import { Connector } from '@/types/core/Connector';

/**
 * Get example connectors
 *
 * Array of {@link Connector}
 */
export const connectors: () => Connector[] = () => [
  {
    id: 0,
    name: 'PostgreSQL',
    logo: '/ui-assets/brands/postgres-logo.svg',
    description: 'Sync data to and from PostgreSQL databases',
    category: 'Database',
    url: 'https://postgresql.org',
  },
  {
    id: 1,
    name: 'MySQL',
    logo: '/ui-assets/brands/mysql-logo.svg',
    description: 'Sync data to and from MySQL databases',
    category: 'Database',
    url: 'https://mysql.org',
  },
  {
    id: 2,
    name: 'MongoDB',
    logo: '/ui-assets/brands/mongodb-logo.svg',
    description: 'Sync data to and from MongoDB databases',
    category: 'Database',
    url: 'https://mongodb.org',
  },
  {
    id: 3,
    name: 'Google Sheets',
    logo: '/ui-assets/brands/google-logo.svg',
    description: 'Sync data to and from Google Sheets',
    category: 'Cloud',
    url: 'https://sheets.google.com',
  },
  {
    id: 4,
    name: 'Google Analytics',
    logo: '/ui-assets/brands/google-analytics-logo.svg',
    description: 'Sync data from Google Analytics',
    category: 'Analytics',
    url: 'https://analytics.google.com',
  },
  {
    id: 5,
    name: 'Excel',
    logo: '/ui-assets/brands/microsoft-logo.svg',
    description: 'Upload a local Excel file to Irmin',
    category: 'Cloud',
    url: 'https://microsoft.com/excel',
  },
  {
    id: 6,
    name: 'Pipedrive',
    logo: '/ui-assets/brands/pipedrive-logo.svg',
    description: 'Sync data to and from Pipedrive CRM',
    category: 'CRM',
    url: 'https://pipedrive.com',
  },
  {
    id: 7,
    name: 'HubSpot',
    logo: '/ui-assets/brands/hubspot-logo.svg',
    description: 'Sync data to and from HubSpot CRM',
    category: 'CRM',
    url: 'https://hubspot.com',
  },
  {
    id: 8,
    name: 'Microsoft Dynamics',
    logo: '/ui-assets/brands/microsoft-logo.svg',
    description: 'Sync data to and from Microsoft Dynamics CRM',
    category: 'CRM',
    url: 'https://microsoft.com/dynamics',
  },
  {
    id: 9,
    name: 'Salesforce',
    logo: '/ui-assets/brands/salesforce-logo.svg',
    description: 'Sync data to and from Salesforce CRM',
    category: 'CRM',
    url: 'https://salesforce.com',
  },
  {
    id: 10,
    name: 'Shopify',
    logo: '/ui-assets/brands/shopify-logo.svg',
    description: 'Sync data to and from Shopify',
    category: 'E-commerce',
    url: 'https://shopify.com',
  },
  {
    id: 11,
    name: 'Stripe',
    logo: '/ui-assets/brands/stripe-logo.svg',
    description: 'Sync data to and from Stripe',
    category: 'Payments',
    url: 'https://stripe.com',
  },
  {
    id: 12,
    name: 'Mailchimp',
    logo: '/ui-assets/brands/mailchimp-logo.svg',
    description: 'Sync data to and from Mailchimp',
    category: 'Marketing',
    url: 'https://mailchimp.com',
  },
  {
    id: 13,
    name: 'SendGrid',
    logo: '/ui-assets/brands/sendgrid-logo.svg',
    description: 'Sync data to and from SendGrid',
    category: 'Email',
    url: 'https://sendgrid.com',
  },
];
