import { StyleSheet } from '@react-pdf/renderer';

export const PDF_COLORS = {
  paper: '#f6f4ed',
  card: '#faf9f6',
  ink: '#171c1c',
  mutedInk: '#5c6666',
  border: '#cbc8c2',
  muted: '#e2dfd7',
  accent: '#799310',
  accentTint: '#e5e9cc',
} as const;

export const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: PDF_COLORS.ink,
    backgroundColor: PDF_COLORS.paper,
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.accent,
  },
  logoText: {
    fontSize: 24,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 4,
    color: PDF_COLORS.ink,
    marginBottom: 8,
  },
  headerMeta: {
    fontSize: 9,
    color: PDF_COLORS.mutedInk,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    marginTop: 24,
    marginBottom: 4,
  },
  sectionDescription: {
    fontSize: 9,
    color: PDF_COLORS.mutedInk,
    marginBottom: 16,
  },
  card: {
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 2,
    padding: 12,
    marginBottom: 12,
    backgroundColor: PDF_COLORS.card,
  },
  cardTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
    color: PDF_COLORS.ink,
    textDecoration: 'underline',
  },
  cardDescription: {
    fontSize: 9,
    color: PDF_COLORS.mutedInk,
    marginBottom: 8,
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  fieldLabel: {
    fontSize: 9,
    color: PDF_COLORS.mutedInk,
    width: 100,
  },
  fieldValue: {
    fontSize: 10,
    color: PDF_COLORS.ink,
    flex: 1,
  },
  tag: {
    fontSize: 8,
    borderWidth: 0.5,
    borderColor: PDF_COLORS.border,
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginRight: 4,
    color: PDF_COLORS.ink,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  statBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 2,
    padding: 8,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
  },
  statLabel: {
    fontSize: 8,
    color: PDF_COLORS.mutedInk,
    marginTop: 2,
  },
  groupTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.mutedInk,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 2,
    padding: 16,
    marginBottom: 16,
    backgroundColor: PDF_COLORS.card,
  },
  summaryTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
  },
  summarySlug: {
    fontSize: 10,
    color: PDF_COLORS.mutedInk,
  },
  mdHeading: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginTop: 8,
    marginBottom: 4,
  },
  mdSubheading: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginTop: 6,
    marginBottom: 3,
  },
  mdParagraph: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 6,
  },
  mdListItem: {
    fontSize: 10,
    lineHeight: 1.5,
    paddingLeft: 12,
    marginBottom: 2,
  },
  mdBold: {
    fontFamily: 'Helvetica-Bold',
  },
  mdItalic: {
    fontStyle: 'italic',
  },
  link: {
    color: PDF_COLORS.ink,
    textDecoration: 'underline',
  },
  notesSection: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.border,
  },
  notesHeading: {
    fontSize: 9,
    color: PDF_COLORS.mutedInk,
    marginBottom: 4,
  },
  flowChain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  flowNode: {
    fontSize: 9,
    borderWidth: 0.5,
    borderColor: PDF_COLORS.border,
    borderRadius: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: PDF_COLORS.card,
  },
  flowArrow: {
    fontSize: 9,
    color: PDF_COLORS.mutedInk,
  },
  statusBadge: {
    fontSize: 8,
    borderRadius: 2,
    borderWidth: 0.5,
    borderColor: PDF_COLORS.accent,
    paddingHorizontal: 4,
    paddingVertical: 1,
    color: PDF_COLORS.ink,
    backgroundColor: PDF_COLORS.accentTint,
  },
  typeBadge: {
    fontSize: 8,
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    color: PDF_COLORS.ink,
    backgroundColor: PDF_COLORS.muted,
  },
});
