import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#111827',
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  logoText: {
    fontSize: 24,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 4,
    color: '#17506b',
    marginBottom: 8,
  },
  headerMeta: {
    fontSize: 9,
    color: '#6b7280',
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    marginTop: 24,
    marginBottom: 4,
  },
  sectionDescription: {
    fontSize: 9,
    color: '#6b7280',
    marginBottom: 16,
  },
  card: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 4,
    padding: 12,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
    color: '#17506b',
    textDecoration: 'underline',
  },
  cardDescription: {
    fontSize: 9,
    color: '#6b7280',
    marginBottom: 8,
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  fieldLabel: {
    fontSize: 9,
    color: '#6b7280',
    width: 100,
  },
  fieldValue: {
    fontSize: 10,
    color: '#111827',
    flex: 1,
  },
  tag: {
    fontSize: 8,
    borderWidth: 0.5,
    borderColor: '#d1d5db',
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginRight: 4,
    color: '#374151',
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  statBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 4,
    padding: 8,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
  },
  statLabel: {
    fontSize: 8,
    color: '#6b7280',
    marginTop: 2,
  },
  groupTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 4,
    padding: 16,
    marginBottom: 16,
  },
  summaryTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
  },
  summarySlug: {
    fontSize: 10,
    color: '#6b7280',
  },
  mdHeading: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginTop: 8,
    marginBottom: 4,
  },
  mdSubheading: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginTop: 6,
    marginBottom: 3,
  },
  mdParagraph: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 6,
  },
  mdListItem: {
    fontSize: 10,
    lineHeight: 1.5,
    paddingLeft: 12,
    marginBottom: 2,
  },
  mdBold: {
    fontFamily: 'Helvetica-Bold',
  },
  mdItalic: {
    fontStyle: 'italic',
  },
  link: {
    color: '#17506b',
    textDecoration: 'underline',
  },
  notesSection: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  notesHeading: {
    fontSize: 9,
    color: '#6b7280',
    marginBottom: 4,
  },
  flowChain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  flowNode: {
    fontSize: 9,
    borderWidth: 0.5,
    borderColor: '#d1d5db',
    borderRadius: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: '#f9fafb',
  },
  flowArrow: {
    fontSize: 9,
    color: '#9ca3af',
  },
  statusBadge: {
    fontSize: 8,
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    color: '#ffffff',
    backgroundColor: '#22c55e',
  },
  typeBadge: {
    fontSize: 8,
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    color: '#374151',
    backgroundColor: '#e5e7eb',
  },
});
